[FLINK-16597] handle exception thrown from close method in OutputFormat
apache/flink pull request #11480
Opened 2020-03-22 09:03 UTC by Jiayi-Liao

## What is the purpose of the change

The `format.close()` in finally block in #DataSinkTask#invoke is not properly handled but only logged.

## Brief change log

1. Remove the `format.close()` in finally block and add a new try-catch-finally block inside the original try-catch block.

## Verifying this change

Unit tests to verify the `tryCleanupOnError` is executed when exception is thrown from `format.close()`.

## Does this pull request potentially affect one of the following parts:

## Documentation

2020-12-09 21:10 UTC, rkhachatryan requested changes
Thanks for the contribution @Jiayi-Liao and sorry for the delay with reviewing.

Can you please:
- add Jira ticket id and component to the commit message (see [guidelines](https://flink.apache.org/contributing/code-style-and-quality-pull-requests.html#commit-naming-conventions))
- rebase to master
- update `cancel` method and adjust test (see the comments below)

2020-12-09 21:10 UTC, rkhachatryan commented on flink-runtime/src/test/java/org/apache/flink/runtime/operators/DataSinkTaskTest.java
> +	public void testClosingErrorDataSinkTask() throws Exception {
Though the test does check that `close` was called, it doesn't test if the original issues were resolved (order of `close` and `tryCleanupOnError` on `cancel` and `invoke`).

2020-12-10 03:18 UTC, Jiayi-Liao commented
@rkhachatryan I notice that the community is doing the unification of streaming and batch. But this #DataSinkTask can only be used in DataSet job, I'm not sure that this work should be continued.

2020-12-10 09:12 UTC, rkhachatryan commented
I think you're right @Jiayi-Liao, the unification lowers the priority of this issue.
But I doubt that this class will be removed anytime soon, nor should there be any conflicts.

@aljoscha, what do you think?

2020-12-11 09:17 UTC, aljoscha commented
I think there won't be conflicts, but I'm also not eager to review changes for code that will be removed eventually.

2020-12-14 10:05 UTC, rkhachatryan commented
Thanks @aljoscha!
I'm going to close the ticket then. @Jiayi-Liao please reopen it if you'd like this PR to be merged.

2020-12-17 03:31 UTC, closed without merging