[FLINK-19450][python][AZP] Optimize the Python CI Test
apache/flink pull request #13520
Opened 2020-09-30 08:34 UTC by HuangXingBo

## What is the purpose of the change

*This pull request will optimize the Python CI Test*

## Brief change log

  - *Optimize the pyflink test to run in latest python version if triggered by git push*

## Verifying this change

This change added tests and can be verified as follows:

  - *See the ci test whether only run in py38 currently*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

2020-09-30 14:34 UTC, HuangXingBo commented
@flinkbot run azure

2020-10-12 08:11 UTC, HuangXingBo commented
@flinkbot run azure

2020-10-13 01:31 UTC, HuangXingBo commented
From the running results, the python test time can be optimized from about 1 hour and 50 minutes to about 1 hour

2020-10-13 08:35 UTC, rmetzger commented on tools/azure-pipelines/jobs-template.yml
> +      ${{parameters.environment}} ./tools/ci/test_controller.sh $(module) $(Build.Reason); TEST_EXIT_CODE=$?
I don't think you need to pass the variable into the script. The variable should be available as `$BUILD_REASON` in the scripts by default.

2020-10-13 08:36 UTC, rmetzger commented on tools/ci/test_controller.sh
>  	EXIT_CODE=$?
these changes are also not needed

2020-10-13 08:37 UTC, rmetzger requested changes
I believe most of the changes in this PR are not needed, because you can access `$BUILD_REASON` directly from the environment.

2020-10-13 09:02 UTC, HuangXingBo commented
@rmetzger Thanks a lot for the review. I have removed the content of passing the variable of BUILD_REASON.

2020-10-16 08:02 UTC, dianfu approved these changes
@HuangXingBo Thanks a lot for the PR. Good work! It reduces the execution time of python tests a lot. The PR LGTM to me. +1 from my side. 
@rmetzger Thanks a lot for the review! Would you like to take a further look at of this PR?

2020-10-19 07:39 UTC, rmetzger approved these changes
Change looks good

2020-10-19 08:20 UTC, dianfu commented
@rmetzger Thanks for the final review. Merging...

2020-10-19 08:32 UTC, closed without merging