[FLINK-19770][python][test] Changed the PythonProgramOptionTest to be an ITCase.
apache/flink pull request #13756
Opened 2020-10-23 03:41 UTC by shuiqiangchen

## What is the purpose of the change

Fixed the error that PythonProgramOptionsTest requires package phase before execution. 

## Brief change log

Changed the PythonProgramOptionsTest to be an ITCase and the path of dummy job jar from a relative path to absolute path.

## Verifying this change

This change has test case covered by PythonProgramOptionTest.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not documented)

2020-10-23 06:21 UTC, anonymouscodeholic commented
Would it be an overkill to split the test class into two, a normal test (all except one method) and to an IT (the troubling method).  

After this PR it's not clear _why_ does this test need to be an IT.

2020-10-23 06:22 UTC, anonymouscodeholic requested changes

2020-10-23 06:22 UTC, anonymouscodeholic commented on flink-python/src/test/java/org/apache/flink/client/cli/PythonProgramOptionsITCase.java
>   */
Add a comment like "Needs to be in ITCase, because depends on dummy-job-jar"?

2020-10-23 06:40 UTC, shuiqiangchen commented
@anonymouscodeholic Thank you for your suggestions. Exactly, there is only the `testConfigurePythonExecution` need to be run as an IT. It would be better to split the tests in PythonProgramOptionsTest into two class (UTs and ITs) since UT has lower cost. 

>After this PR it's not clear why does this test need to be an IT.

The reason is that it requires to set a job jar to build a `PackagedProgram`, and the dummy job jar used in this test case is built in the packing phase.

2020-10-23 06:50 UTC, anonymouscodeholic commented
> > After this PR it's not clear why does this test need to be an IT.
> 
> The reason is that it requires to set a job jar to build a `PackagedProgram`, and the dummy job jar used in this test case is built in the packing phase.

Sorry, I wasn't being clear enough. I meant just by quickly _reading_ the code, it's not obvious. By looking at the associated JIRA ticket and this PR, it is clear. But I think it'd worth mentioning why the test is an IT also in the codebase.

2020-10-23 06:58 UTC, shuiqiangchen commented
@anonymouscodeholic Sorry, I will add more comments for this test case to make it more intuitive.

2020-10-28 02:51 UTC, shuiqiangchen commented
Hi @anonymouscodeholic ， I have updated the pr according to your suggestions, please have a look at it.

2020-10-28 06:14 UTC, anonymouscodeholic requested changes
Small JavaDoc fix(es) needed. I haven't personally tried running the tests locally, which was the original issue, but this should work.

2020-10-28 06:14 UTC, anonymouscodeholic commented on flink-python/src/test/java/org/apache/flink/client/cli/PythonProgramOptionsITCase.java
> +	 * */
Should be `**/`

2020-10-28 06:14 UTC, anonymouscodeholic commented on flink-python/src/test/java/org/apache/flink/client/cli/PythonProgramOptionsITCase.java
> +	 * */
Maybe also `PackagedProgram` -> `{@link PackagedProgram}`.

2020-10-28 06:34 UTC, shuiqiangchen commented
@anonymouscodeholic Thank you for pointing out the mistake， I have revised them in the latest commit.

2020-10-28 07:29 UTC, anonymouscodeholic approved these changes
Looks good.

2020-10-28 12:25 UTC, shuiqiangchen commented
@flinkbot run azure

2020-10-29 02:04 UTC, dianfu approved these changes
Thanks @shuiqiangchen for the work and thanks @anonymouscodeholic for the review. +1 from my side. Merging...

2020-10-29 02:05 UTC, closed without merging