[FLINK-19527][Doc] Common errors when running with docker on windows
apache/flink pull request #14002
Opened 2020-11-09 20:44 UTC by haseeb1431

## What is the purpose of the change

Try flink experiments spins up couple of docker containers which works fine with non-windows containers. In some cases, when user is running docker on windows, some of script wouldn't work so we have updated the documentation with a workaround. 

Following is the preview

![image](https://user-images.githubusercontent.com/4470055/98594234-aa451f80-22d4-11eb-8a04-28982794b8a5.png)

2020-11-10 00:32 UTC, sjwiesman requested changes
A few comments on the grammar. Two other points: 

1) We put the Jira and component in the commit. Your PR title is correct and should be the commit message. 

2) Take a look at the docs contributing guidelines. I'd like to wrap this in a `note` annotation. 

https://flink.apache.org/contributing/docs-style.html#annotations

2020-11-10 00:32 UTC, sjwiesman commented on docs/try-flink/table_api.md
> +### Docker on windows
We capitalize all proper words in titles along with a new line between the header and the first 

```suggestion
### Docker on Windows

```

2020-11-10 00:32 UTC, sjwiesman commented on docs/try-flink/table_api.md
> +if you're running docker on windows and your data generator container is failing to start then please ensure that you're using right shell.
```suggestion
If you're running docker on windows and your data generator container is failing to start then please ensure that you're using the right shell.
```

Grammar

2020-11-10 00:32 UTC, sjwiesman commented on docs/try-flink/table_api.md
> +For example `docker-entrypoint.sh` for `table-walkthrough_data-generator_1` container requires bash shell.
```suggestion
For example, `docker-entrypoint.sh` for `table-walkthrough_data-generator_1` container requires bash. 
```

2020-11-10 00:32 UTC, sjwiesman commented on docs/try-flink/table_api.md
> +So a workaround is to swith shell to `sh` from `bash` on the first row in `docker-entrypoint.sh` to make it work.
```suggestion
A workaround is to switch shell to `sh` from `bash` on the first row in `docker-entrypoint.sh`.
```

2020-11-10 18:09 UTC, haseeb1431 commented
@sjwiesman Thanks for the inputs. I have addressed all the requested changes. Regarding the wrapping, I have wrapped the message in the "info" because there is no note annotation unless I am missing something. Thanks

![image](https://user-images.githubusercontent.com/4470055/98713722-3fedb700-2388-11eb-8ecf-a1426eeb884a.png)

2020-11-11 14:38 UTC, sjwiesman commented
That's what I meant :) Sorry for being confusing. 

LGTM, merging . . .

2020-11-11 15:17 UTC, closed without merging