[FLINK-20204][docs-zh] Translate page 'upsert-kafka Connector' into Chinese
apache/flink pull request #14126
Opened 2020-11-19 04:44 UTC by caozhen1937

## What is the purpose of the change

Translate page 'upsert-kafka Connector' into Chinese.

## Brief change log

*docs/dev/table/connectors/upsert-kafka.zh.md*
*docs/dev/table/connectors/upsert-kafka.md*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`:(no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

2020-11-19 05:44 UTC, wuchong commented
cc @fsk119 , could you help to review this?

2020-11-19 12:32 UTC, fsk119 reviewed
Thanks for your contribution @caozhen1937 . I left some comments.

2020-11-19 12:32 UTC, fsk119 commented on docs/dev/table/connectors/upsert-kafka.zh.md
> +这意味着，Flink 可以将具有相同 key 的重复记录写入 Kafka topic。但由于连接器是在 upsert 模式下工作的，在作为 source 回读时同一 key 的最后一条记录才会生效。因此，upsert-kafka 连接器可以像 [HBase sink]({{ site.baseurl }}/dev/table/connectors/hbase.html) 一样实现幂等写入。
>但由于连接器是在 upsert 模式下工作的，在作为 source 回读时同一 key 的最后一条记录才会生效。

但由于该连接器以 upsert 的模式工作，该连接器作为 source 读入时，可以确保具有相同主键值下仅最后一条消息会生效。

2020-11-19 12:32 UTC, fsk119 commented on docs/dev/table/connectors/upsert-kafka.zh.md
> +作为 source，upsert-kafka 连接器生产变更日志流，其中每条数据记录代表一个更新或删除事件。更准确地说，数据记录中的 value 被解释为同一 key 的最后一个 value 的 UPDATE，如果有这个 key（如果不存在相应的 key，则该更新被视为 INSERT）。用表来类比，更改日志流中的数据记录被解释为 UPSERT，也称为 INSERT/UPDATE，因为任何具有相同
I think we can keep the `changelog` untranslated.  It's more straightforward for users to understand.


>另外，空 value 以特殊方式解释：具有空 value 的记录表示“DELETE”。

另外， value 为空的消息将会被视作为 DELETE 消息

2020-11-19 12:32 UTC, fsk119 commented on docs/dev/table/connectors/upsert-kafka.zh.md
> +      <td>用于对 Kafka 消息中 key 部分反序列化和序列化的格式。key 字段由 PRIMARY KEY 语法指定。支持的格式包括 <code>'csv'</code>、<code>'json'</code>、<code>'avro'</code>。请参考<a href="{% link dev/table/connectors/formats/index.zh.md %}">
>反序列化和序列化

序列化和反序列化?

2020-11-19 12:32 UTC, fsk119 commented on docs/dev/table/connectors/upsert-kafka.zh.md
> +      <td>用于对 Kafka 消息中 value 部分反序列化和序列化的格式。支持的格式包括 <code>'csv'</code>、<code>'json'</code>、<code>'avro'</code>。请参考<a href="{% link dev/table/connectors/formats/index.zh.md %}">格式</a>页面以获取更多详细信息和格式参数。
ditto

2020-11-19 12:32 UTC, fsk119 commented on docs/dev/table/connectors/upsert-kafka.md
> -In order to set up the upsert-kafka connector, the following table provide dependency information for
Why delete this?

2020-11-19 12:32 UTC, fsk119 commented on docs/dev/table/connectors/upsert-kafka.zh.md
> +作为 sink，upsert-kafka 连接器可以消费变更日志流。它会将 INSERT/UPDATE_AFTER 数据作为正常的 Kafka 消息写入，并且将 DELETE 数据作为具有空 value 的 Kafka 消息写入(表示 key 对应的 value 被删除)。Flink 将根据主键列的值对数据进行分区，从而保证主键上的消息有序，因此同一 key 上的更新/删除消息将落在同一分区中。
变更日志 -> changelog 

> 并且将 DELETE 数据作为具有空 value 的 Kafka 消息写入(表示 key 对应的 value 被删除)

并将 DELETE 数据以 value 为空的的 Kafka 消息写入(表示 对应 key 的消息被删除)

2020-11-19 12:32 UTC, fsk119 commented on docs/dev/table/connectors/upsert-kafka.zh.md
> +Upsert Kafka 用字节存储消息的 key 和 value，因此没有 schema 或数据类型。消息按格式进行反序列化和序列化，例如：csv、json、avro。因此数据类型映射表由指定的格式确定。请参考[格式]({% link dev/table/connectors/formats/index.zh.md %})页面以获取更多详细信息。
反序列化和序列化 -> 序列化和反序列化

2020-11-19 13:19 UTC, caozhen1937 commented on docs/dev/table/connectors/upsert-kafka.zh.md
> +作为 source，upsert-kafka 连接器生产变更日志流，其中每条数据记录代表一个更新或删除事件。更准确地说，数据记录中的 value 被解释为同一 key 的最后一个 value 的 UPDATE，如果有这个 key（如果不存在相应的 key，则该更新被视为 INSERT）。用表来类比，更改日志流中的数据记录被解释为 UPSERT，也称为 INSERT/UPDATE，因为任何具有相同
I agree with you.  Keeping the `changelog`.

2020-11-19 13:24 UTC, caozhen1937 commented on docs/dev/table/connectors/upsert-kafka.md
> -In order to set up the upsert-kafka connector, the following table provide dependency information for
I see FLINK-20093 , so keep the same as it.

2020-11-19 13:25 UTC, caozhen1937 commented on docs/dev/table/connectors/upsert-kafka.zh.md
> +Upsert Kafka 用字节存储消息的 key 和 value，因此没有 schema 或数据类型。消息按格式进行反序列化和序列化，例如：csv、json、avro。因此数据类型映射表由指定的格式确定。请参考[格式]({% link dev/table/connectors/formats/index.zh.md %})页面以获取更多详细信息。
`The messages are deserialized and serialized by formats`

2020-11-19 13:32 UTC, caozhen1937 commented
@fsk119 , Thank you for your comments, I fix some.

2020-11-20 02:06 UTC, fsk119 commented on docs/dev/table/connectors/upsert-kafka.md
> -In order to set up the upsert-kafka connector, the following table provide dependency information for
It's better to delete it. 
![image](https://user-images.githubusercontent.com/33114724/99748713-00f1fb00-2b18-11eb-99b4-949c651e0378.png)

2020-11-20 02:38 UTC, fsk119 requested changes
LGTM except some minor problems.

2020-11-20 02:38 UTC, fsk119 commented on docs/dev/table/connectors/upsert-kafka.zh.md
> +为了设置 upsert-kafka 连接器，下表为项目使用自动化构建工具（例如 Maven 或 SBT ）以及 SQL 客户端使用 SQL JAR 包提供了依赖信息。
Please also delete it as you work in upsert-kafka.md. We should use `sql-connector-download-table.html` to generate the introduction. But currently, we only has English verion page here. 
![image](https://user-images.githubusercontent.com/33114724/99750459-6693b680-2b1b-11eb-881d-338d1ecb31d5.png)

2020-11-20 02:38 UTC, fsk119 commented on docs/dev/table/connectors/upsert-kafka.zh.md
> +作为 source，upsert-kafka 连接器生产 changelog 流，其中每条数据记录代表一个更新或删除事件。更准确地说，数据记录中的 value 被解释为同一 key 的最后一个 value 的 UPDATE，如果有这个 key（如果不存在相应的 key，则该更新被视为 INSERT）。用表来类比，更改日志流中的数据记录被解释为 UPSERT，也称为 INSERT/UPDATE，因
更改日志 -> changelog

2020-11-20 02:38 UTC, fsk119 commented on docs/dev/table/connectors/upsert-kafka.zh.md
> +作为 sink，upsert-kafka 连接器可以消费 changelog 流。它会将 INSERT/UPDATE_AFTER 数据作为正常的 Kafka 消息写入，并将 DELETE 数据以 value 为空的 Kafka 消息写入（表示对应 key 的消息被删除）。Flink 将根据主键列的值对数据进行分区，从而保证主键上的消息有序，因此同一 key 上的更新/删除消息将落在同一分区中。
> Flink 将根据主键列的值对数据进行分区，从而保证主键上的消息有序，因此同一 key 上的更新/删除消息将落在同一分区中

Flink 将根据主键列的值对数据进行分区，从而保证主键上的消息有序，因此同一主键上的更新/删除消息将落在同一分区中。

感觉如果前面用中文的主键，那么后半句也用中文的描述会更为一致。

2020-11-20 02:41 UTC, fsk119 commented on docs/dev/table/connectors/upsert-kafka.zh.md
> +Upsert Kafka 用字节存储消息的 key 和 value，因此没有 schema 或数据类型。消息按格式进行反序列化和序列化，例如：csv、json、avro。因此数据类型映射表由指定的格式确定。请参考[格式]({% link dev/table/connectors/formats/index.zh.md %})页面以获取更多详细信息。
oh. I don't notice the order in English verison. If you have time, please help me to adjust the order.

2020-11-20 02:43 UTC, caozhen1937 commented on docs/dev/table/connectors/upsert-kafka.zh.md
> +作为 sink，upsert-kafka 连接器可以消费 changelog 流。它会将 INSERT/UPDATE_AFTER 数据作为正常的 Kafka 消息写入，并将 DELETE 数据以 value 为空的 Kafka 消息写入（表示对应 key 的消息被删除）。Flink 将根据主键列的值对数据进行分区，从而保证主键上的消息有序，因此同一 key 上的更新/删除消息将落在同一分区中。
I agree with you.

2020-11-20 02:47 UTC, caozhen1937 commented
@fsk119 , Thanks for your comments, I fix it.

2020-11-20 02:56 UTC, fsk119 commented
LGTM. Thanks for your update.

2020-11-20 02:57 UTC, fsk119 approved these changes

2020-11-20 02:57 UTC, fsk119 commented
@wuchong CC

2020-11-20 04:10 UTC, wuchong approved these changes
LGTM.

2020-11-20 04:11 UTC, closed without merging