[FLINK-20299][docs-zh] Update Chinese table overview
apache/flink pull request #14244
Opened 2020-11-27 06:04 UTC by T0UGH

## What is the purpose of the change

Sync `/docs/dev/table/index.zh.md` with the changes introduced in FLINK-18279

commit: 0fd9dc6f717fc4bb0a4e77b2212f317c8f318e03

## Brief change log

- update Chinese translate `/docs/dev/table/index.zh.md`

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? no

2020-11-27 12:41 UTC, T0UGH commented
Hi, @sjwiesman , Could you help review this PR in your free time? thanks.

2020-12-02 01:50 UTC, HuangXingBo requested changes
Hi, you need to rebase `master` code first

2020-12-02 13:00 UTC, T0UGH commented
> Hi, you need to rebase `master` code first

Thank you, I will fix it tomorrow.

2020-12-03 07:30 UTC, T0UGH commented
Hi, @HuangXingBo, I rebased the master branch, and fixed the conflict. Would you review it in your free time?

2025-03-28 06:28 UTC, closed without merging