[Flink-20091][avro] add ignore-parse-error for
apache/flink pull request #14444
Opened 2020-12-21 09:58 UTC by fsk119

## What is the purpose of the change

*Add ignore-parse-error for avro format, avro-confluent.*

## Brief change log

  - *move the option IGNORE_PARSE_ERROR to FactoryUtil*
  - *add the option IGNORE_PARSE_ERROR  for avro and avro-confluent*

## Verifying this change

This change added tests and can be verified as follows:

  - *test when parsing record with the decoder whose schema is different*
 
## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (**yes** / no)
  - If yes, how is the feature documented? (not applicable / **docs** / JavaDocs / not documented)

2020-12-22 03:54 UTC, wuchong requested changes
Thanks for the contribution. I left some comments.


We should also update debezium-avro docs.

2020-12-22 03:54 UTC, wuchong commented on flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroRowDataDeserializationSchema.java
> +	public AvroRowDataDeserializationSchema(
I would suggest to refactor this class into builder pattern. It's hard to maintain to introduce a new constructor when adding a new parameter.

2020-12-22 03:54 UTC, wuchong commented on flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroRowDataDeserializationSchema.java
> +	public AvroRowDataDeserializationSchema(
Besides, this class should be `@Internal` and not `@PublicEvolving`.

2020-12-22 03:54 UTC, wuchong commented on flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroRowDataDeserializationSchema.java
> +	private final Boolean ignoreParseError;
Use primitive type `boolean` otherwise, it maybe `null`.

2020-12-22 03:54 UTC, wuchong commented on flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroRowDataDeSerializationSchemaTest.java
> +		assertThat(actual, org.hamcrest.core.IsNull.nullValue(RowData.class));
Why not use `assertNull(actual)` here?

2020-12-22 03:54 UTC, wuchong commented on flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroRowDataDeSerializationSchemaTest.java
> +		byte[] byteData = serializationSchema.serialize(input);
Would be better to using numberic type to deseriazing string type to verify the parse error. For example:
deserializing `[int: 1, string: abc]` with schema `(int, long)` should get `Row(1, null)`.

I think deserializing null field is not a strong enough test.

2021-10-21 03:00 UTC, fsk119 commented
I am recently busy working in the inner branch. I think I have no time to finish this PR....

2021-11-22 07:43 UTC, closed without merging

2025-11-05 04:10 UTC, qite8676 commented
Hello! Which version is this feature released in?