[FLINK-20385][canal][json] Allow to read metadata for canal-json format
apache/flink pull request #14464
Opened 2020-12-22 13:24 UTC by SteNicholas

## What is the purpose of the change

*Currently FLIP-107 supports reading meta from the Debezium format. According to FLIP-107, metadata should support to be exposed for the Canal JSON format.*

## Brief change log

  - *Let `CanalJsonDeserializationSchema` access and convert those additional fields to metadata columns.*

## Verifying this change

  - *`CanalJsonSerDeSchemaTest` adds `testDeserializationWithMetadata` to whether deserialization of `CanalJsonDeserializationSchema` could read metadata for the Canal JSON format.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

2020-12-24 08:28 UTC, wuchong commented
Hi @SteNicholas , I would like to discuss the metadata keys first. What do you think think just use the keys and types?

- `pk_names ARRAY<STRING>`
- `sql_types MAP<STRING, INT>`
- `table STRING`
- `database STRING`
- `ingestion_timestamp TIMESTAMP(3) WITH LOCAL TIME ZONE`

2020-12-24 08:42 UTC, wuchong reviewed
The change looks good in general. Could you add a IT case in `KafkaChangelogTableITCase` to test kafka+canal-json with metadata accessing?

2020-12-24 08:42 UTC, wuchong commented on flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/canal/CanalJsonDecodingFormat.java
> +		DataType physicalDataType) {
Add indent.

2020-12-24 08:42 UTC, wuchong commented on flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/canal/CanalJsonDecodingFormat.java
> +			MetadataConverter converter) {
Add indent.

2020-12-24 08:42 UTC, wuchong commented on flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/canal/CanalJsonDeserializationSchema.java
> +		List<ReadableMetadata> requestedMetadata) {
Add indent.

2020-12-25 02:54 UTC, SteNicholas commented
> Hi @SteNicholas , I would like to discuss the metadata keys first. What do you think think just use the keys and types?
> 
> * `pk_names ARRAY<STRING>`
> * `sql_types MAP<STRING, INT>`
> * `table STRING`
> * `database STRING`
> * `ingestion_timestamp TIMESTAMP(3) WITH LOCAL TIME ZONE`

IMO, just using the above keys and types is friendly for users to read metadata of the Canal JSON format.

2020-12-25 02:55 UTC, SteNicholas commented
> The change looks good in general. Could you add a IT case in `KafkaChangelogTableITCase` to test kafka+canal-json with metadata accessing?

OK. I would like to add a IT case in `KafkaChangelogTableITCase`.

2020-12-27 10:04 UTC, SteNicholas commented
@wuchong  I have added a IT case in `KafkaChangelogTableITCase` to test Kafka and Canal JSON with metadata accessing.
About the Canal JSON metadata, I prefer to the following keys and types:
 - `database STRING`
 - `table STRING`
 - `sql-type MAP<STRING, INT>`
 - `pk-names ARRAY<STRING>`
 - `ingestion-timestamp TIMESTAMP(3) WITH LOCAL TIME ZONE`
 The name of keys are a little different from yours. What do you think about the above names of keys?

2020-12-27 13:59 UTC, wuchong commented
I'm also fine with that. Will review it tomorrow.

2020-12-27 15:01 UTC, wuchong commented
Btw, could you add documentation for this feature?

2020-12-27 15:29 UTC, SteNicholas commented
> Btw, could you add documentation for this feature?

No problem.

2020-12-27 16:02 UTC, SteNicholas commented
@wuchong I have added the document about the metadata for Canal JSON format. Please help to review the document together.

2020-12-28 04:06 UTC, wuchong commented on docs/dev/table/connectors/formats/canal.md
> +  `origin_table` STRING METADATA FROM 'value.table' VIRTUAL,
Could you list all the metadata columns? I think that would be helpful, esp. for the complex types.

2020-12-28 04:06 UTC, wuchong commented on docs/dev/table/connectors/formats/canal.md
> +  `behavior` STRING
I think we don't need to add backquotes around the column names, because they are not keywords.

2020-12-28 04:06 UTC, wuchong commented on flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaChangelogTableITCase.java
> +				" origin_table STRING METADATA FROM 'value.table' VIRTUAL," +
Could you also test the Map and Array metadatas?

2020-12-28 11:36 UTC, wuchong requested changes

2020-12-28 11:36 UTC, wuchong commented on docs/dev/table/connectors/formats/canal.zh.md
> +  origin_sql_type MAP&lt;STRING, INT&gt; METADATA FROM 'value.sql-type' VIRTUAL,
Don't need to escape the character.

2020-12-28 12:32 UTC, wuchong requested changes

2020-12-28 12:32 UTC, wuchong commented on docs/dev/table/connectors/formats/canal.zh.md
>    origin_pk_names ARRAY&lt;STRING&gt; METADATA FROM 'value.pk-names' VIRTUAL,
Please also modify others and preview the page in local.

2020-12-29 06:25 UTC, SteNicholas commented
@wuchong I have kept code spotless with Maven for conflicts resolution and modified the document. Please help to review again.

2020-12-29 07:02 UTC, wuchong commented on flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaChangelogTableITCase.java
> +        // | 108 | jacket             | water resistent black wind breaker                      |
Could you beautify the format? The same to the debezium one.

2020-12-30 07:40 UTC, wuchong commented
I helped to beautify the format. Will merge this once Azure is passed.

2020-12-30 11:13 UTC, SteNicholas commented
@wuchong Thanks for helping to beautify the format. I have set the time zone for the Canal JSON format metadata `ingestion-timestamp` to solve the Azure failure. Please help to merge once Azure is passed.

2020-12-30 12:14 UTC, wuchong approved these changes
LGTM.

2020-12-31 02:34 UTC, merged

2021-01-07 08:50 UTC, wangfeigithub commented
Nicholas Jiang Jark Wu  I found a bug in the canal code. 'canal-json.table.include' does not filter out the binlog of the specified table correctly, which will cause an error in the parsing section. For example, if I want to read the binlog of canal-json.table.include = 'a' table, there is a source field of int in table a, but at this time if table b also has a source field of string, An error will be reported.

2021-01-07 08:51 UTC, wangfeigithub commented
![image](https://user-images.githubusercontent.com/29723968/103871825-82bdd800-5108-11eb-93ad-55a9b0c7a016.png)
![Uploading image.png…]()

2021-01-07 09:25 UTC, wuchong commented
@wangfeigithub thanks for reporting this. Could you create an JIRA issue for this?