[FLINK-20837] Refactor dynamic SlotID
apache/flink pull request #14560
Opened 2021-01-05 10:35 UTC by KarmaGYZ

## What is the purpose of the change

Refactor dynamic SlotID.
In FLINK-14189, we specified that the SlotID whose slot number is -1 represents the dynamic slot. However, the SlotID with a negative slot number will be treated as invalid in other components, e.g. SlotPool and SlotManager. We have to remove a lot of sanity checks with this change, which is error-prone. The evidence is that there are still some sanity checks that have not been removed, e.g. sanity checks in AllocatedSlotInfo.

In this PR, we refactor the dynamic SlotID:
- In SlotManager, it still uses -1 as slot number when allocating dynamic slot.
- In TM, when allocating dynamic slots, it will asssign an increasing number larger than the numberSlots as the slot number.

## Verifying this change

This change is already covered by existing tests:
- TaskExecutorTest
- TaskSlotTableImplTest

2021-01-06 11:07 UTC, xintongsong requested changes
Thanks for the PR, @KarmaGYZ.
I've left a few comments. Please take a look.

2021-01-06 11:07 UTC, xintongsong commented on flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlotTableImpl.java
> +        if (index < numberSlots) {
Now since the dynamic slots also have unique indexes, we can also insert them into `taskSlots`.

2021-01-06 11:07 UTC, xintongsong commented on flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlotTableImpl.java
> +        } else if (index >= numberSlots) {
If we also insert dynamic slot to the `taskSlot`, we won't need this `else-if` branch anymore.

2021-01-06 11:08 UTC, xintongsong commented
And please take a look at the compiling error reported by AZP.

2021-01-07 07:13 UTC, KarmaGYZ commented
Thanks for the review @xintongsong . PR updated.

2021-01-07 07:46 UTC, xintongsong commented on flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlotTableImpl.java
> +        } else if (!isIndexAlreadyTaken(index)) {
`!` should be removed.

2021-01-07 07:46 UTC, xintongsong commented on flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlotTableImpl.java
> +                    "The static slot with index {} is already assigned to another allocation with id {}.",
Not sure about exposing the concept *static* slot here.

2021-01-07 07:46 UTC, xintongsong commented on flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlotTableImpl.java
> +        resourceProfile = index < numberSlots ? defaultSlotResourceProfile : resourceProfile;
There are 3 occurrences of `index < numberSlots` and 1 occurrence of `index >= numberSlots` in this file.
Let's deduplicate it with a util method.

2021-01-07 09:02 UTC, xintongsong reviewed
It might be better to also add test cases for the duplicate/inconsistent slot allocation, for both static and dynamic slots. (i.e., the logics that the first commit touches.)

2021-01-08 05:09 UTC, xintongsong reviewed
Thanks for updating the PR, @KarmaGYZ.
The changes already look quite good to me. I have only a few minor comments regarding the test verifications.

2021-01-08 05:09 UTC, xintongsong commented on flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlotTableImplTest.java
> +    public void testInconsistentStaticSlotAllocation() throws Exception {
This covers the case trying to allocate the same allocation id to different slot index.
I think we need to also cover the case that different allocation ids trying to take the same slot index

2021-01-08 05:09 UTC, xintongsong commented on flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlotTableImplTest.java
> +    public void testDuplicateDynamicSlotAllocation() throws Exception {
I think we should also verify that the second call of `allocateSlot` does not replace the slot allocated by the first call.

2021-01-08 05:30 UTC, KarmaGYZ commented
PR updated.

2021-01-08 08:36 UTC, xintongsong approved these changes
Thanks @KarmaGYZ. LGTM.
Merging once AZP gives green light.

2021-01-08 10:28 UTC, closed without merging