[FLINK-20862][table] Support creating DataType from TypeInformation
apache/flink pull request #14619
Opened 2021-01-12 12:23 UTC by twalthr

## What is the purpose of the change

This ensures a smooth mapping between `TypeInformation` and `DataType`. A user can decide whether `TypeInformation` should be treated as an entire RAW type or if instances should be converted to logical types on a best effort basis. In any case, a user will not get an exception during conversion anymore because every `TypeInformation` can be mapped to a non-legacy type in the Blink planner.

## Brief change log

- Add a new TypeInformation to DataType converter that is backed by `DataTypeFactory`
- Add API methods for creating a `DataType` either via `DataTypes.of(TypeInformation)` or `DataTypes.RAW(TypeInformation)`

## Verifying this change

This change added tests and can be verified as follows:

- `DataTypesTest`
- `TypeInfoDataTypeConverterTest`
- `TypeInfoDataTypeConverterScalaTest`

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): yes
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: yes
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? yes
  - If yes, how is the feature documented? JavaDocs

2021-01-15 10:51 UTC, dawidwys requested changes

2021-01-15 10:51 UTC, dawidwys commented on flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/TypeInfoDataTypeConverterTest.java
> +                TestSpec.forType(Types.POJO(PojoWithFieldOrder.class))
I think something is wrong with POJO types mapping. Shouldn't the primitive fields be mapped to `NOT NULL` types?
Also from our offline chat it seems bridging classes are also not mapped correctly.

2021-01-15 16:44 UTC, twalthr commented
Thanks for the feedback @dawidwys. I have updated the PR.

2021-01-18 08:25 UTC, dawidwys approved these changes
Looks good now!

2021-01-18 08:25 UTC, dawidwys commented on flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/utils/TypeInfoDataTypeConverter.java
> +                                        .orElseThrow(IllegalArgumentException::new)
nit: I'd rather use `IllegalStateException` as it is more likely an internal Flink error that the `TypeInformation` does not reflect its class.

2021-01-18 08:25 UTC, dawidwys commented on flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/utils/TypeInfoDataTypeConverter.java
> +                            return dataType.bridgedTo(fieldClass);
nit: How about we call `notNull` here, just for clarity.

2021-01-18 14:19 UTC, closed without merging