[FLINK-21102] Add ScaleUpController for declarative scheduler
apache/flink pull request #14874
Opened 2021-02-04 15:28 UTC by rmetzger

## What is the purpose of the change

Add the ScaleUpController according to the definition in FLIP-160.

Note that this change is currently not usable as-is, as the other parts of declarative scheduler are not merged yet (See for the prototype this PR is based on: https://github.com/tillrohrmann/flink/tree/declarative-scheduler)

## Verifying this change

Added a new test

## Does this pull request potentially affect one of the following parts:

No existing code has been touched.

## Documentation

There will be a separate PR for the Declarative Scheduler Docs.

2021-02-05 17:19 UTC, tillrohrmann requested changes
Thanks for creating this PR @rmetzger. I think we should also add the simple implementation of the `ScaleUpController`.

2021-02-05 17:19 UTC, tillrohrmann commented on flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/declarative/scalingpolicy/ScaleUpControllerTest.java
> +    }
I think there is no need to test test classes.

2021-02-05 17:19 UTC, tillrohrmann commented on flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/declarative/scalingpolicy/ScaleUpControllerTest.java
> +public class ScaleUpControllerTest {
```suggestion
public class ScaleUpControllerTest extends TestLogger {
```

2021-02-08 16:12 UTC, rmetzger commented
Thanks a lot for your review & feedback. I addressed all your comments.

2021-02-08 16:53 UTC, tillrohrmann approved these changes
Thanks for updating this PR @rmetzger. The changes look good to me. +1 for merging after updating the missing configuration documentation.

2021-02-08 16:53 UTC, tillrohrmann commented on flink-core/src/main/java/org/apache/flink/configuration/JobManagerOptions.java
> +                            "Configure the minimum increase in parallelism for a job to scale up.");
I would expect that CI won't pass because the configuration documentation has not been updated.

2021-02-08 16:53 UTC, tillrohrmann commented on flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/declarative/scalingpolicy/ReactiveScaleUpController.java
> +        minParallelismIncrease = configuration.get(MIN_PARALLELISM_INCREASE);
we don't have to change it right now but if things become more complex I would suggest to separate the `ReactiveScaleUpController` and how it is set up from a `Configuration`.

2021-02-08 18:15 UTC, rmetzger commented
Thanks a lot for the approval. I'll merge once CI is green.

2021-02-09 07:16 UTC, rmetzger commented
Created JIRA for the failed e2e: https://issues.apache.org/jira/browse/FLINK-21329

2021-02-09 07:23 UTC, merged