[FLINK-22021][table-planner-blink] Fix exception when PushFilterIntoLegacyTableSourceScanRule is faced with INTERVAL types
apache/flink pull request #15424
Opened 2021-03-30 03:34 UTC by TsReaper

## What is the purpose of the change

`PushFilterIntoLegacyTableSourceScanRule` will throw exception when faced with `INTERVAL` types, no matter it can be pushed down or not.

This PR fixes this issue.

## Brief change log

 - Fix exception when PushFilterIntoLegacyTableSourceScanRule is faced with INTERVAL types

## Verifying this change

This change can be verified by running the added tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

2021-03-30 03:40 UTC, JingsongLi requested changes
Thanks @TsReaper for your contribution, left some comments.

2021-03-30 03:40 UTC, JingsongLi commented on flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/PushFilterIntoLegacyTableSourceScanRuleTest.xml
> -  <TestCase name="testPartialPushDownWithVirtualColumn">
Can you keep this as it is?

2021-03-30 03:40 UTC, JingsongLi commented on flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/PushFilterIntoTableSourceScanRuleTest.xml
> -  <TestCase name="testPartialPushDownWithVirtualColumn">
Can you keep this as it is?

2021-03-30 03:40 UTC, JingsongLi commented on flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/utils/RexNodeExtractor.scala
> +        java.time.Period.ofMonths(v)
You should take a look to `YearMonthIntervalPeriodConverter`.

2021-03-31 02:10 UTC, TsReaper commented
Azure passed in https://dev.azure.com/tsreaper96/Flink/_build/results?buildId=137&view=results

2021-03-31 02:14 UTC, JingsongLi approved these changes
Looks good to me.

2021-03-31 02:15 UTC, merged