[FLINK-22065] [sql-client]Beautify the parse error exception
apache/flink pull request #15585
Opened 2021-04-13 06:33 UTC by chaozwn

…ommand in the sql client

## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluser with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

2021-04-17 16:32 UTC, fsk119 reviewed
Thanks for  your contribution. I left some comments.

2021-04-17 16:32 UTC, fsk119 commented on flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/exception/SqlParseException.java
> +    }
This is method is not used. Remove this.

2021-04-17 16:32 UTC, fsk119 commented on flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/local/LocalExecutor.java
> +            throw new SqlExecutionException("invalid statement: " + statement);
Use `SqlParseException`? I think the origin exception message is good enough.

2021-04-17 16:32 UTC, fsk119 commented on flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliClient.java
>              return false;
What about 
```
catch (SqlParseException e) {
       printSqlParseException(e);
}
catch (SqlExecutionException e) {
       printSqlExecutionException(e);
}
```
We can remove the `instance of`.

2021-04-17 16:32 UTC, fsk119 commented on flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/Executor.java
> +    Operation parseStatement(String sessionId, String statement) throws SqlClientException;
nit: I think we can make the exception more specific. Use `SqlClientParseException` is better?

2021-04-17 16:32 UTC, fsk119 commented on flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/Executor.java
> +    void start() throws SqlClientException;
nit: I think we can still use SqlExecutionException.

we can reduce the modifcation... and it only throws SqlExecutionException here?

2021-04-17 16:34 UTC, fsk119 commented
There are check style  errors. Use `mvn com.diffplug.spotless:spotless-maven-plugin:apply` to fix these.

2021-04-19 05:48 UTC, fsk119 reviewed
LGTM in general.

2021-04-19 05:48 UTC, fsk119 commented on flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliStrings.java
> +    public static final String MESSAGE_SQL_UNDIFINE_ERROR = "Unknown Error";
Remove this.

2021-04-20 09:12 UTC, wuchong requested changes
Please also add some validation tests in `misc.q`, e.g. 

```
invalid command;
!error

unknown command;
!error

unknown create command;
!error

invalid use mytable;
!error

create unknown command;
!error

select invalid command;
!error

use invalid command;
!error
```

2021-04-20 09:12 UTC, wuchong commented on flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/local/LocalExecutor.java
> +            throw new SqlParseException("Failed to parse statement: " + statement, e);
Personally, I think this pull request still not resolve the problem of the issue. You will still get the reason `org.apache.calcite.runtime.CalciteException: Non-query expression encountered in illegal context` when entering `invalid command;`. However, the reason message still can't help users figure out what happens. 

I think the purpose of this issue is reminding users this is an unsupported syntax. In order to improve the exception message, we can catch exception here, and wrap it into a new exception with message "Unsupported statement syntax is encountered" (or sth. similar) when the exception class is  `CalciteException` and the exception message is matched.

2025-03-29 06:25 UTC, closed without merging