[FLINK-22434] Store suspended execution graphs on termination to keep…
apache/flink pull request #15799
Opened 2021-04-29 06:11 UTC by fapaul

… them accessible

Before this change as soon as a cluster termination was initiated every
job was suspended and not accessible anymore until recovery. By storing
the execution graph they will appear as SUSPENDED they are now
accessible until the cluster is fully shutdown.

## Brief change log

  * Once the JobMasterServiceLeadershipRunner is shutdown the resultFuture describing will complete **without** an exception and return the SUSPENDED execution graph.

## Verifying this change

* Updated tests to ensure on shutdown the JobStatus is reflected correctly

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (**yes** / no / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

2021-04-29 06:31 UTC, fapaul commented
A ran the tests successfully on private azure https://dev.azure.com/georgeryan1322/Flink/_build/results?buildId=370&view=logs&j=9401bf33-03c4-5a24-83fe-e51d75db73ef&t=72901ab2-7cd0-57be-82b1-bca51de20fba

2021-05-03 10:00 UTC, tillrohrmann requested changes
Thanks for creating this PR @fapaul. I think it goes in a very good direction. 

I think the part where we changed the behavior a bit with this PR and, thus, need to adjust it is the client-side. Before, when a job was suspended, we did not report anything back to the client. Now, the client will see a `SUSPENDED` EG in the `JobResult` or an `UNKNOWN` `JobExecutionResult.` This is a bit of a problem for the case where the client waits for the job result and there is a leadership loss of the `Dispatcher`. In this case, the client should look up the new leader and wait for the result of the job. Currently, this is handled [here](https://github.com/apache/flink/blob/master/flink-clients/src/main/java/org/apache/flink/client/program/rest/RestClusterClient.java#L739) by not responding with a `JobResult` and simply closing the connection. With this change, we now need to handle the retry logic on a higher level where we see that the job has been suspended. If not, then we are changing behavior.

You should be able to observe the behavior when creating an HA Flink cluster on which you submit a bounded job (which take a bit of time), and then kill the current leader. If you have a standby leader, then it should take over and complete the job and the client should report the successful execution.

2021-05-14 16:02 UTC, fapaul commented on flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java
> +                dispatcher.requestExecutionGraphInfo(jobId, TIMEOUT).get();
Thanks for the hint. I added a new test submitting two jobs simulating the scenario you've described.

2021-05-14 16:03 UTC, fapaul commented
@tillrohrmann Thanks for your feedback I have now addressed all your comments, please have another look.

2021-05-18 13:38 UTC, tillrohrmann approved these changes
Thanks for updating this PR @fapaul. The changes look very good. Rebasing and merging this PR once AZP gives green light.

2021-05-19 08:55 UTC, fapaul commented
@flinkbot run azure

2021-05-21 12:23 UTC, closed without merging