[FLINK-22253][docs] Update back pressure monitoring docs with new WebUI changes
apache/flink pull request #15811
Opened 2021-04-29 15:06 UTC by pnowojski

This PR updates the docs to reflect changes implemented in https://issues.apache.org/jira/browse/FLINK-14712

2021-05-03 12:36 UTC, alpinegizmo requested changes
The explanations are clear, I simply created some suggestions for improving the English. 

One question though: does the timeout work as stated? I remember we discussed with Roman doing this a bit differently.

2021-05-03 12:36 UTC, alpinegizmo commented on docs/content/docs/ops/monitoring/back_pressure.md
> +that subtask has been back pressured (or idle or busy) in that last couple of seconds.
```suggestion
These metrics are being updated every couple of seconds, and the reported value represents the average time
that subtask was back pressured (or idle or busy) during the last couple of seconds.
```

2021-05-03 12:36 UTC, alpinegizmo commented on docs/content/docs/ops/monitoring/back_pressure.md
> +of `busyTimeMsPerSecond` around `500ms`.
```suggestion
Keep this in mind if your job has a varying load. For example, a subtask with a constant load of 50% and another subtask that is alternating every second between fully loaded and idling will both have the same value
of `busyTimeMsPerSecond`: around `500ms`. 
```

2021-05-03 12:36 UTC, alpinegizmo commented on docs/content/docs/ops/monitoring/back_pressure.md
> +If there is no available buffer (at least one) for output, then it indicates that there is back pressure for the task.
```suggestion
If a task has no available output buffers, then that task is considered back pressured.
```

2021-05-03 12:36 UTC, alpinegizmo commented on docs/content/docs/ops/monitoring/back_pressure.md
> +Idleness is judged on the other hand on the availability of the task's input.
```suggestion
Idleness, on the other hand, is determined by whether or not there is input available.
```

2021-05-03 12:36 UTC, alpinegizmo commented on docs/content/docs/ops/monitoring/back_pressure.md
> +also color codded to make the investigation easier.
```suggestion
The WebUI aggregates the maximum value of the back pressure and busy metrics from all of the subtasks and presents those aggregated values inside the JobGraph. Besides displaying the raw values, tasks are
also color-coded to make the investigation easier.
```

2021-05-03 12:36 UTC, alpinegizmo commented on docs/content/docs/ops/monitoring/back_pressure.md
> +Idling tasks are blue. Fully back pressured tasks are black, while 100% busy tasks are colored red.
```suggestion
Idling tasks are blue, fully back pressured tasks are black, and fully busy tasks are colored red.
```

2021-05-03 12:36 UTC, alpinegizmo commented on docs/content/docs/ops/monitoring/back_pressure.md
> +In *Back Pressure* tab next to the job overview you can find more detailed metrics.
```suggestion
In the *Back Pressure* tab next to the job overview you can find more detailed metrics.
```

2021-05-03 12:36 UTC, alpinegizmo commented on docs/content/docs/ops/monitoring/back_pressure.md
> +Additionally you can find the percentage each subtask is back pressured, idle or busy.
```suggestion
Additionally, you can find the percentage of time each subtask is back pressured, idle, or busy.
```

2021-05-03 12:36 UTC, alpinegizmo commented on docs/content/docs/ops/monitoring/back_pressure.md
> +other hand means that the subtasks are back pressured. Where status is defined in the following way:
```suggestion
For subtasks whose status is **OK**, there is no indication of back pressure. **HIGH**, on the
other hand, means that a subtask is back pressured. Status is defined in the following way:
```

2021-05-03 12:36 UTC, alpinegizmo commented on docs/content/docs/ops/state/checkpoints.md
> +Note that unaligned checkpoints is a new feature that currently has the
```suggestion
Note that unaligned checkpointing is a new feature that currently has the
```

2021-05-03 12:36 UTC, alpinegizmo commented on docs/content/docs/ops/state/checkpoints.md
> +some task exceeds this timeout, this checkpoint will time out to unaligned checkpoint.
```suggestion
`CheckpointConfig.setAlignmentTimeout(Duration)` or `execution.checkpointing.alignment-timeout` in
the configuration file. When activated, each checkpoint will still begin as an aligned checkpoint, but if the alignment for some task exceeds this timeout, then the checkpoint will proceed as an unaligned checkpoint.
```

2021-05-04 07:18 UTC, pnowojski commented
Thanks for the suggestions @alpinegizmo! Yes, uc timeout is counted against subtask's alignment time.

2021-05-04 08:27 UTC, alpinegizmo commented on docs/content/docs/ops/state/checkpoints.md
> +but if the alignment for some subtask exceeds this timeout, then the checkpoint will proceed as an
```suggestion
but if the alignment time for some subtask exceeds this timeout, then the checkpoint will proceed as an
```

2021-05-04 08:29 UTC, alpinegizmo approved these changes
I'll approve this now, but I've added one last (trivial) suggestion.

2021-05-04 10:17 UTC, pnowojski commented
Thanks a lot! I've included that last one suggestion and I'm going to merge it soon.

2021-05-04 10:17 UTC, merged