[FLINK-22515][docs] Add documentation for GSR-Flink Integration
apache/flink pull request #15830
Opened 2021-05-04 17:41 UTC by LinyuYao1021

## What is the purpose of the change

This pull request adds documentation for Glue Schema Registry(GSR)-Flink integration and updates with the latest GSR version.

## Brief change log

  - Documentation of Flink-Kafka and Flink-Kinesis is updated to introduce GSR integration
  - GSR version is updated to 1.0.2
  - Using `avro` plugin to converter `.asvc` file to Java POJO class.

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (docs)

2021-05-05 00:23 UTC, LinyuYao1021 commented
@flinkbot run azure

2021-05-06 17:16 UTC, LinyuYao1021 commented
@flinkbot run azure

2021-05-06 22:22 UTC, LinyuYao1021 commented
@flinkbot run travis

2021-05-12 17:08 UTC, LinyuYao1021 commented
@flinkbot run travis

2021-05-12 17:39 UTC, LinyuYao1021 commented
@flinkbot run azure

2021-05-13 14:30 UTC, dannycranmer requested changes

2021-05-13 14:30 UTC, dannycranmer commented on docs/content.zh/docs/connectors/datastream/kinesis.md
> +2. `JsonDeserializationSchema` (and `JSONKeyValueDeserializationSchema`) which turns the serialized JSON
I cannot see a `JsonDeserializationSchema` in the codebase, and `JSONKeyValueDeserializationSchema implements KafkaDeserializationSchema`, not sure this is right for Kinesis.

2021-05-13 14:30 UTC, dannycranmer commented on docs/content.zh/docs/connectors/datastream/kinesis.md
> +    - You can use AWS's implementation of a schema registry [AWS Glue Schema Registry](https://docs.aws.amazon.com/glue/latest/dg/schema-registry.html)
nit: reword `You can use AWS's implementation of a schema registry [AWS Glue Schema Registry]` to `You can use [AWS Glue Schema Registry]`

2021-05-13 14:30 UTC, dannycranmer commented on docs/content/docs/connectors/datastream/kafka.md
> +    - You can also use AWS's implementation of a schema registry [AWS Glue Schema Registry](https://docs.aws.amazon.com/glue/latest/dg/schema-registry.html)
nit: same as above, reword to `You can use [AWS Glue Schema Registry]`

2021-05-13 14:30 UTC, dannycranmer commented on flink-formats/flink-avro-glue-schema-registry/pom.xml
> +		<glue.schema.registry.version>1.0.2</glue.schema.registry.version>
Really this change (and below) should be in a dedicated PR. Can you please raise a separate PR with a dedicated Jira issue and we should be able to merge this right away.

2021-05-18 09:05 UTC, merged

2021-05-18 09:06 UTC, dannycranmer reviewed
LGTM