[FLINK-22782][docs] Remove legacy planner from Chinese docs
apache/flink pull request #16018
Opened 2021-05-28 08:46 UTC by SteNicholas

## What is the purpose of the change

*(This is another step in getting rid of the legacy planner. The Chinese docs are still not perfect but better than before with this PR. The Chinese docs should be done in a followup issue, I only dropped the legacy planner page there.*

## Brief change log

  - Remove reference of `useBlink/LegacyPlanner`
  - Remove `DataSet`
  - Remove legacy planner mentioning

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

2021-05-28 14:00 UTC, twalthr requested changes
Thanks for the PR @SteNicholas. Could you perform another search in the Chinese dcos for occurences of `DataSet`, `ExecutionEnvironment`, `BatchTableEnvironment`. It seems there are still a lot of mentionings. Such as in `zh/docs/dev/table/common/ ` with `fsSettings` or `useAnyPlanner`. The English docs were already updated.

2021-05-28 14:00 UTC, twalthr commented on docs/content.zh/docs/dev/table/common.md
>  val bsEnv = StreamExecutionEnvironment.getExecutionEnvironment
remove `bs` and `b_s_settings` etc. here and below? I think the "b" stood for Blink in the past?

2021-05-28 14:00 UTC, twalthr commented on docs/content.zh/docs/dev/table/common.md
>  # BLINK BATCH QUERY
update?

2021-05-28 14:00 UTC, twalthr commented on docs/content.zh/docs/dev/table/tableApi.md
>  t_env = BatchTableEnvironment.create(
update usages of `BatchTableEnvironment`?

2021-05-31 12:26 UTC, wuchong reviewed
1. should we remove all the "blink" keyword in the docs? cc @twalthr 
2. there are still many "dataset" used in `docs/content.zh/docs/dev/table/functions/udfs.md`.

2021-05-31 12:33 UTC, twalthr commented
Yes, the removal of "blink" keyword will be another subtask. But I think the PR is good for now. Let's do all of this incrementally. But we could remove `dataset` in `udfs` already. What do you think @SteNicholas?

2021-05-31 12:42 UTC, SteNicholas commented
@wuchong @twalthr , thanks for detailed review. I have updated the `docs/content.zh/docs/dev/table/functions/udfs.md` for `dataset`. Please help to review again.

2021-05-31 15:04 UTC, twalthr approved these changes
Thanks @SteNicholas. LGTM I will merge this now. We will do another pass over the docs at a later stage.

2021-05-31 15:11 UTC, closed without merging