[FLINK-21926][doc] Add docs for fine-grained resource management
apache/flink pull request #16561
Opened 2021-07-22 03:28 UTC by KarmaGYZ

## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluser with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

2021-08-02 20:11 UTC, sjwiesman requested changes
I've made a first pass

2021-08-02 20:11 UTC, sjwiesman commented on docs/content/docs/deployment/finegrained_resource.md
> +profiles, namely **coarse-grained resource management**. The TaskManager contained a fixed number of identical slots to fulfill those requirements.
```suggestion
```

I moved this down

2021-08-02 20:11 UTC, sjwiesman commented on docs/content/docs/deployment/finegrained_resource.md
> +
```suggestion
{{< hint info >}}
Previously in Flink, the resource requirement only contained the number of the required slots, without fine-grained resource
profiles, namely **coarse-grained resource management**. The TaskManager contained a fixed number of identical slots to fulfill those requirements.
{{< /hint >}}

2021-08-02 20:11 UTC, sjwiesman commented on docs/content/docs/deployment/finegrained_resource.md
> +</div>
```suggestion
{{< hint warning >}}
**Note:** Each slot sharing group can only attach to one specified resource, any conflict will fail the compiling of your job.
{{< /hint >}}
```

2021-08-02 20:11 UTC, sjwiesman commented on docs/content/docs/deployment/finegrained_resource.md
> +For the resource requirement without a specified resource profile, Flink will automatically decide the resource profile of it.
```suggestion
For the resource requirement without a specified resource profile, Flink will automatically decide a resource profile.
```

2021-08-02 20:11 UTC, sjwiesman commented on docs/content/docs/deployment/finegrained_resource.md
> +management. In the future, there might be various strategies that can be selected for different scenarios.
```suggestion
management. In the future, there might be various strategies that users can select for different scenarios.
```

2021-08-02 20:11 UTC, sjwiesman commented on docs/content/docs/deployment/finegrained_resource.md
> +It provides means for users to further improve Flink’s resource efficiency with knowledge of their specific scenarios.
```suggestion
Apache Flink works hard to auto-derive sensible default resource requirements for all applications out of the box. 
For users who wish to fine-tune their resource consumption, based on knowledge of their specific scenarios, Flink offers **fine-grained resource management**.
```

I want to make it clear to new users that you don't have to do this.

2021-08-03 02:06 UTC, KarmaGYZ commented on docs/content/docs/deployment/finegrained_resource.md
> +The slot is the basic unit of both resource scheduling and resource requirement in Flink runtime.
Maybe `Flink's`?

2021-08-03 02:38 UTC, KarmaGYZ commented
Thanks for the valuable comments! @sjwiesman PR updated.

2021-08-12 02:06 UTC, KarmaGYZ commented
@sjwiesman Hi, would you like to give it another pass?

2021-08-17 16:11 UTC, closed without merging

2021-08-17 16:11 UTC, sjwiesman approved these changes