[FLINK-23110][runtime-web] Bump angular's and ng-zorro's version to 8
apache/flink pull request #16603
Opened 2021-07-27 08:20 UTC by yangjunhan

## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*
Step-by-step modernize **flink-runtime-web**, i.e. Flink UI. This PR bumps it to v8

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): yes
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

2021-07-27 08:35 UTC, Airblader approved these changes
Changes look good to me, thanks!

2021-07-27 20:09 UTC, Airblader commented
BTW, I'm also totally fine with doing the upgrades all the way to Angular 12 on the same PR. Just separating by commit to make it easier to review would be appreciated, but we don't need to wait on merges every single time that way.

2021-07-28 01:45 UTC, yangjunhan commented
> BTW, I'm also totally fine with doing the upgrades all the way to Angular 12 on the same PR. Just separating by commit to make it easier to review would be appreciated, but we don't need to wait on merges every single time that way.

Sure, I will continue to push commits to this PR.

2021-07-30 07:07 UTC, yangjunhan commented
@Airblader I believe this PR is ready for reviews now. BTW, since there is little modifications while bumping from v11 to v12, I have merged those two updates in one commit.

2021-07-30 07:55 UTC, Airblader requested changes
Thanks for working on this! Overall it looks great. I left a couple minor comments. There is one main thing, we need to do still, however; we need to update the `pom.xml` to use a compatible node version (12.14.x/14.15.x or later minor version) during a Maven build.

2021-07-30 07:55 UTC, Airblader commented on flink-runtime-web/web-dashboard/package.json
> +    "rxjs": "^6.5.3",
This should be >= 6.6 (see https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3)

2021-07-30 07:55 UTC, Airblader commented on flink-runtime-web/web-dashboard/package.json
>      "dagre": "^0.8.4",
We should add `dagre` to `allowedCommonJsDependencies` in `angular.json` to avoid a warning.

2021-07-30 09:18 UTC, Airblader approved these changes
Thanks! Let's wait for the CI, but LGTM now.

2021-08-02 07:12 UTC, yangjunhan commented
@Airblader I believe the CI has finished. Once this PR is merged, I can start working on the eslint migration.

2021-08-02 07:31 UTC, Airblader commented
Sounds great. Do you have someone who can merge this PR for you? Otherwise I can find someone who can take care of it.

2021-08-02 07:56 UTC, yangjunhan commented
> Sounds great. Do you have someone who can merge this PR for you? Otherwise I can find someone who can take care of it.

Please do so. I have no one to do it for me currently.

2021-08-02 07:58 UTC, Airblader commented
That's fine. We'll take care of it.

2021-08-05 10:38 UTC, twalthr reviewed
Thanks for improving the web UI @yangjunhan. I can help merging this but have to rely on  @Airblader judgement for a review. One thing that we should check though is whether we need to update NOTICE files. I see `flink-runtime-web/src/main/resources/META-INF/NOTICE` maybe also in `flink-dist`?

2021-08-09 02:03 UTC, yangjunhan commented
Hi, @Airblader @twalthr. How is the reviewing going? Could you kindly confirm whether I need to update the `NOTICE` file as well?

2021-08-09 05:27 UTC, Airblader commented
@yangjunhan Yes, the NOTICE file @twalthr mentioned needs to be updated as well.

2021-08-09 09:02 UTC, yangjunhan commented
> @yangjunhan Yes, the NOTICE file @twalthr mentioned needs to be updated as well.

Okay, I will handle it @Airblader . However, I am not very sure the tool and exact steps to auto-update the NOTICE file, and I do not think that I should manually update the file 😂.

BTW, would it be possible to invite me to the Veverica Slack workspace so that we can communicate there in a more convenient way? I am currently a team member of VVP Front-end in Hangzhou, China.

2021-08-09 09:41 UTC, Airblader commented
I actually think the NOTICE files are maintained manually (unfortunately). There is a license checker to verify some basic things, but I am not sure it even runs for the npm dependencies.

I'll try to ask someone about Slack and will get back to you.

2021-08-09 13:35 UTC, Airblader commented
@yangjunhan Can you give us your email address with which to invite you to Slack?

2021-08-10 03:41 UTC, yangjunhan commented
> @yangjunhan Can you give us your email address with which to invite you to Slack?

My email address: yangjunhan1234@gmail.com. Thanks.

2021-08-11 07:19 UTC, Airblader commented
supersedes #14960

2021-08-16 09:45 UTC, twalthr approved these changes
LGTM

2021-08-16 15:08 UTC, closed without merging