[FLINK-23840][runtime] Improve confusing log / exception message when…
apache/flink pull request #16879
Opened 2021-08-18 13:08 UTC by dmvk

https://issues.apache.org/jira/browse/FLINK-23840

2021-08-18 14:56 UTC, alpinegizmo commented
I'm not familiar with how the code here is organized, so no comment on that. But in terms of the user experience, looks great.

2021-08-18 14:58 UTC, alpinegizmo commented
If it's easy to do so, it would be nice to backport this to 1.13.

2021-08-19 08:12 UTC, zentol requested changes

2021-08-19 11:58 UTC, dmvk commented
@zentol Thanks for the review! I've tried to enhance log messages so user can get a better intuition on why a particular options has been ignored.

@alpinegizmo This should be fairly easy to backport as there were no changes to CheckpointStorageLoader since 1.13 release. I've added 1.13.3 to the list of fix versions.

2021-08-19 16:44 UTC, zentol requested changes

2021-08-19 16:44 UTC, zentol commented on flink-runtime/src/main/java/org/apache/flink/runtime/state/CheckpointStorageLoader.java
> +            "Legacy state backends can also be used as checkpoint storage and are configured to take precedence for backward-compatibility reasons.";
```suggestion
            "Legacy state backends can also be used as checkpoint storage and take precedence for backward-compatibility reasons.";
```
Saying that they are "configured to do X" may imply that this behavior is configurable.

2021-08-23 12:15 UTC, dmvk commented
@zentol Fixed, PTAL ;)

2021-08-24 08:05 UTC, merged