[FLINK-24210][serializer] Return the correct serialized length for wi…
apache/flink pull request #17720
Opened 2021-11-08 13:14 UTC by ljz2051

…ndow-related serializer

## What is the purpose of the change

This pull request return the correct serialized length for window-related serializer, rather than return 0.

## Brief change log
 - Return the correct serialized length  for TimeWindow, GlobalWindow and CountWindow
 - Add unit test for TimeWindow.Serializer

## Verifying this change

This change added tests and can be verified as follows:
 - Added unit test that validates that TimeWindow.Serializer can follow the standard serializer behavior

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: yes
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented?

2021-12-09 11:17 UTC, Myasuka requested changes
The CI is broken, please take a look at the failures.

2022-01-15 06:11 UTC, Myasuka commented
@ljz2051 Please take a look at the CI.

@flinkbot run azure

2022-01-18 12:56 UTC, ljz2051 commented
@flinkbot run azure

2022-01-19 02:59 UTC, ljz2051 commented
@flinkbot run azure

2022-01-19 04:39 UTC, ljz2051 commented
@flinkbot run azure

2022-01-19 11:50 UTC, Myasuka approved these changes
LGTM

2022-01-20 02:51 UTC, closed without merging