[FLINK-24830][examples] Update DataStream WordCount example
apache/flink pull request #17760
Opened 2021-11-10 21:19 UTC by sjwiesman

## What is the purpose of the change

Updates the DataStream word count example to better reflect the current state of the art in Apache Flink; in particular the batch stream unification. 

Because of how important this example is, it has more comments than normal to walk users through the application and to show off best practices. 

## Verifying this change

This change is already covered by existing tests

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

2021-11-10 21:22 UTC, sjwiesman commented
@alibahadirzeybek would you want to take a look at this? The actual code changes are trivial, but I'd be interested in your opinion on the code comments.

2021-11-11 11:58 UTC, alpreu commented
@flinkbot run azure

2021-11-11 12:10 UTC, alpreu requested changes
Thank you for your contribution. I checked the code and it looks good to me, I only found some small issues in the comments

2021-11-11 12:10 UTC, alpreu commented on flink-examples/flink-examples-streaming/src/main/scala/org/apache/flink/streaming/scala/examples/wordcount/WordCount.scala
> +    // By setting the runtime mode to AUTOMATIC, Flink will choose the BATCH  if all sources
```suggestion
    // By setting the runtime mode to AUTOMATIC, Flink will choose BATCH if all sources
```

2021-11-11 12:10 UTC, alpreu commented on flink-examples/flink-examples-streaming/src/main/scala/org/apache/flink/streaming/scala/examples/wordcount/WordCount.scala
> +    // are bounded and otherwise STREAMING.
Duplicate comment

2021-11-11 12:10 UTC, alpreu commented on flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/wordcount/WordCount.java
> +        // By setting the runtime mode to AUTOMATIC, Flink will choose the BATCH  if all sources
```suggestion
        // By setting the runtime mode to AUTOMATIC, Flink will choose BATCH if all sources
```

2021-11-11 15:48 UTC, sjwiesman commented on flink-examples/flink-examples-streaming/src/main/scala/org/apache/flink/streaming/scala/examples/wordcount/WordCount.scala
> +    // are bounded and otherwise STREAMING.
whoops 😅

2021-11-11 15:48 UTC, sjwiesman commented
@alpreu thanks for the quick review! I'll apply your fixes while merging :)

2021-11-11 15:55 UTC, sjwiesman commented
It looks like there are some relevant test failures because some tests actually use the examples as test dependencies. I'll look into it.

2021-11-11 18:03 UTC, sjwiesman commented
Nevermind, it's because my changes to the test base weren't filtering out hidden files. I'll merge if green.

2021-11-12 15:38 UTC, sjwiesman commented
@gaborgsomogyi or @KarmaGYZ could either of you please take a look at the failing Yarn tests and help me debug them? I have made a simple change to the DataStream WordCount example, which is used by the Yarn tests as the submitted application. 

After speaking offline with @AHeise and @tillrohrmann we believe this may be due to the added dependency on `flink-connector-files` which is causing some sort of version clash with Yarn. Any insights on how to resolve this would be greatly appreciated.

2021-11-12 15:59 UTC, alibahadirzeybek commented on flink-examples/flink-examples-streaming/src/main/scala/org/apache/flink/streaming/scala/examples/wordcount/WordCount.scala
> +      // will output each words as a (2-tuple) containing (word, 1)
```suggestion
      // will output each word as a (2-tuple) containing (word, 1)
```

2021-11-12 17:43 UTC, alibahadirzeybek reviewed
Suggested a couple of changes to wordings in some of the comments, otherwise LGTM.

2021-11-12 17:43 UTC, alibahadirzeybek commented on flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/wordcount/util/CLI.java
> +            System.out.println("Executing example with default input data set.");
```suggestion
            System.out.println("Executing example with default input data.");
```

2021-11-12 17:43 UTC, alibahadirzeybek commented on flink-examples/flink-examples-streaming/src/main/scala/org/apache/flink/streaming/scala/examples/wordcount/WordCount.scala
> +        // If the input data set is bounded, sum will output a final count for
```suggestion
        // If the input data stream is bounded, sum will output a final count for
```

2021-11-12 17:43 UTC, alibahadirzeybek commented on flink-examples/flink-examples-streaming/src/main/scala/org/apache/flink/streaming/scala/examples/wordcount/WordCount.scala
> +   * Implements the string tokenizer that splits sentences into words as a user-defined
```suggestion
   * Implements the string tokenizer that splits a sentence into words as a user-defined
```

Same for the Java implementation

2021-11-12 17:43 UTC, alibahadirzeybek commented on flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/wordcount/WordCount.java
> +                        // If the input data set is bounded, sum will output a final count for
```suggestion
                        // If the input data stream is bounded, sum will output a final count for
```

2021-11-12 19:15 UTC, sjwiesman commented on flink-examples/flink-examples-streaming/pom.xml
> -								</artifactItem>
Turns out that copying this class overwrites the `wordcount/util` folder and deletes CLI.class

2021-11-12 19:18 UTC, sjwiesman commented on flink-examples/flink-examples-streaming/pom.xml
> -
This job doesn't exist anymore

2021-11-15 15:29 UTC, MartijnVisser commented
@sjwiesman Should we also update the example in the README?

2021-11-15 15:47 UTC, sjwiesman commented
@MartijnVisser I have an umbrella ticket, FLINK-24635, for cleaning up the examples. You can open that as another subtask though I think the entire README could use a rewrite. It still shows off DataSet and does not have a table API example.

2021-11-15 21:22 UTC, closed without merging