[FLINK-25085][runtime] Add a scheduled thread pool in Endpoint and close it when the endpoint is stopped
apache/flink pull request #18007
Opened 2021-12-03 11:41 UTC by zjureel

## What is the purpose of the change

This PR adds a scheduled thread pool to hold the periodic tasks and send them to akka with gateway when they should be executed. These periodic tasks such as resource timeout checker, heartbeat checker and some other tasks are scheduled by akka thread pool now,  and they are alive even when the job or tasks reach termination, it will cause FullGC. 

## Brief change log
 - Add a scheduled thread pool to hold the periodic tasks and send them to akka with gateway when they should be executed
 - Create the scheduled thread pool in Endpoint and close it when Endpoint is closed.

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - Added test ScheduledMainThreadExecutorTest that validates the ScheduledMainThreadExecutor
  - Endpoint related changes are covered by existing test RpcEndpointTest

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no) no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no) no
  - The serializers: (yes / no / don't know) no
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know) no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know) no
  - The S3 file system connector: (yes / no / don't know) no

## Documentation

  - Does this pull request introduce a new feature? (yes / no) no
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) not documented

2021-12-03 11:51 UTC, zjureel commented
@tillrohrmann @xintongsong Please have look at this PR for [FLINK-25085](https://issues.apache.org/jira/browse/FLINK-25085) when you are free, thanks

2021-12-06 02:07 UTC, xintongsong commented
Thanks for preparing this PR, @zjureel. @KarmaGYZ and I will both take a look.

2021-12-06 07:49 UTC, KarmaGYZ requested changes
Thanks for the PR, @zjureel . I left some comments after the first pass.
My main concern is the relationship between `ScheduledMainThreadExecutor` and `MainThreadExecutor`. From my understanding, the `MainThreadExecutor` is designed to be used for scheduling tasks and periodic tasks. The functionality of these two classes is a bit overlapped.
Is there any concern about not replacing the existing `MainThreadExecutor#schedule`? If not, I would recommend not introducing another `ScheduledMainThreadExecutor`. WDYT?

2021-12-06 07:49 UTC, KarmaGYZ commented on flink-runtime/src/test/java/org/apache/flink/runtime/rpc/RpcEndpointTest.java
> +        final String foo = "foobar";
It would be better to name it `endpointId`.

2021-12-07 06:06 UTC, zjureel commented
@KarmaGYZ Thank you for your comments. I think it's a good question about `ScheduledMainThreadExecutor` and `MainThreadExecutor`. I create `ScheduledMainThreadExecutor` here for two reasons: 

1) The `ScheduledMainThreadExecutor` instance is not only created and used in `RpcEndpoint`, but also created in `HeartbeatManager.monitorTarget` for each job in `TaskExecutor` to schedule the job's heartbeat. When a job terminates, its `ScheduledMainThreadExecutor` should be closed too.

2) In my conception,  `MainThreadExecutor#schedule` will be replaced with `ScheduledMainThreadExecutor` and it will throw `Exception` when all its calls are replaced. The `MainThreadExecutor` will be used as main thread to execute `Runnable` at once.

WDYT of that? THX

2021-12-07 07:27 UTC, KarmaGYZ commented
Thanks for the reply, @zjureel .
It seems we all agree that, in the end, the `MainThreadExecutor#schedule` will be replaced. Also, I don't think one should use `ScheduledMainThreadExecutor#execute` to execute tasks in the main thread. So, I would prefer to merge these two classes. As the `MainThreadExecutor` is indeed a `ScheduledExecutor`, one would expect to schedule tasks in the main thread directly by `MainThreadExecutor#schedule`.

Regarding the `HeartbeatManager.monitorTarget`, I'm not quite sure about what the problem is. Maybe we can construct a new `ScheduledMainThreadExecutor` from the `MainThreadExecutor`. That should be out of the scope of this PR.

2021-12-14 08:02 UTC, zjureel commented
@KarmaGYZ Thank you for your advice. Through the last communication, I think integrate `ScheduledMainThreadExecutor` and `MainThreadExecutor` is cool. I have made this update in code, checked the methods which call the `MainThreadExecutor.schedule` and add some test cases in `RpcEndpointTest`. Can you have a look when you are free and hope to hear from you. THX

2021-12-15 02:22 UTC, KarmaGYZ commented
@zjureel All the `RpcEndpointTest.testScheduleXXX` hangs because the `TestMainThreadExecutable#runAsync` do nothing. It only call the `scheduleRunAsyncConsumer` in the `scheduleRunAsync`. Please take a look.

Also, please squash your commits which are used to address the review comments.

2021-12-15 12:09 UTC, KarmaGYZ requested changes

2021-12-15 12:09 UTC, KarmaGYZ commented on flink-runtime/src/test/java/org/apache/flink/runtime/rpc/RpcEndpointTest.java
> +                        expectedDelay.toMillis());
```suggestion
        final CompletableFuture<Void> actualDelayMsFuture = new CompletableFuture<>();
        final String endpointId = "foobar";

        final Duration expectedDelay = Duration.ofSeconds(1);
        final MainThreadExecutable mainThreadExecutable =
                new TestMainThreadExecutable(
                        runnable -> actualDelayMsFuture.complete(null));
```

2021-12-15 12:10 UTC, KarmaGYZ commented
@flinkbot run azure

2021-12-20 05:41 UTC, zjureel commented on flink-rpc/flink-rpc-core/src/main/java/org/apache/flink/runtime/rpc/FencedRpcEndpoint.java
> +                getRpcService().fenceRpcServer(rpcServer, fencingToken);
@KarmaGYZ It's automatically separated by `mvn spotless:apply`, i think it's better keep it like this

2021-12-20 06:44 UTC, KarmaGYZ approved these changes

2021-12-21 01:56 UTC, KarmaGYZ commented
@flinkbot run azure

2021-12-22 02:01 UTC, KarmaGYZ commented
@flinkbot run azure

2021-12-22 08:26 UTC, closed without merging