[FLINK-25052] Port Row to row casting to cast rule
apache/flink pull request #18027
Opened 2021-12-06 12:57 UTC by slinkydeveloper

## What is the purpose of the change

Port row to row casting logic to `CastRule` stack.

## Brief change log

* Fix `AbstractCodeGeneratorCastRule` to properly write the serializers
* Port row to row casting logic to `CastRule` stack.

## Verifying this change

This change adds some test cases to `CastRule` and `CastFunctionsITCase`

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

2021-12-07 09:45 UTC, matriv commented on flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CastFunctionITCase.java
> -                // Cast to structuredTypes
Please include that in the extracted method

2021-12-07 09:45 UTC, matriv commented on flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CastFunctionITCase.java
> -                // Cast to structuredTypes
ah, it's on top, sorry, ignore

2021-12-07 10:05 UTC, matriv reviewed
LGTM, Thx @slinkydeveloper !!

2021-12-07 10:06 UTC, slinkydeveloper commented on flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/casting/CastRulesTest.java
> +    public static class MyStructuredType {
Not sure what to write there :)

2021-12-07 10:07 UTC, matriv commented on flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/casting/CastRulesTest.java
> +    public static class MyStructuredType {
Just wondering if spotless requires it, otherwise no comment is needed, of course.

2021-12-07 10:10 UTC, slinkydeveloper commented on flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/casting/CastRulesTest.java
> +    public static class MyStructuredType {
I think checkstyle doesn't require comments for public subclasses, but let's see what CI thinks :)

2021-12-07 14:56 UTC, twalthr requested changes
Thanks for the PR @slinkydeveloper. I added some comments.

2021-12-07 14:56 UTC, twalthr commented on flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/casting/CastRulesTest.java
> +        public long getA() {
if you want to keep your code concise you can also just have public mutable members. should be ok for testing code.

2021-12-07 14:56 UTC, twalthr commented on flink-table/flink-table-common/src/test/java/org/apache/flink/table/test/TableAssertions.java
> +    // --- Internal data types
nit: `Internal data structures`

2021-12-07 16:27 UTC, slinkydeveloper commented on flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CastFunctionITCase.java
> +                CastTestSpecBuilder.testCastTo(ARRAY(INT()))
Perhaps collection types?

2021-12-08 13:16 UTC, twalthr approved these changes
LGTM

2021-12-08 14:26 UTC, closed without merging