update doc variable name reference error
apache/flink pull request #18172
Opened 2021-12-22 06:32 UTC by h1365930778

## What is the purpose of the change

This PR fixes the problem with the Python DataStream API documentation page variable "t_env" being written as "table". On this page: https://nightlies.apache.org/flink/flink-docs-release-1.13/docs/dev/python/datastream/intro_to_datastream_api/

![1640152803226](https://user-images.githubusercontent.com/55094781/147046455-8d423226-dea2-4ba9-afcf-b0d269740b51.jpg)

## Verifying this change

I built and verified at the rendered docs site locally

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? applicable

2021-12-22 09:40 UTC, h1365930778 commented
Hi @wuchong  I opened this PR ,please take a look when you have time, thanks a lot.

2021-12-22 18:45 UTC, MartijnVisser requested changes
Please update your commit message to follow the Code Style & Quality Guidelines, which can be found at https://flink.apache.org/contributing/code-style-and-quality-preamble.html.

2021-12-23 03:34 UTC, sky-walking reviewed
[hotfix][doc] Change tableEnvironment attribute reference error

2021-12-23 04:45 UTC, sky-walking commented
> Please update your commit message to follow the Code Style & Quality Guidelines, which can be found at https://flink.apache.org/contributing/code-style-and-quality-preamble.html.

Could you be more specific, please? I don't know what the problem is, thank you very much.

2021-12-23 10:13 UTC, MartijnVisser commented
> > Please update your commit message to follow the Code Style & Quality Guidelines, which can be found at https://flink.apache.org/contributing/code-style-and-quality-preamble.html.
> 
> Could you be more specific, please? I don't know what the problem is, thank you very much.

You currently have three commits with 3 different messages:

`variable name reference error`
`[hotfix][doc] Change tableEnvironment attribute reference error`
`Merge branch 'hot-fix-update-doc' of github.com:h1365930778/flink into hot-fix-update-doc`

This can/should be one commit message, as explained on https://flink.apache.org/contributing/code-style-and-quality-pull-requests.html#commit-naming-conventions. Also explained there is that in this case, the commit message should probably look something like:

`[hotfix][docs] Fix incorrect Python tableEnvironment attribute reference`

2021-12-23 12:12 UTC, sky-walking commented
> > > Please update your commit message to follow the Code Style & Quality Guidelines, which can be found at https://flink.apache.org/contributing/code-style-and-quality-preamble.html.
> > 
> > 
> > Could you be more specific, please? I don't know what the problem is, thank you very much.
> 
> You currently have three commits with 3 different messages:
> 
> `variable name reference error` `[hotfix][doc] Change tableEnvironment attribute reference error` `Merge branch 'hot-fix-update-doc' of github.com:h1365930778/flink into hot-fix-update-doc`
> 
> This can/should be one commit message, as explained on https://flink.apache.org/contributing/code-style-and-quality-pull-requests.html#commit-naming-conventions. Also explained there is that in this case, the commit message should probably look something like:
> 
> `[hotfix][docs] Fix incorrect Python tableEnvironment attribute reference`

2021-12-23 12:12 UTC, sky-walking commented
> > > Please update your commit message to follow the Code Style & Quality Guidelines, which can be found at https://flink.apache.org/contributing/code-style-and-quality-preamble.html.
> > 
> > 
> > Could you be more specific, please? I don't know what the problem is, thank you very much.
> 
> You currently have three commits with 3 different messages:
> 
> `variable name reference error` `[hotfix][doc] Change tableEnvironment attribute reference error` `Merge branch 'hot-fix-update-doc' of github.com:h1365930778/flink into hot-fix-update-doc`
> 
> This can/should be one commit message, as explained on https://flink.apache.org/contributing/code-style-and-quality-pull-requests.html#commit-naming-conventions. Also explained there is that in this case, the commit message should probably look something like:
> 
> `[hotfix][docs] Fix incorrect Python tableEnvironment attribute reference`

Thank you very much for your guidance. I have modified it according to your format.

2021-12-23 12:13 UTC, sky-walking commented
Thank you very much for your guidance. I have modified it according to your format

2021-12-24 04:32 UTC, MartijnVisser commented
@flinkbot run azure

2021-12-24 07:04 UTC, MartijnVisser approved these changes
LGTM

@fapaul Can you please merge?

2022-01-05 02:32 UTC, sky-walking commented
@fapaul Could you please help me review my commit? Thank you very much

2022-01-06 08:08 UTC, fapaul approved these changes
Thanks for the fix. Does this also affect release-1.14?

2022-01-06 08:08 UTC, merged