[hotfix] Fix typo hasAggreateExprs -> hasAggregateExprs in HiveParser…
apache/flink pull request #18227
Opened 2021-12-29 07:37 UTC by sky-walking

[hotfix] Fix typo hasAggreateExprs -> hasAggregateExprs in HiveParserQBSubQuery.java

2021-12-29 14:55 UTC, MartijnVisser requested changes
Thank you for your contribution. 

Please update the PR to follow the PR guidelines as can be found on https://flink.apache.org/contributing/reviewing-prs.html and update your commit message to follow the Code Style & Quality Guidelines, which can be found at https://flink.apache.org/contributing/code-style-and-quality-preamble.html. 

Also, you've opened multiple PRs with one or a couple of small changes. You could also consider making all these change in one PR and one commit.

2021-12-30 15:03 UTC, sky-walking commented
Thank you for your review. I have finished correcting it.

2021-12-31 11:03 UTC, MartijnVisser approved these changes
Thank you, LGTM. @fapaul can you please merge?

2022-01-03 09:45 UTC, fapaul requested changes
This change does not feel like a `[docs]` PR and rather `[hbase]`. Can you please update the commit message?

2025-03-30 06:27 UTC, closed without merging