[FLINK-25589][docs][connectors] Update Chinese version of Elasticsearch connector docs
apache/flink pull request #18322
Opened 2022-01-11 05:06 UTC by biyuhao

## What is the purpose of the change

Update Chinese version document of Elasticsearch sink interface related to [FLINK-24326](https://issues.apache.org/jira/browse/FLINK-24326) (#17930)

## Brief change log

  - Translate `docs/content.zh/docs/connectors/datastream/elasticsearch.md`
  - Translate `docs/content.zh/docs/connectors/table/elasticsearch.md`
  - Trivial fix of `docs/content/docs/connectors/datastream/elasticsearch.md`

## Verifying this change

This is a document update.
Please build docs locally to verify document content and syntax.
```
cd docs
./build_docs.sh -p
```
Then you can preview `http://localhost:1313` in the local browser.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

2022-01-11 08:33 UTC, biyuhao commented
@flinkbot run azure

2022-01-13 19:41 UTC, JingGe requested changes

2022-01-13 19:41 UTC, JingGe commented on docs/content.zh/docs/connectors/datastream/elasticsearch.md
>          <td>6.x</td>
```suggestion
       <td><= 6.3.1</td>
```

2022-01-13 19:41 UTC, JingGe commented on docs/content.zh/docs/connectors/datastream/elasticsearch.md
> +用户可以通过配置自行启用 Elasticsearch sink 的 at-least-once 语义。
```suggestion
用户可以选择启用 Elasticsearch sink 的 at-least-once 语义。
```

2022-01-13 19:41 UTC, JingGe commented on docs/content.zh/docs/connectors/datastream/elasticsearch.md
> +启用 Flink checkpoint 后，Flink Elasticsearch Sink 可以保证至少一次将操作请求发送到 Elasticsearch 集群。
```suggestion
通过启用 Flink checkpoint ，Flink Elasticsearch Sink 可以保证至少一次将操作请求发送到 Elasticsearch 集群。
```

2022-01-13 19:41 UTC, JingGe commented on docs/content.zh/docs/connectors/datastream/elasticsearch.md
> +checkpoint 会进行等待直到 Elasticsearch 节点队列有足够的容量来处理所有挂起的请求，或者达到最大重试次数。
```suggestion
checkpoint 会进行等待，直到 Elasticsearch 节点队列有足够的容量来处理所有挂起的请求，或者达到最大重试次数。
```

2022-01-13 19:41 UTC, JingGe commented on docs/content.zh/docs/connectors/datastream/elasticsearch.md
> + * **setBulkFlushBackoffStrategy(FlushBackoffType flushBackoffType, int maxRetries, long delayMillis)**：延迟重试的类型，`CONSTANT` 或者 `EXPONENTIAL`，延迟重试次数，延迟重试的时间间隔。
```suggestion
 * **setBulkFlushBackoffStrategy(FlushBackoffType flushBackoffType, int maxRetries, long delayMillis)**：退避延迟的类型，`CONSTANT` 或者 `EXPONENTIAL`，退避重试次数，退避重试的时间间隔。
```

2022-01-13 19:41 UTC, JingGe commented on docs/content.zh/docs/connectors/table/elasticsearch.md
>        <td>每次回退尝试之间的延迟。对于 <code>CONSTANT</code> 回退策略，该值是每次重试之间的延迟。对于 <code>EXPONENTIAL</code> 回退策略，该值是初始的延迟。</td>
```suggestion
      <td>每次退避尝试之间的延迟。对于 <code>CONSTANT</code> 退避策略，该值是每次重试之间的延迟。对于 <code>EXPONENTIAL</code> 退避策略，该值是初始的延迟。</td>
```

2022-01-14 15:37 UTC, biyuhao commented on docs/content.zh/docs/connectors/datastream/elasticsearch.md
> +        <td>7.x</td>
sorry, forgot to mention that it comes from FLINK-25189
thanks for the review

2022-01-17 08:14 UTC, JingGe approved these changes
LGTM

2022-01-17 09:06 UTC, JingGe commented
@flinkbot run azure

2022-01-17 10:45 UTC, JingGe commented
@fapaul Would you like to merge this PR? Thanks.

2022-01-17 10:49 UTC, merged