[FLINK-25975][docs] add document about AvroParquet format use cases
apache/flink pull request #18660
Opened 2022-02-08 10:37 UTC by JingGe

## What is the purpose of the change

Add user facing document for AvroParquet format.

## Brief change log

  - use case for Avro Generic record
  - use case for Avro Specific record
  - use case for Avro Reflect record

## Verifying this change

This change is a trivial documentation without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)

2022-02-08 15:02 UTC, MartijnVisser requested changes
Thanks for the PR @JingGe - I've left some comments based on https://flink.apache.org/contributing/docs-style.html. At first I was wondering if the writing of Avro fitted more with the Avro format documentation, but I think this is so specific to Parquet that it's probably best to stay with the Parquet format documentation.

2022-02-08 15:02 UTC, MartijnVisser commented on docs/content/docs/connectors/datastream/formats/parquet.md
> +and then create a DataStream containing Parquet records as Avor Reflect records.
```suggestion
You create an `AvroParquetRecordFormat` via `AvroParquetReaders` for Avro Reflect record
and then create a DataStream containing Parquet records as Avro Reflect records.
```

2022-02-08 15:02 UTC, MartijnVisser commented on docs/content/docs/connectors/datastream/formats/parquet.md
> +#### Continuous read example
```suggestion
#### Unbounded stream example
```

2022-02-08 15:02 UTC, MartijnVisser commented on docs/content/docs/connectors/datastream/formats/parquet.md
> +infinitely as new files are added to the directory.
```suggestion
This example, similar to the bounded data example, uses the same POJO Java class `Datum`
and monitors for the new files every second to read Avro Reflect records from Parquet files
infinitely as new files are added to the directory.
```

2022-02-08 15:36 UTC, JingGe commented on docs/content/docs/connectors/datastream/formats/parquet.md
> +#### Bounded read example
The original text was "read" and the use case is reading records. Could you share your thoughts of replacing the "read" with the "data"?

2022-02-09 10:22 UTC, MartijnVisser commented on docs/content/docs/connectors/datastream/formats/parquet.md
> +#### Bounded read example
I think we should go for Unbounded Streams and Bounded Streams, like is explained on https://flink.apache.org/flink-architecture.html

2022-02-09 10:31 UTC, JingGe commented on docs/content/docs/connectors/datastream/formats/parquet.md
> +#### Bounded read example
hmm, even on that page there are two different names: Unbounded and Bounded Data vs. Stream. Let's use stream.

2022-02-09 11:10 UTC, JingGe commented on docs/content/docs/connectors/datastream/formats/parquet.md
> +#### Bounded read example
let's use Bounded/Unbounded data for naming consistency.

2022-02-09 11:18 UTC, JingGe commented
Thanks @MartijnVisser for your effort! I have fixed all found issues.

2022-02-09 12:53 UTC, MartijnVisser approved these changes
Thanks for fixing it @JingGe - I saw one more typo, but overall LGTM.

2022-02-09 12:53 UTC, MartijnVisser commented on docs/content/docs/connectors/datastream/formats/parquet.md
> +This example, similar to the bound batch example, uses the same generated Address Java class
```suggestion
This example, similar to the bounded batch example, uses the same generated Address Java class 
```

2022-02-09 12:53 UTC, MartijnVisser commented on docs/content/docs/connectors/datastream/formats/parquet.md
> +This example, similar to the bound batch example, uses the same POJO Java class `Datum`
```suggestion
This example, similar to the bounded batch example, uses the same POJO Java class `Datum`
```

2022-02-09 13:48 UTC, JingGe commented
@tillrohrmann This PR is now ready. Would you please help merging it? Thanks.

2022-02-09 13:56 UTC, tillrohrmann commented
Sure. Let me know once AZP gives green light @JingGe.

2022-02-09 19:39 UTC, JingGe commented
@flinkbot run azure

2022-02-10 10:13 UTC, closed without merging