[FLINK-25793][connector/base] Implement additive increase/multiplicative decrease to limit throughput
apache/flink pull request #18880
Opened 2022-02-22 14:45 UTC by vahmed-hamdy

## What is the purpose of the change

Introuducing RateLimiting Strategy for `AsyncSinkWriter` base and Additive Increase Multiplicative Decrease Strategy to `KinesisSinkWriter` and `KinesisFirehoseWriter`.

## Brief change log

  - Added `RateLimitingStrategy` Interface and made `AsyncSinkWriter` depend on it.
  - Added `AIMDRateLimitingStrategy` to base module.
  - changed throttling condition in `AsyncSinkWriter` to depend on `RateLimitingStrategy`.
  - modified `KinesisSinkWriter` and `KinesisFirehoseWriter` to depend on `AIMDRateLimitingStrategy`.

## Verifying this change
 - Added unit tests for newly implemented strategy in `flink-connector-base`.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: yes
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

2022-02-22 16:00 UTC, dannycranmer commented on flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AIMDRateLimitingStrategyTest.java
> +        Assertions.assertThat(rateLimitingStrategy.getInFlightMessagesLimit())
nit: These are more readable with a static import for `assertThat`

2022-02-22 17:02 UTC, dannycranmer requested changes

2022-02-22 17:02 UTC, dannycranmer commented on flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterTest.java
> +        ExecutorService es = Executors.newFixedThreadPool(10);
Why create a thread pool of size 10 when you are only making 2 requests?

2022-02-22 17:02 UTC, dannycranmer commented on flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterTest.java
> +                                    e.printStackTrace();
If this happens will the test fail?

2022-02-22 17:28 UTC, vahmed-hamdy commented on flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriter.java
> +    public AsyncSinkWriter(
I agree, The multiple implementations of constructor are more confusing than helpful.

2022-02-22 17:45 UTC, dannycranmer commented on flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriter.java
> +        inFlightMessages -= messages;
Yep, on second inspection I agree. Thanks

2022-02-22 18:17 UTC, fapaul commented
I do not want to be the devil's advocate but this PR looks like a new feature for the AsyncSink that would require a FLIP and we are passed the feature freeze so we can very likely only merge it to 1.16.

2022-02-22 18:24 UTC, vahmed-hamdy commented on flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriter.java
> +            RateLimitingStrategy rateLimitingStrategy,
I agree with wrapping the parameters with a config object, captured in this JIRA [FLINK-26310].
I believe we don't need a builder. The writer should only be created via the sink in normal cases.

2022-02-23 13:48 UTC, dannycranmer commented
> I do not want to be the devil's advocate but this PR looks like a new feature for the AsyncSink that would require a FLIP and we are passed the feature freeze so we can very likely only merge it to 1.16.

@fapaul we were treating this change as a bug, however I agree the new interface definitions are edging into new feature territory. During our testing we have found that when the output streams are underprovisioned, saturating the destination stream results in a high number of records throttled. This results in a high retry count and consumes un-necessary CPU/network. See graph below, `aimd8`/`aimd50` contain this fix and `async8`/`async50` do not. You can see that the `aimd` implementation has slightly better throughput and significantly less throttling.

<img width="1440" alt="Screenshot 2022-02-23 at 09 59 45" src="https://user-images.githubusercontent.com/4950503/155303236-7c0be0b8-816f-424b-b2ea-7d510eca2766.png">

In response to your feedback, in order to remediate the issues observed in KDF/KDS sinks I propose we remove the rate limiting strategy change from the Async Sink base, and move to the concrete implementation. This would leave the Async Sink Base public interface untouched. We can then follow up with a FLIP to define how the rate limiting interfaces will work and pull into the Async Sink base. In order to facilitate this change we would need to extract 2 methods in AsyncSinkWriter that can be overridden to introduce the limiting.

2022-02-23 14:35 UTC, dannycranmer commented
I discussed this with @fapaul and we agreed that we can merge this change as a bug fix if we do not modify any public API. Therefore instead of adding the rate limiter to the concrete KDF/KDS implementation we will add it directly to the `AsyncSinkWriter`. We will follow up in Flink 1.16 with a FLIP to consolidate the feature and refactor at this point.

2022-02-23 14:40 UTC, fapaul commented
> I discussed this with @fapaul and we agreed that we can merge this change as a bug fix if we do not modify any public API. Therefore instead of adding the rate limiter to the concrete KDF/KDS implementation we will add it directly to the `AsyncSinkWriter`. We will follow up in Flink 1.16 with a FLIP to consolidate the feature and refactor at this point.

Thanks for the detailed analysis and everyone working on this PR. The idea with the automatic buffer size calculations sounds definitely great. Unfortunately, we have to postpone the general availability of configurations a bit to avoid breaking APIs.
Let's work together in 1.16 to roll this out in a configurable way.

2022-02-23 22:06 UTC, vahmed-hamdy commented
superseded by #18902

2022-02-23 22:06 UTC, closed without merging