[FLINK-26998] Remove log-related configuration from predefined options in RocksDB state backend
apache/flink pull request #19335
Opened 2022-04-02 03:40 UTC by Zakelly

## What is the purpose of the change

After FLINK-23791, the RocksDB log should be enabled by default. However, the log-related configuration remains in ```PredefinedOptions```, which will override the default value provided in ```RocksDBConfigurableOptions```.
We could remove the related values in ```PredefinedOptions``` and let ```RocksDBConfigurableOptions``` take control of the default value.

## Brief change log

  -  Remove the log related values in ```org/apache/flink/contrib/streaming/state/PredefinedOptions.java```

## Verifying this change

This change modified test RocksDBStateBackendConfigTest.testDefaultDbLogDir

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no
 
## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

2022-04-02 04:03 UTC, Myasuka requested changes
Thanks for creating this PR. Please take a look at my comments.

2022-04-02 04:03 UTC, Myasuka commented on flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/PredefinedOptions.java
>       *   <li>setInfoLogLevel(InfoLogLevel.HEADER_LEVEL)
We should also remove such comments.
The same for all other options defined in this file.

2022-04-02 09:16 UTC, Zakelly commented
@Myasuka Thanks for your review! Would you please to take another look?

2022-04-02 09:17 UTC, Zakelly commented
The CI failed, but it succeeded in my setup:  https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=34149&view=results

2022-04-03 05:27 UTC, Myasuka commented
@flinkbot run azure

2022-04-03 11:54 UTC, Myasuka approved these changes
LGTM.

2022-04-03 12:00 UTC, closed without merging