[FLINK-27438][table-planner] Fix the constructing a map array
apache/flink pull request #19648
Opened 2022-05-05 04:24 UTC by rovboyko

## What is the purpose of the change

This pull request fixes the ValidationException appears while trying to construct the array of maps. The bug appeared after adding explicit casting into SqlArrayConstructor in 0f51995bc156435eb9e97d2ac15e0225117877e2.

## Brief change log

  - add cast to map sql data type functionality into SqlValidatorUtils
  - add tests for plan verification inside batch and stream test sets

## Verifying this change

  - Extended unit tests for Calc exec plan verification

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no

2022-05-06 02:39 UTC, rovboyko commented
@flinkbot run azure

2022-05-06 12:17 UTC, matriv reviewed
@rovboyko Thank you for the fix! left some comments.

2022-05-06 12:17 UTC, matriv commented on flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/utils/SqlValidatorUtils.java
> +        SqlDataTypeSpec dataTypeSpec;
```suggestion
        final SqlDataTypeSpec dataTypeSpec;
```

2022-05-06 12:17 UTC, matriv commented on flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/utils/SqlValidatorUtils.java
> +        SqlDataTypeSpec dataTypeSpec;
```suggestion
        final RelDataType keyType = type.getKeyType();
        final RelDataType valueType = type.getValueType();
        final SqlTypeNameSpec sqlTypeNameSpec =
                new SqlMapTypeNameSpec(
                        SqlTypeUtil.convertTypeToSpec(keyType).withNullable(keyType.isNullable()),
                        SqlTypeUtil.convertTypeToSpec(valueType)
                                .withNullable(valueType.isNullable()),
                        SqlParserPos.ZERO);
        return new SqlDataTypeSpec(sqlTypeNameSpec, SqlParserPos.ZERO);
```

2022-05-06 12:17 UTC, matriv commented on flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/CalcTest.scala
> +    util.verifyExecPlan(
Can we also add a test where the key or value (or both) is of some other type, like a numeric?

2022-05-06 12:17 UTC, matriv commented on flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/CalcTest.scala
> +    util.verifyExecPlan(
same here

2022-05-06 13:01 UTC, matriv approved these changes
LGTM. Thank you!

2022-05-06 13:44 UTC, rovboyko commented
> @MartijnVisser Would be great to backport it to 1.15 and I guess 1.14 as well.

Yes, we discussed it, I'll do it.

2022-05-09 13:12 UTC, twalthr requested changes
I left a comment. TBH I'm not sure if [FLINK-19796](https://issues.apache.org/jira/browse/FLINK-19796) was actually the right approach to fix the issue. We could have simply adapted the runtime implementation to perform the casting during runtime instead of modifying the plan and the built-in operator. This change in Calcite's default type inference might cause downstream issues in the optimizer.

2022-05-09 13:12 UTC, twalthr commented on flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/utils/SqlValidatorUtils.java
> +        if (SqlTypeUtil.isMap(type)) {
Isn't this only fixing the top-level problem but not nested problems such as `ARRAY[ARRAY[MAP]]` or even more complex `ARRAY[MAP[ARRAY[MAP]]]`?

2022-05-09 13:13 UTC, twalthr commented on flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/utils/SqlValidatorUtils.java
> +        if (SqlTypeUtil.isMap(type)) {
Btw in `org.apache.flink.table.planner.functions.inference.TypeInferenceOperandChecker#castTo` we would have a similar issue, correct?

2022-05-11 14:45 UTC, rovboyko commented
> I left a comment. TBH I'm not sure if [FLINK-19796](https://issues.apache.org/jira/browse/FLINK-19796) was actually the right approach to fix the issue. We could have simply adapted the runtime implementation to perform the casting during runtime instead of modifying the plan and the built-in operator. This change in Calcite's default type inference might cause downstream issues in the optimizer.

Hi Timo @twalthr . Ok I've got your idea and try to adapt the runtime to different decimal precision (instead of [FLINK-19796]).
Could you please take a look?

2022-05-16 14:55 UTC, rovboyko commented
ping @twalthr

2022-05-19 07:50 UTC, twalthr requested changes
Sorry for the delay. Great that the PR removes more than it adds :) We just need to make sure that the casting is applied to all kinds of data types.

2022-05-19 07:50 UTC, twalthr commented on flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/CodeGenUtils.scala
> +      case (toDec: DecimalType, _: DecimalType) =>
This is a bit too specific. We should simply cast all arguments to `arrayType.getElementType` using the `generateCast` method.

2022-05-26 04:58 UTC, rovboyko commented
Hi Timo @twalthr  !
I've rewritten the solution according to your idea to use the `generateCast` method.
I had to change the `CodeGeneratorCastRule` to it be able to declare not only variables but the class fields too.
Could you please take a look?

2022-05-30 10:25 UTC, rovboyko commented
@flinkbot run azure

2022-05-30 14:02 UTC, MartijnVisser commented
@rovboyko You'll need to rebase on master to get the latest fixes in that are currently blocking a successful CI run

2022-07-05 10:44 UTC, MartijnVisser commented
> Could you please take a look?

@twalthr Can you have one more final look?

2025-03-31 06:27 UTC, closed without merging