[hotfic][doc] fix doc of chapter etl
apache/flink pull request #20077
Opened 2022-06-27 04:01 UTC by nyingping

## What is the purpose of the change

Fix doc of chapter etl.

## Brief change log

<ol>
<li> Add InputSelectable link address ,add  missing ')' at the end of note.</li>
<li> Updated the Chinese definition of `truly Desperate`. In context, I think `迫切渴望` is better than `感到绝望`.`绝望` is more like `despair`.</li>
</ol>

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)no
  - The serializers: (yes / no / don't know)no 
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)no 
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)no 
  - The S3 file system connector: (yes / no / don't know)no

## Documentation

  - Does this pull request introduce a new feature? (yes / no)no
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)not applicable

2022-06-28 00:35 UTC, nyingping commented
@flinkbot run azure

2022-06-30 08:58 UTC, MartijnVisser commented on docs/content/docs/learn-flink/etl.md
> +It is important to recognize that you have no control over the order in which the `flatMap1` and `flatMap2` callbacks are called. These two input streams are racing against each other, and the Flink
```suggestion
It is important to recognize that you have no control over the order in which the `flatMap1` and `flatMap2` callbacks are called. These two input streams are racing against each other, and the Flink runtime will do what it wants to regarding consuming events from one stream or the other. In cases where timing and/or ordering matter, you may find it necessary to buffer events in managed Flink state until your application is ready to process them. (Note: if you are truly desperate, it is possible to exert some limited control over the order in which a two-input operator consumes its inputs by using a custom Operator that implements the {{< javadoc name="InputSelectable" file="org/apache/flink/streaming/api/operators/InputSelectable.html" >}}
```

2022-06-30 08:58 UTC, MartijnVisser requested changes
@nyingping Thanks but we have a specific way of linking to JavaDoc, see suggestions.

2022-06-30 08:58 UTC, MartijnVisser commented on docs/content.zh/docs/learn-flink/etl.md
> +认识到你没法控制 `flatMap1` 和 `flatMap2` 的调用顺序是很重要的。这两个输入流是相互竞争的关系，Flink 运行时将根据从一个流或另一个流中消费的事件做它要做的。对于需要保证时间和/或顺序的场景，你会发现在 Flink 的管理状态中缓存事件一直到它们能够被处理是必须的。（注意：如果你真的迫切需要，可以使用自定义的算子实现 [`InputSelectable`](https:
```suggestion
认识到你没法控制 `flatMap1` 和 `flatMap2` 的调用顺序是很重要的。这两个输入流是相互竞争的关系，Flink 运行时将根据从一个流或另一个流中消费的事件做它要做的。对于需要保证时间和/或顺序的场景，你会发现在 Flink 的管理状态中缓存事件一直到它们能够被处理是必须的。（注意：如果你真的迫切需要，可以使用自定义的算子实现 {{< javadoc name="InputSelectable" file="org/apache/flink/streaming/api/operators/InputSelectable.html" >}} 接口，在两输入算子消费它的输入流时增加一些顺序上的限制。）
```

2022-06-30 09:24 UTC, nyingping commented
@MartijnVisser Thanks for review and suggestions!

2022-07-20 07:35 UTC, MartijnVisser approved these changes
@nyingping I've rebased your PR and I'll merge it now. Thanks for the improvement!

2022-07-20 07:35 UTC, merged