[FLINK-27941][connectors][test] kinesis connector test module migrate…
apache/flink pull request #20129
Opened 2022-07-01 09:49 UTC by mddxhj

… to junit5

## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluster with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

2022-07-01 17:42 UTC, reswqa requested changes

2022-07-01 17:42 UTC, reswqa commented on flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumerMigrationTest.java
> +    public void testRestoreWithEmptyState(FlinkVersion flinkVersion) throws Exception {
```suggestion
    void testRestoreWithEmptyState(FlinkVersion flinkVersion) throws Exception {
```

2022-07-01 17:42 UTC, reswqa commented on flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/KinesisConsumerTest.java
>  public class KinesisConsumerTest extends TestLogger {
```suggestion
@ExtendWith(TestLoggerExtension.class)
class KinesisConsumerTest {
```

2022-07-01 17:42 UTC, reswqa commented on flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutShardSubscriberTest.java
>  import org.junit.Test;
Why org.junit.Test still exist

2022-07-02 15:57 UTC, Myasuka requested changes
Thanks for creating this PR!
For `FlinkKinesisConsumerTest`, I tried to remove the dependencies of `PowerMockRunner`, however, it might need more time to rewrite the test.
For the ignored `FlinkKinesisITCase`, I think we can use junit5 related tag to replace junit4s'. Since we might need some extra efforts, and for the `kinesalite` with `ClassRule` tag, we can just remove the `ClassRule`tag with a `TODO` annotation.

2022-07-02 15:57 UTC, Myasuka commented on flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumerMigrationTest.java
>      @Ignore
Should use `Disabled` to replace.

2022-07-02 15:57 UTC, Myasuka commented on flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumerMigrationTest.java
>  import org.junit.Test;
I think we should move these two imports to junit5 based.

2022-07-02 15:57 UTC, Myasuka commented on flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/util/KinesisConfigUtilTest.java
>  import org.powermock.modules.junit4.PowerMockRunner;
I tried to remove this in this test, and it seems okay.

2022-10-07 07:47 UTC, XComp commented
@mddxhj Are you still working on this issue?

2025-03-31 06:28 UTC, closed without merging