[FLINK-28411] - Error Handling for OperatorCoordinatorHolder which may fail Session Cluster
apache/flink pull request #20186
Opened 2022-07-06 15:25 UTC by darenwkt

## What is the purpose of the change

This pull request adds error handling around OperatorCoordinatorHolder.start method, addressing problem raised in [FLINK-28411]. Previously, exception from this method (I.e from starting OperatorCoordinator) bubbles up to Dispatcher to trigger a fatal error which brings down the entire cluster. With this new change, OperatorCoordinatorHolder will instead trigger a globalFailure which is handled by the Scheduler. 

## Brief change log

OperatorCoordinatorHolder.start now handles exception thrown from OperatorCoordinator.start. It rethrows the error if it's a JVM/OOM fatal error. Else, it triggers a globalFailure which is handled by Scheduler to attempt to restart the Job.

## Verifying this change

Added Unit Test to validate:
- Exception is caught and not bubbled up above OperatorCoordinatorHolder.
- GlobalFailure is successfully triggered.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

2022-07-12 20:12 UTC, darenwkt commented
@flinkbot run azure

2022-07-20 16:39 UTC, dannycranmer commented
@darenwkt you have a CI failure on compilation step, can you please take a look?

2022-07-20 16:43 UTC, dannycranmer requested changes

2022-07-20 16:43 UTC, dannycranmer commented on mvnvm.properties
> +mvn_version=3.2.5
What is this for? This is an old maven version, looks like this is not intentional?

2022-07-20 16:43 UTC, dannycranmer commented on flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinatorHolderTest.java
> +        assertNotNull(globalFailure);
Can you add an assertion to check that the job is cancelled with the appropriate error?

2022-09-07 14:33 UTC, closed without merging