[FLINK-28522][tests][JUnit5 migration] flink-sequence-file
apache/flink pull request #20258
Opened 2022-07-12 23:57 UTC by RyanSkraba

## What is the purpose of the change

Update the `flink-formats/flink-sequence-file` module to AssertJ and JUnit 5 following the [JUnit 5 Migration Guide](https://docs.google.com/document/d/1514Wa_aNB9bJUen4xm5uiuXOooOJTtXqS_Jqk9KJitU/edit)

## Brief change log

* Removed dependences on JUnit 4, JUnit 5 Assertions and Hamcrest where possible.

## Verifying this change

This change is a code cleanup without any test coverage.

I verified that there were 4 tests run before and after the change.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive):no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no

2022-07-13 16:26 UTC, RyanSkraba commented
@flinkbot run azure

2022-10-06 15:20 UTC, XComp reviewed
LGTM :+1: Again, some minor cosmetic comments. I'm curious what you think. Please rebase the branch to make it ready to being merged.

2022-10-21 16:43 UTC, RyanSkraba commented on flink-formats/flink-sequence-file/src/test/java/org/apache/flink/formats/sequencefile/SerializableHadoopConfigurationTest.java
> +                            return actualConfig != configuration
This needed to be rewritten in order to compile.   I squashed it into the single commit.

2022-10-25 09:08 UTC, XComp commented
`KafkaShuffleExactlyOnceITCase` failed due to FLINK-24119. I added the pipeline run to the ticket already. I'm going to investigate the `PulsarSourceUnorderedE2ECase` test failure (see [build failure](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=42325&view=logs&j=af184cdd-c6d8-5084-0b69-7e9c67b35f7a&t=160c9ae5-96fd-516e-1c91-deb81f59292a&l=14720))

2022-10-25 12:12 UTC, XComp requested changes
We seem to use the description logic in the wrong way. Please have a look.

2022-10-25 12:13 UTC, XComp commented
I created FLINK-29755 to cover the `PulsarSourceUnorderedE2ECase.testSavepoint` test failure in the [failed build](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=42325&view=logs&j=af184cdd-c6d8-5084-0b69-7e9c67b35f7a&t=160c9ae5-96fd-516e-1c91-deb81f59292a&l=14380)

2022-10-25 16:45 UTC, RyanSkraba commented on flink-formats/flink-sequence-file/src/test/java/org/apache/flink/formats/sequencefile/SerializableHadoopConfigurationTest.java
> +                .describedAs(
Yes, it seems that the `describedAs` needs to come before any asserts!

In this case, I changed the logic quite a bit from the original to improve the descriptive error messages.  The new logic would print the error message:

```
[ERROR] Failures: 
[ERROR]   SerializableHadoopConfigurationTest.customPropertiesSurviveSerializationDeserialization:60 
[a Hadoop Configuration with property: key=test-key and value=test-value] (1 failure)
-- failure 1 --
expected: "test-value"
 but was: "faked-for-error-message"
```

2022-11-03 15:58 UTC, XComp approved these changes

2022-11-04 08:28 UTC, XComp commented
I accidentally cancelled the squash-merge but the corresponding commit 276bb778c7ea4555370c6155af5128ea7f7cbe6c ended up on `master` as planned. Therefore, I'm manually closing this PR. The PR is considered `MERGED`.

2022-11-04 08:28 UTC, closed without merging