Draft: send events from reader to enumerator
apache/flink pull request #20289
Opened 2022-07-17 03:52 UTC by xinbinhuang

## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluster with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

2022-07-17 20:27 UTC, xinbinhuang commented on flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumerator.java
> +                                                && split.sourceIndex() == previousSourceIndex)
this is a paranoid check..

2022-07-18 01:19 UTC, xinbinhuang commented
@flinkbot run azure

2022-07-18 01:21 UTC, xinbinhuang commented
cc: @tweise This is the first draft of the implementation. PTAL! 
(i'm planning to add more tests gradually)

2022-07-18 01:27 UTC, xinbinhuang commented on flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumerator.java
> +            // TODO: should finishedReaders be reset after switching to a new numerator?
@tweise It seems that `finishedReaders` will keep increasing after the first switch unless the job is restarted. So if there are more than 2 sources in the chain, the 3rd and latter source may never get triggered. Is my understand correct?

2022-07-19 00:45 UTC, xinbinhuang commented
@flinkbot run azure

2022-07-20 19:49 UTC, xinbinhuang commented
@flinkbot run azure

2022-07-27 01:20 UTC, tweise commented
@xinbinhuang looking at all the modifications to HybridSource itself I think it is necessary to take a step back here and discuss the design aspects first.

The underlying sources are a sequence of bounded sources, optionally followed by an unbounded source. Therefore, there should be no need to have a "dynamic reader" that does special things. The enumerator knows upfront which splits need to be processed and when it is finished.

The HybridSource already has the support to transfer the end position to the next enumerator. That was part of the FLIP and the details can be found https://cwiki.apache.org/confluence/display/FLINK/FLIP-150%3A+Introduce+Hybrid+Source and you can find an example in the tests: HybridSourceITCase.sourceWithDynamicSwitchPosition

2022-07-27 01:21 UTC, tweise requested changes
Pending clarification of design.

2022-07-27 05:47 UTC, xinbinhuang commented
@tweise Thank you so much for reviewing the PR! I just realized that I might have misread jira issue as `HybridSource: Support dynamic stop position in HybridSource` instead of `HybridSource: Support dynamic stop position in FileSource`. So this PR actually aimed to design an _**generic interface to allow any sources to participate in dynamic source switch**_. With that in mind. Let me explain how I came up with the current design & implementation.

After reviewing the current logic of the hybrid source (amazing work 🎉 🎉 !!), I understand that the current implementation support transferring the end position to the next enumerator. However, it lacks the mechanism to know where is the end position (i.e. offset for a kafka partition). And these "end positions" are probably unknown beforehand, or it would be the same as [fixed start position](https://nightlies.apache.org/flink/flink-docs-master/docs/connectors/datastream/hybridsource/#fixed-start-position-at-graph-construction-time)?
Therefore, I think the key is to transfer the "end position" to the enumerator from source reader during source switch. 
There are a few points to consider:

1. What would be the "end position" to transfer to the next source? 

I believe this varied by use cases. Some may find it enough to use `file.path`, while some may require to derive the timestamp or offset from the content of the file (i.e. kafka archive, and the implementation can vary by companies.). Since we can't anticipate all use cases, passing all finished splits seem to be a reasonable solution here and let the developer to decide how to derive the position from them.

2. Where to make the changes?

I aimed to implement this s.t. most existing sources can benefit from it out of the box with minimal changes and no breaking changes to them.


3. How to store the "finished splits" before source switch?

Per FLIP-27, the enumerator only knows what splits to consume but not the actual progress - only source reader knows about it. So we need to store them and transfer them to the enumerator during source switch. However, most existing sources implements `SourceReaderBase` and it [purges them from state](https://github.com/apache/flink/blob/3e2620bc785b3b4d82f1f188eb7b1e0e129b14d3/flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/SourceReaderBase.java#L193-L194) once it reaches the end position. One naive solution would be to adjust `SourceReaderBase` to also store finished splits into the state. However, this'll affect all sources running in production and is probably a big backward incompatible changes right away. Therefore, I decided to store them only in the `HybridSourceReader`, and the existing sources only need to implement one method (`DynamicHybridSourceReader::getFinishedSplits`) that allows the finished splits to be extracted during checkpoint and source switch. This process is transparent to all existing sources, and only happens when used with the `HybridSource`.

With the above points, the current implementation works as follow:
- On each checkpoint,  `HybridSourceReader`  retrieve the finished states (marked with  `HybridSourceSplit.isFinished = true`) from the underlying reader and checkpoint them for persistent along with the unfinished states.
- Upon source switch,  `HybridSourceReader`  will send all the finished splits in  `SourceReaderFinishedEvent`  to the enumerator.
- Enumerator will pass along those finished splits to in  `SourceSwitchContext`  to the next source. And the next source can them use the splits to derive the start positions.

#### Changes required on existing non hybrid sources:
- Implements `DynamicHybridSourceReader::getFinishedSplits` on `SourceReaderBase`.

#### API changes on `HybridSource`
- Added `SourceSwitchContext::getPreviousSplits` which returns finished splits from the previous source.

It's a lot of words, so really appreciate your patience for reading this. Let me know if there are anything unclear, I'm happy to chat more about this!

2022-07-27 15:10 UTC, tweise commented
@xinbinhuang thanks for describing the thought process.

As you already mentioned, the goal of the JIRA was to add the passing of end position to file source and when we implemented FLIP-150 we presumably already added everything that is required to achieve that goal to the HybridSource. 

I think we need to zoom in why or why not the enumerator knows the actual stop position without involvement of the reader. 

It is correct that we do not know the stop position at graph construction time or otherwise we would not need any runtime behavior. However, the enumerator already knows what splits have been processed because it has passed those to the readers and the readers have finished the splits that they got assigned. Remember that we are dealing with **bounded** sources. So there really should be no need to pass splits back to the enumerator. Now it will depend on the specific type of source how the enumerator communicates the end position to the next enumerator. In most typical cases that will simply come from the partition metadata (iceberg, files).

2022-10-07 20:09 UTC, xinbinhuang commented
@tweise was distracted by other works. Let me get back to this.
> I think we need to zoom in why or why not the enumerator knows the actual stop position without involvement of the reader.

Our use case is to expose end offset or timestamp based on the content of the file. We're archiving out-of-retention messages into S3 using a long-running job. Normally there are multiple messages inside the files, and the timestamp of the last message may not align with the file metadata. So we'll need to actually parse the file content to find out either the last timestamp or offset. That's why I think sending back the split would make sense, since it's already processed there. 

Do you have any recommendations around this? Or do you think this's too complex to implement?

2022-12-16 17:58 UTC, xinbinhuang commented
@MartijnVisser I would love to move it forward. 
@tweise would you live to take a look again?

2023-12-26 06:34 UTC, waywtdcc commented
How is this going?

2025-04-01 06:25 UTC, closed without merging