[FLINK-28504][streaming] Update watermarks across multiple oneinputstreams.
apache/flink pull request #20337
Opened 2022-07-22 02:29 UTC by nyingping

## What is the purpose of the change

In local-global streaming tasks, the` LOCAL` phase is classified as `POINTWISE` by default in some versions. And in the case of data skew, the following phenomena will occur.

![image](https://user-images.githubusercontent.com/10743150/180346883-5bf24a42-feb8-43e4-8f8f-788ed5815c02.png)

When `table.exec.source-idle-timeout` is set, the watermark is not aligned in the local phase and then pushes downstream.The UI is confusing,While the `idleness` effect is achieved, But the underlying logic doesn't seem to make sense.

In the `ALL-TO-ALL` case, as shown in down picture, each Input stream task contains all channels, and all Netty Input channels share a watermark value in main memory.Watermark Value or Watermark Status is updated in different input stream tasks. Other input stream tasks are clearly visible. (volatile)

![OLWY%(4WEI 08W_}WK(YS4](https://user-images.githubusercontent.com/10743150/180347084-67a0de1a-a0b2-4d86-ab43-5ff217b1f3c8.png)

In the case of `POINTWISE`, an input stream task contains only part of the Netty input channels, and each of its channels has its own independent watermark. So its watermark value, and the Posting and updating of the watermark status are only in its own part. That's what caused this. One or a portion of independent channels will advance the watermark to downstream without updating other channels.

In order to avoid this situation, I made the following changes.
However, because the streams task&channels are independent from each other, if the watermark in a certain channel is not aligned, it will not affect the watermark to advance the down stream.

It doesn't matter how many input streams and channels there are, or how they are connected, as long as  update the watermark value across the input stream with in the same Vertex.

updated effect
![image](https://user-images.githubusercontent.com/10743150/180348902-9534980b-f643-4fa0-bf0f-a12a8925c15d.png)

## Brief change log

  - *When creating a stream input task, collect all dataoutputs of the same vertex. When it is necessary to update the watermark, update all outputs together.*
 

## Verifying this change

This change added tests and can be verified as follows:

  - *Added test case verifies that across multiple OneInputStreams update watermark.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

2022-07-28 13:22 UTC, pnowojski requested changes
Aren't you trying to fix a WebUI/REST API issue, that maybe they don't understand idleness in a wrong place? Isn't the core issue here, that the watermark metric from idle subtasks is incorrectly aggregated before being presented in the WebUI?

2022-07-28 13:22 UTC, pnowojski commented on flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/OneInputStreamTask.java
> +                                            watermark.getTimestamp()));
This looks wrong:

1. Having static field accessed like that ring warning bells.
2. Why emitting watermark in one subtask should bump watermark gauge from other subtasks? This sounds very incorrect thing to do. `WatermarkGauge` is not supposed to present max watermark across all subtasks, but the watermark of that given subtask. If something needs to aggregate and get "max" value, this should happen on a higher level, like REST API, or WebUI.
3. Are you sure that job vertex ids are unique across multiple jobs running on the same cluster?
4. It looks like you are creating a memory leak, never removing anything from the `outputList`.

2022-08-04 06:15 UTC, nyingping commented
@pnowojski Thanks for reviewing!
My understanding is that if subtasks of the same vertex can send watermarks downstream without alignment, then the problem does not exist, it is not a bug at all. Maybe we can just close this PR.

2022-08-04 14:21 UTC, pnowojski commented
Hi @nyingping . After giving this a second look I think the current code behaviour is indeed correct and I don't see any bug here. 

You idle source subtasks have never sent any watermark to some of the downstream local aggregations. So those `LocalWindowAggregate` correctly don't report any watermark, resulting in `Low Watermark` in the webUI not being reported. As correctly, low watermark is `NaN` for the task as a whole.

It might be a bit confusing the current behaviour. Ideally maybe WebUI should present the lowest non `NaN` watermark, with a caveate/asteriks, that some subtasks are idle. But to me the current behaviour is also valid.

2022-08-05 00:28 UTC, nyingping commented
@pnowojski @MartijnVisser Thanks for your time.close this PR.

2022-08-05 00:28 UTC, closed without merging