[FLINK-28651] [Runtime / REST] JarRunHandler gets restore mode from configuration when it is missing in the request
apache/flink pull request #20366
Opened 2022-07-26 09:56 UTC by nuno-c-afonso

## What is the purpose of the change

This pull request updates `JarRunHandler` to get the restore mode from the configuration when it is missing from the run request.

## Brief change log

- `getSavepointRestoreSettings` in `JarRunHandler` gets the restore mode from the configuration when it is not defined in the run request
- `JarRunHandlerTest` was added to test the `getSavepointRestoreSettings` method

## Verifying this change

This change added tests and can be verified as follows:

- Added test that validates that `getSavepointRestoreSettings` uses configuration to get the restore mode when it is not defined in the request

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

2022-07-28 08:23 UTC, nuno-c-afonso commented
@flinkbot run azure

2022-07-29 10:29 UTC, zentol requested changes

2022-07-29 10:29 UTC, zentol commented on flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/handlers/JarRunHandler.java
> +    SavepointRestoreSettings getSavepointRestoreSettings(
AFAICT you could make testing way easier by making this static and adding a `Logger` and `Configuration` parameter.

2022-07-29 10:29 UTC, zentol commented on flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/handlers/JarRunHandlerTest.java
> +import static org.mockito.Mockito.when;
Don't use mocking.
You can leverage the `JarHandlers` class to setup a JarRunHandler (just need to a add a coonfiguration parameter) (see `JarHandlerTest` on how it's used) and create a proper `HandlerRequest`.

2022-11-15 09:09 UTC, zentol commented
Fixed as part of FLINK-29543.

2022-11-15 09:09 UTC, closed without merging