[FLINK-29624][Common][Connector][Filesystem] Upgrade commons-lang3 to 3.12.0
apache/flink pull request #21048
Opened 2022-10-13 09:16 UTC by MartijnVisser

## What is the purpose of the change

* Upgrade org.apache.commons:commons-lang3 from 3.3.2 to 3.12.0 to avoid being falsely flagged for CVEs CVE-2021-29425 and CVE-2020-15250

## Brief change log

* Update POM file and NOTICE files

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): yes
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

2022-10-13 13:18 UTC, zentol requested changes
pulsar should also use this version.

This results in us using several deprecated APIs that have been moved to a new commons-text project:
* org.apache.commons.lang3.StringEscapeUtils
Other now deprecated APIs that we use:
* org.apache.commons.lang3.ArrayUtils#add

2022-10-13 13:20 UTC, zentol commented
I don't understand how these CVEs are related. One if for commons-io, the other for jUnit.

2022-10-13 14:20 UTC, MartijnVisser commented
> I don't understand how these CVEs are related. One if for commons-io, the other for jUnit.

Both are transitive dependencies of commons-lang3, which gets picked up by scanners. False flags, but still better to avoid.

2022-10-14 09:54 UTC, zentol commented
I haven't seen a test scanner complain about a test dependency of another project. Where was that reported?

2022-10-25 19:11 UTC, MartijnVisser commented
@flinkbot run azure

2022-10-26 07:15 UTC, MartijnVisser commented
@flinkbot run azure

2022-11-01 10:03 UTC, zentol approved these changes
Please squash the last 4 commits when merging.

2022-11-01 10:36 UTC, merged

2022-11-01 10:36 UTC, MartijnVisser commented
CI run completed in https://dev.azure.com/apache-flink/98463496-1af2-4620-8eab-a2ecc1a2e6fe/_build/results?buildId=42410