[FLINK-29157][doc] Clarify the contract between CompletedCheckpointStore and SharedStateRegistry
apache/flink pull request #21053
Opened 2022-10-13 10:49 UTC by fredia

## What is the purpose of the change

Improve logging in CompletedCheckpointStore

## Verifying this change

This change is a trivial rework without any (new) test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature?  no
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

2022-10-17 04:28 UTC, masteryhx commented on flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CompletedCheckpointStore.java
> +     * SharedStateRegistry must be the same object as the input parameter, otherwise the state may
IIUC, the fallible place is SharedStateRegistryFactory#create where the same object should be passed.
So maybe specify it here ?

2022-10-24 07:12 UTC, fredia commented
Hi @klion26, could you please take a review?

2022-10-25 15:15 UTC, klion26 requested changes
Thanks for your contribution, please take a look at the comment inline.

2022-10-26 14:14 UTC, klion26 approved these changes
Thanks for the update, LGTM now, merging

2022-10-26 14:15 UTC, merged

2022-10-27 02:33 UTC, fredia commented
Thanks a lot for reviewing. 👍