[FLINK-29582][state-processor] Relax 1+ operator requirement
apache/flink pull request #21088
Opened 2022-10-17 14:44 UTC by zentol

Based on #21085.

The SavepointWriter previously had to enforce that the user provides at least 1 operator because we used them to get access to the execution environment. No operator -> no environment -> can't setup remaining operations.

This PR adds new factory methods that have the user explicitly pass the environment. With that we can define any operation we like internally without requiring another operator.
The existing factory methods were deprecated. They will continue to work, but it they are used the program is still subject to the old requirement of having at least 1 operator.

2022-10-18 09:52 UTC, zentol commented on flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/SavepointWriterTest.java
> -        env.configure(configuration);
This is an excellent example for why `@Test(expected = ...)` is such a flawed approach. You just don't know where the exception is actually thrown.

2022-10-20 07:28 UTC, alpinegizmo requested changes
The code looks fine. But the State Processor API docs include examples of `newSavepoint` and `fromExistingSavepoint` that should be updated so that they no longer use the deprecated versions.

2022-10-20 10:02 UTC, zentol commented
@alpinegizmo I can't find other usages in the docs. (although I did find a few more in tests/javadocs :sweat_smile: )

2022-10-20 10:09 UTC, alpinegizmo commented
> @alpinegizmo I can't find other usages in the docs. (although I did find a few more in tests/javadocs 😅 )

I was thinking of the references in https://nightlies.apache.org/flink/flink-docs-master/docs/libs/state_processor_api/#writing-new-savepoints and in https://nightlies.apache.org/flink/flink-docs-master/docs/libs/state_processor_api/#modifying-savepoints.  

Somehow I missed that you already updated those. Sorry about the false alarm.

2022-10-20 10:10 UTC, alpinegizmo approved these changes
Looks good now.

2022-10-20 16:25 UTC, zentol commented
@flinkbot run azure

2022-10-20 17:30 UTC, merged