[hotfix] Remove unused private method LocalExecutorITCase#executeAndVerifySinkResult
apache/flink pull request #21103
Opened 2022-10-18 15:53 UTC by snuyanzin

## What is the purpose of the change

There is an unused method `LocalExecutorITCase#executeAndVerifySinkResult` and the PR removes it

## Brief change log

_flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/local/LocalExecutorITCase.java_

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.
## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: ( no)
  - The runtime per-record code paths (performance sensitive): ( no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: ( no)
  - The S3 file system connector: ( no)

## Documentation

  - Does this pull request introduce a new feature? ( no)
  - If yes, how is the feature documented? (not applicable)

2022-10-19 06:49 UTC, XComp approved these changes

2022-10-19 06:52 UTC, XComp requested changes
Removing this method actually makes `verifySinkResult` unused as well. Did you do research on whether this method is actually not used out of accident?

2022-10-19 07:17 UTC, snuyanzin commented
Thanks for looking
good catch
yes you're right
i noticed that removal of `verifySinkResult` also makes `executeSql` unused (removal of `executeSql` does not introduced new unused)

The change that made `executeAndVerifySinkResult` unused done within https://issues.apache.org/jira/browse/FLINK-22540.

I will have a look at other classes touched within that jira issue and update PR accordingly

2022-10-19 16:27 UTC, snuyanzin commented
Also found `CliClient#printWarning`
There are several not used public methods after this commit (not sure if they are required or not, will leave them)
_org.apache.flink.table.client.cli.CliOptionsParser#parseGatewayModeGateway_
_org.apache.flink.table.client.cli.CliOptionsParser#parseGatewayModeClient_
_org.apache.flink.table.client.cli.CliOptionsParser#printHelpGateway_

2022-10-19 20:13 UTC, snuyanzin commented
@flinkbot run azure

2022-10-19 22:26 UTC, snuyanzin commented
@flinkbot run azure

2022-10-20 11:46 UTC, snuyanzin commented
Finally ci passed
about ci failures: 
first attempt failed because of network issue (2 jobs were killed during very long git checkout, about 1.5 hours)
2, 3, 4 failed because of https://issues.apache.org/jira/browse/FLINK-29697, https://issues.apache.org/jira/browse/FLINK-24119

2022-10-21 14:52 UTC, XComp approved these changes
LGTM :+1:

2022-10-25 08:28 UTC, merged