[FLINK-29801] OperatorCoordinator need open the way to operate metric…
apache/flink pull request #21197
Opened 2022-10-31 06:20 UTC by JerryYue-M

…Group interface

## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluster with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

2022-11-03 10:02 UTC, zhuzhurk requested changes
Thanks for opening this PR @JerryYue-M 
I have a few comments. Please take a look.

2022-11-03 10:02 UTC, zhuzhurk commented on flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java
> +        operatorCoordinatorHandler.initializeMetricGroup(jobManagerJobMetricGroup);
Besides that, can we add a test to verify that whether `OperatorCoordinator#registerMetrics(...)` are invoked on all the operator coordinators when a job starts scheduling?

2022-11-03 12:44 UTC, JerryYue-M commented on flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java
> +        operatorCoordinatorHandler.initializeMetricGroup(jobManagerJobMetricGroup);
@zhuzhurk only have one question, there is no metric group in` CreatingExecutionGraph `,when we called `operatorCoordinatorHandler.startAllOperatorCoordinators()` in `handleExecutionGraphCreation` method ,we have nothing to passed

2022-11-04 01:57 UTC, zhuzhurk commented on flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java
> +        operatorCoordinatorHandler.initializeMetricGroup(jobManagerJobMetricGroup);
We can add a method `getJobMetricGroup()` to `CreatingExecutionGraph.Context` and let `AdaptiveScheduler` implement it.

2022-11-04 03:13 UTC, JerryYue-M commented on flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java
> +        operatorCoordinatorHandler.initializeMetricGroup(jobManagerJobMetricGroup);
@zhuzhurk thanks for reply,i found that there no instance or method to help to implement getJobMetricGroup() in  AdaptiveScheduler ,maybe ` return UnregisteredMetricGroups.createUnregisteredJobManagerMetricGroup();
`

2022-11-04 03:49 UTC, zhuzhurk commented on flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java
> +        operatorCoordinatorHandler.initializeMetricGroup(jobManagerJobMetricGroup);
`AdaptiveScheduler` receives the `JobManagerJobMetricGroup` on construction. And that is the group to host the operator coordinator metrics. You can record it in `AdaptiveScheduler` and return it via `AdaptiveScheduler#getJobMetricGroup()`.

2022-11-04 04:01 UTC, zhuzhurk commented on flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java
> +        operatorCoordinatorHandler.initializeMetricGroup(jobManagerJobMetricGroup);
Unregistered metric groups should just be used as placeholder or for testing. Metrics registered to these groups will not be reported.

2022-11-04 05:34 UTC, JerryYue-M commented
@zhuzhurk  all the questions you mentioned had resolved, add  ut to check all the operator coordinators had registered metrics after scheduling, please review it again
thanks a lot

2022-11-07 10:53 UTC, JerryYue-M commented
@zhuzhurk can you review it again, all the discussion had resolved
thanks a lot

2022-11-11 08:38 UTC, zhuzhurk commented on flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinator.java
> +     * Init job manager metric group for current operator coordinator for report metric.
The compilation still fails and looks to me the problem is not resolved.
https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=42878&view=logs&j=52b61abe-a3cc-5bde-cc35-1bbe89bb7df5&t=54421a62-0c80-5aad-3319-094ff69180bb

2022-11-11 08:45 UTC, zhuzhurk commented on flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinator.java
> +     * Init job manager metric group for current operator coordinator for report metric.
The comment is outdated.

2022-11-11 08:47 UTC, zhuzhurk commented on flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinatorHolder.java
> - *
The change is unrelated and it even violated the checkstyle rule.

2022-11-11 09:18 UTC, zhuzhurk reviewed
I have a few more comments. Please take a look.
And it's better to submit a fix commit instead of updating the exiting commit. Because it helps to easier identify why parts are modified.

2022-11-11 09:18 UTC, zhuzhurk commented on flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/OperatorCoordinatorHandler.java
>      void registerAndStartNewCoordinators(
The documentation is not updated.

2022-11-11 09:18 UTC, zhuzhurk commented on flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/OperatorCoordinatorHandler.java
>      /** Start all operator coordinators. */
The documentation is not updated.

2022-11-11 09:18 UTC, zhuzhurk commented on flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinator.java
> +        // do nothing default.
```suggestion
        // do nothing by default
```

2022-11-11 09:18 UTC, zhuzhurk commented on flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/TestingOperatorCoordinator.java
> +       this.metricGroups.add(metricGroup);
```suggestion
      metricGroups.add(metricGroup);
```

2022-11-11 09:18 UTC, zhuzhurk commented on flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/TestingOperatorCoordinator.java
> +   private final List<MetricGroup> metricGroups = new ArrayList<>();
Wrong indentation.
And it should be placed after the `static final` fields.

2022-11-11 09:18 UTC, zhuzhurk commented on flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/DefaultOperatorCoordinatorHandlerTest.java
> +import static org.hamcrest.Matchers.comparesEqualTo;
Looks to me the matcher is introduced without use?

2022-11-11 09:18 UTC, zhuzhurk commented on flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/CreatingExecutionGraphTest.java
> +            final CompletableFuture<Gauge<Long>> numRestartsMetricFuture = new CompletableFuture<>();
You can simply return an `UnregisteredJobManagerJobMetricGroup` for testing.

2022-11-11 09:18 UTC, zhuzhurk commented on flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/DefaultSchedulerTest.java
> +import org.apache.flink.runtime.OperatorIDPair;
These changes are not needed.

2022-11-11 09:18 UTC, zhuzhurk commented on flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/DefaultOperatorCoordinatorHandlerTest.java
> +    private final JobManagerMetricGroup jobManagerMetricGroup =
You can simply return an `UnregisteredJobManagerJobMetricGroup` for testing.
`MetricRegistryImpl` is heavy and must be closed after the testing.

2022-11-11 09:18 UTC, zhuzhurk commented on flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinatorHolderTest.java
> +    private MetricRegistryImpl registry =
You can simply return an `UnregisteredJobManagerJobMetricGroup` for testing.
`MetricRegistryImpl` is heavy and must be closed after the testing.

2022-11-11 09:18 UTC, zhuzhurk commented on flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinatorSchedulerTest.java
> +        assertEquals(1, operatorCoordinatorHolderList.size());
We should use `assertJ` assertions in tests.
See https://flink.apache.org/contributing/code-style-and-quality-common.html#testing.

2022-11-14 07:30 UTC, JerryYue-M commented
@flinkbot  run azure

2022-11-14 10:30 UTC, JerryYue-M commented
@flinkbot run azure

2022-11-15 03:05 UTC, JerryYue-M commented
@flinkbot run azure

2022-11-17 07:46 UTC, JerryYue-M commented
@flinkbot run azure

2022-11-17 07:47 UTC, JerryYue-M commented
@zhuzhurk  
your comments had resolved and no checkstyle and compile problems, can you take a look at those new changes

2022-11-17 11:19 UTC, zhuzhurk commented
Hi @JerryYue-M, I had a discussion with @PatrickRen offline and got quite some feedbacks. The conclusions is that, to better support future operator coordinator metrics, we need a framework-wise design to organize operator coordinator metrics and expose them to users. We need FLIP for the change and a discuss it in the community.
If you are interested, you can work with @ruanhang1993 to do this.
Sorry for the inconvenience! Hopefully the efforts of this PR can be re-used.

cc @wuchong

2022-11-17 11:44 UTC, JerryYue-M commented
@zhuzhurk  thanks for reply  I will take a talk with @arunans23 later

2022-11-17 11:57 UTC, JerryYue-M commented
@zhuzhurk  I checked with https://issues.apache.org/jira/browse/FLINK-21000
some question:
1. this issue is just for the source coordinator, it's not a common way for every implement of operatorcoordinator
2. it takes a long time to merge into the Flink community

2022-11-17 14:03 UTC, zhuzhurk commented
> @zhuzhurk I checked with https://issues.apache.org/jira/browse/FLINK-21000 some question:
> 
> 1. this issue is just for the source coordinator, it's not a common way for every implement of operatorcoordinator
> 2. it takes a long time to merge into the Flink community

> 1. this issue is just for the source coordinator, it's not a common way for every implement of operatorcoordinator
We absolutely need a common way and the solution requires some further thought and discussion

> 2. it takes a long time to merge into the Flink community
I think @ruanhang1993 and @PatrickRen will try to get this improvment done in Flink 1.17.
side note: I guess you `@` a wrong person.

I think the most important thing to design and discuss is the full name pattern of operator coordinator metrics(including the scopes) and how users can access them.

2022-11-19 04:58 UTC, zhuzhurk commented
@ruanhang1993 would you work with @JerryYue-M on the FLIP?

cc @PatrickRen

2022-11-21 03:57 UTC, ruanhang1993 commented
> @ruanhang1993 would you work with @JerryYue-M on the FLIP?
> 
> cc @PatrickRen



> FLIP for the change and a discuss it in the community.

I would love to help. @JerryYue-M , I will create a FLIP about this issue.

2025-04-01 06:29 UTC, closed without merging