[FLINK-30100][checkpointing] Remove the unused CheckpointFailureReason
apache/flink pull request #21353
Opened 2022-11-20 13:48 UTC by 1996fanrui

## What is the purpose of the change

Some CheckpointFailureReasons have not been used for a long time and should be removed. E.g: 

- TOO_MANY_CONCURRENT_CHECKPOINTS
- CHECKPOINT_DECLINED_TASK_NOT_CHECKPOINTING
- CHECKPOINT_DECLINED_ALIGNMENT_LIMIT_EXCEEDED
- JOB_FAILURE

## Brief change log

- The first commit: Remove some unused exceptions and refactor some code of CheckpointCoordinatorTest
- The second commit: Remove deprecated getCheckpointId of PendingCheckpoint
- The third commit: Remove the unused CheckpointFailureReason

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

2022-11-21 12:03 UTC, 1996fanrui commented
Hi @pnowojski please help take a look, thanks. It's also a cleanup PR.

2022-11-23 11:04 UTC, pnowojski requested changes
LGTM % one comment. Thanks for the clean up

2022-11-23 14:05 UTC, 1996fanrui commented on flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTest.java
> -                        .build(graph);
You are right, It's my mistake.  I see this checkpointCoordinator isn't used, so removed it. 

It's covered, and I removed the `CheckpointCoordinator checkpointCoordinator =` due to it's not necessary.

BTW, I did some extra work in this PR during fix this comment.

I migrate checkpoint coordinator related tests to junit5 in the 3rd commit.

2022-11-25 13:12 UTC, pnowojski approved these changes
Thanks for the update, LGTM

2022-11-25 13:12 UTC, merged

2022-11-25 13:33 UTC, 1996fanrui commented
@pnowojski Thanks for your review!