[FLINK-30224][Connectors/Kinesis] An IT test for slow FlinKinesisConsumer's run() which caused an NPE in close
apache/flink pull request #21407
Opened 2022-11-28 10:56 UTC by astamur

[FLINK-30224](https://issues.apache.org/jira/projects/FLINK/issues/FLINK-30224)
- An IT test was added which reproduced this issue;
- Previously the issue itself was fixed in [FLINK-29324](https://issues.apache.org/jira/projects/FLINK/issues/FLINK-29324).

2022-11-28 14:56 UTC, astamur commented
@flinkbot run azure

2022-12-01 11:44 UTC, dannycranmer commented
@flinkbot run azure

2022-12-12 10:33 UTC, dannycranmer commented
@astamur it looks like you did not use the standard PR template, can you please fix the description?

2022-12-12 10:33 UTC, dannycranmer requested changes
see comment

2022-12-12 16:59 UTC, closed without merging

2022-12-12 20:22 UTC, dannycranmer commented
As discussed, please move to flink-connector-aws