[FLINK-30274][pom] Add commons-collections4 to replace commons-collec…
apache/flink pull request #21442
Opened 2022-12-02 08:54 UTC by chucheng92

## What is the purpose of the change

Apache commons-collections 3.x is a Java 1.3 compatible version, and it does not use Java 5 generics. Apache commons-collections4 4.4 is an upgraded version of commons-collections and it built by Java 8.  Because the flink-core use commons-collections 3.x in some old codes, so we currently we can not upgrade it directly. This we add commons-collections4 support first in order to forbid the next and later error usages.

## Brief change log

Add commons-collections4 dependency in managed pom.

## Verifying this change

Just add dependency in managed pom, it will not cause build error.  Verifying by CI process.

## Does this pull request potentially affect one of the following parts:

- Dependencies (does it add or upgrade a dependency): no (managed pom)
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
- The serializers: no
- The runtime per-record code paths (performance sensitive): no
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
- The S3 file system connector: no

## Documentation

- Does this pull request introduce a new feature?  no
- If yes, how is the feature documented? not applicable

2022-12-02 09:06 UTC, MartijnVisser requested changes
This is not a replacement, but just adding collections4 without using it. Where's the value in that? 

I would expect that a replacement also shows the refactoring of the current usage of `commons-collections` to `commons-collections4`.

2022-12-02 09:26 UTC, chucheng92 commented
> This is not a replacement, but just adding collections4 without using it. Where's the value in that?
> 
> I would expect that a replacement also shows the refactoring of the current usage of `commons-collections` to `commons-collections4`.

Add it in dependencyManagement to let the submodules match with this version in later using.

2022-12-02 09:39 UTC, MartijnVisser commented
Again, why would we add a dependency without using it? There's no value in that. Please change current usage of `commons-collections` to `commons-collections4`. Else there's no value in the PR and I'll have to close it.

2022-12-02 10:01 UTC, chucheng92 commented
> Again, why would we add a dependency without using it? There's no value in that. Please change current usage of `commons-collections` to `commons-collections4`. Else there's no value in the PR and I'll have to close it.

Yes. the best solution is replacing it. Can I open a new issue to refactor some old codes to replace it ?

2023-02-08 06:58 UTC, chucheng92 commented
@flinkbot run azure

2023-02-08 07:09 UTC, chucheng92 commented
@flinkbot run azure

2023-02-08 07:10 UTC, chucheng92 commented
@MartijnVisser PTAL, thanks.

2023-02-08 07:26 UTC, chucheng92 commented
@flinkbot run azure

2023-02-08 08:06 UTC, MartijnVisser commented
> @MartijnVisser PTAL, thanks.

@chucheng92 The PR can't pass the CI because it doesn't contain the necessary changes to the NOTICE files (where's there's still an outdated reference to the previous versions of commons-collections and none to the new one).

2023-02-08 08:18 UTC, chucheng92 commented
@MartijnVisser thanks.  Is this caused by updating the commons-collections4? It add some transitive dependencies?

INFO  org.apache.flink.tools.ci.licensecheck.NoticeFileChecker     [] - Problems were detected for a NOTICE file.
	flink-sql-connector-hbase-2.2:
		 These issues are assumed to be false-positives: 
			Dependency com.fasterxml.jackson.core:jackson-core:2.4.0 is not bundled, but listed.
			Dependency com.google.protobuf:protobuf-java:3.7.1 is not bundled, but listed.
			Dependency com.google.code.gson:gson:2.8.5 is not bundled, but listed.
			Dependency com.fasterxml.jackson.core:jackson-databind:2.4.0 is not bundled, but listed.
			Dependency com.fasterxml.jackson.core:jackson-annotations:2.4.0 is not bundled, but listed.
			Dependency org.apache.commons:commons-collections4:4.3 is not bundled, but listed.
			Dependency com.google.protobuf:protobuf-java-util:3.7.1 is not bundled, but listed.
			Dependency commons-logging:commons-logging:1.1.1 is not bundled, but listed.
			Dependency com.google.guava:guava:27.1-jre is not bundled, but listed.
			Dependency com.google.guava:failureaccess:1.0.1 is not bundled, but listed.
			Dependency io.netty:netty-all:4.1.34.Final is not bundled, but listed.
			Dependency commons-cli:commons-cli:1.4 is not bundled, but listed.

Can we add a NOTICE file in flink-core to address this or temporarily we do not do this updating.

2023-02-08 08:21 UTC, MartijnVisser commented
> Is this caused by updating the commons-collections4? 

Yes

> It add some transitive dependencies?

No. Like those lines say `These issues are assumed to be false-positives`. 

The issue lies here https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=45877&view=logs&j=b59e5554-36c7-5512-ab1a-b80b74075fce&t=849d419c-1b8f-52b7-e455-d4bc36ec43ad&l=30273

```
	flink-dist:
		 These issue are legally problematic and MUST be fixed: 
			Dependency org.apache.commons:commons-collections4:4.4 is not listed.
		 These issues are mistakes that aren't legally problematic. They SHOULD be fixed at some point, but we don't have to: 
			Dependency commons-collections:commons-collections:3.2.2 is not bundled, but listed.
```

2023-02-08 08:33 UTC, chucheng92 commented
> > Is this caused by updating the commons-collections4?
> 
> Yes
> 
> > It add some transitive dependencies?
> 
> No. Like those lines say `These issues are assumed to be false-positives`.
> 
> The issue lies here https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=45877&view=logs&j=b59e5554-36c7-5512-ab1a-b80b74075fce&t=849d419c-1b8f-52b7-e455-d4bc36ec43ad&l=30273
> 
> ```
> 	flink-dist:
> 		 These issue are legally problematic and MUST be fixed: 
> 			Dependency org.apache.commons:commons-collections4:4.4 is not listed.
> 		 These issues are mistakes that aren't legally problematic. They SHOULD be fixed at some point, but we don't have to: 
> 			Dependency commons-collections:commons-collections:3.2.2 is not bundled, but listed.
> ```

Can i update the commons-collections3 to commons-collections4 in NOTICE file?

- commons-collections:commons-collections:3.2.2  -> - org.apache.commons:commons-collections4:4.4

Do I just need to update the NOTICE file of the flink-dist module or do I need to update all the places where it appears?

2023-02-08 08:41 UTC, chucheng92 commented
> > Is this caused by updating the commons-collections4?
> 
> Yes
> 
> > It add some transitive dependencies?
> 
> No. Like those lines say `These issues are assumed to be false-positives`.
> 
> The issue lies here https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=45877&view=logs&j=b59e5554-36c7-5512-ab1a-b80b74075fce&t=849d419c-1b8f-52b7-e455-d4bc36ec43ad&l=30273
> 
> ```
> 	flink-dist:
> 		 These issue are legally problematic and MUST be fixed: 
> 			Dependency org.apache.commons:commons-collections4:4.4 is not listed.
> 		 These issues are mistakes that aren't legally problematic. They SHOULD be fixed at some point, but we don't have to: 
> 			Dependency commons-collections:commons-collections:3.2.2 is not bundled, but listed.
> ```

i think i already know how to do it. [PR-21048](https://github.com/apache/flink/pull/21048)  There is similar work done here. thanks.

2023-02-09 05:01 UTC, chucheng92 commented
@flinkbot run azure

2023-02-09 14:40 UTC, chucheng92 commented
@flinkbot run azure

2023-02-09 15:01 UTC, MartijnVisser commented
@chucheng92 You need to rebase your PR on the latest `master`

2023-02-10 07:54 UTC, chucheng92 commented
@MartijnVisser thanks. i rebased it. ci passed. PTAL

2023-02-13 15:07 UTC, MartijnVisser requested changes
@chucheng92 I still see some occurrences of `org.apache.commons.collections`, can we get completely get rid of everything that currently uses collections 3.x?

2023-02-14 05:11 UTC, chucheng92 commented
@MartijnVisser I think we can fix it completely.  i will fix this and update pr ASAP.  Sorry for my mistake. thanks.

2023-02-15 06:18 UTC, chucheng92 commented
![image](https://user-images.githubusercontent.com/11287509/218948092-281c16c7-eafa-41a5-93b6-185cea0330cb.png)

2023-02-15 10:19 UTC, chucheng92 commented
hi. @MartijnVisser i have updated the pr. And i searched the source code and didn't find any other occurs using `org.apache.commons.collections`.  PTAL. thanks.

2023-03-01 09:44 UTC, chucheng92 commented
@MartijnVisser PTAL:)

2023-03-15 05:26 UTC, chucheng92 commented
> hi. @MartijnVisser i have updated the pr. And i searched the source code didn't find any other occurs using `org.apache.commons.collections`. PTAL. thanks.

hi. @MartijnVisser please take a look ?

2023-03-23 21:53 UTC, MartijnVisser reviewed
@chucheng92 I think in general this is looking good, but I would like to wait until https://issues.apache.org/jira/browse/FLINK-30859 is completed, to avoid another round of syncing towards the Flink Kafka connector repo.

2023-03-24 02:25 UTC, chucheng92 commented
@MartijnVisser thanks for explanations. make sense. we will be watching closely about kafka externalization.

2023-06-29 03:10 UTC, chucheng92 commented
@MartijnVisser hi, Martijn, https://issues.apache.org/jira/browse/FLINK-30859 has been resolved. Can you help me to check this pr?

2023-06-29 11:50 UTC, MartijnVisser requested changes
@chucheng92 There are still multiple occurrences of `org.apache.commons.collections` in the codebase; can you double check please?

2023-06-29 12:52 UTC, chucheng92 commented
Hi, Martijn. thanks. it seems like a recent code introduced a old usage. I updated it.

![image](https://github.com/apache/flink/assets/11287509/4dc5e34e-26fd-4a92-80da-a98083d54dc8)

![image](https://github.com/apache/flink/assets/11287509/b44143ef-252b-4436-969f-5cb7f4430ae6)

please check.

2023-06-30 12:24 UTC, MartijnVisser commented
> please check.

The CI is failing for your PR. Please check

2023-06-30 15:02 UTC, chucheng92 commented
@MartijnVisser There is a circular reference.

ci failed becase flink-python kafka test case failed. 

<img width="1014" alt="image" src="https://github.com/apache/flink/assets/11287509/d12b60f4-7ff3-457e-a2c4-8cd415bb5ca2">
<img width="969" alt="image" src="https://github.com/apache/flink/assets/11287509/6b096a4f-83f0-4287-b7ad-d46b9371de4c">


flink-python test case reference flink-sql-connector-kafka. so we need update flink-sql-connector-kafka first. 

The pr is: https://github.com/apache/flink-connector-kafka/pull/37, then this pr can merge, and finally we may remove explicit dependency in flink-connector-kafka. (or keep it remained.)

2023-06-30 15:48 UTC, chucheng92 commented on pom.xml
> -				<groupId>commons-collections</groupId>
@MartijnVisser hi, Martijn. If we can not fix it in flink-connector-kafka, can we solved it in flink here? not replace it, but add a dependency. when flink-connector-kafka update, check and remove it in the future?

2024-05-16 12:30 UTC, AlvaroStream commented
@MartijnVisser or @chucheng92 do you think this will enter in future releases?

Thanks.

2025-04-02 06:25 UTC, closed without merging