[hotfix] Replace deprecated Calcite's APIs
apache/flink pull request #21459
Opened 2022-12-06 15:16 UTC by snuyanzin

## What is the purpose of the change

1. `org.apache.calcite.sql.SqlCharStringLiteral#getNlsString` was made deprecated at
https://github.com/apache/calcite/commit/a1bdba6d79ac05ef227cdb15b7c044c6e0e54dfa#diff-de2027de5bcb4bbe94314c3414b63166ecd9537b437e08d39f6424c0f903c8fbR48
and as suggested in the same place
    ```
    * @deprecated Use {@link #getValueAs getValueAs(NlsString.class)}
    ```
2. `org.apache.calcite.rex.RexSimplify#RexSimplify(RexBuilder, RelOptPredicateList, boolean, RexExecutor)` was made deprecated at https://issues.apache.org/jira/browse/CALCITE-2604
and it is recommended
   ```
   * @deprecated Use methods with a {@link RexUnknownAs} argument, such as
   * {@link #simplify(RexNode, RexUnknownAs)}. */
   ```
3. `org.apache.calcite.rel.core.AggregateCall#create(SqlAggFunction, boolean, boolean, boolean, List<Integer>, int, RelCollation, RelDataType, String)` was made deprecated at https://issues.apache.org/jira/browse/CALCITE-4483
now distinct keys should be specified 
4 `org.apache.calcite.rel.core.Aggregate#Aggregate(RelOptCluster, RelTraitSet, RelNode, ImmutableBitSet, List<ImmutableBitSet>, List<AggregateCall>)` was deprecated at https://issues.apache.org/jira/browse/CALCITE-3723
now hints should be specified

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: ( no )
  - The runtime per-record code paths (performance sensitive): ( no )
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: ( no )
  - The S3 file system connector: ( no)

## Documentation

  - Does this pull request introduce a new feature? ( no)
  - If yes, how is the feature documented? (not applicable)

2022-12-07 16:31 UTC, XComp commented
Created FLINK-30328 to cover the test failure

2022-12-07 16:31 UTC, XComp commented
@flinkbot run azure

2022-12-07 16:56 UTC, XComp requested changes
There are multiple occurrences of deprecated `AggregateCall.create(..)` calls in the code still. 

Additionally, there's a `RexSimplify` implementation in `flink-table/flink-table-planner`. Does this need to be updated as well? I guess, that's not necessary because the goal would be to remove that class and rely on the class provided by Calcite, am I right?

2022-12-08 12:41 UTC, XComp approved these changes
LGTM :+1: It's ready to be merged after CI is successful.

2022-12-08 12:44 UTC, snuyanzin commented
Looks like Idea(or just my set up of it) is kind of weird in finding usages... with help of full-text search I noticed several more missing `AggregateCall#create`
I'm going to push one more commit once this finishes

2022-12-08 12:49 UTC, XComp commented
Yeah, grepping/idea file search is the best way to identify usages for something like that. But all the occurrences of `AggregateCall#create` I found looked legit. I'm curious what you sitll found...

2022-12-08 13:03 UTC, snuyanzin commented
Usages in these classes
`org.apache.flink.table.planner.delegation.hive.HiveParserUtils`
`org.apache.flink.table.planner.calcite.RelTimeIndicatorConverter`
`org.apache.flink.table.planner.plan.rules.logical.FlinkAggregateExpandDistinctAggregatesRule`
`org.apache.flink.table.planner.codegen.MatchCodeGenerator`
`org.apache.flink.table.planner.plan.rules.logical.AggregateReduceGroupingRule`
`org.apache.flink.table.planner.plan.utils.AggregateUtil`
`org.apache.flink.table.planner.plan.metadata.FlinkRelMdHandlerTestBase`
probably could be initially missed because of different args

2022-12-08 14:42 UTC, snuyanzin commented
The failure is related to https://issues.apache.org/jira/browse/FLINK-29755

2022-12-08 18:04 UTC, snuyanzin commented
@flinkbot run azure

2022-12-09 09:09 UTC, merged