[FLINK-30166][Connector/FileSystem] Refactor tests that use the deprecated StreamingFileSink instead of FileSink
apache/flink pull request #21630
Opened 2023-01-09 13:15 UTC by MartijnVisser

Same as https://github.com/apache/flink/pull/21371, except for c4dc109cba59f406f2f1a38ed4e3fdadb62d4970 which now also removes the StreamingFileSink from the E2E tests

2023-01-09 15:43 UTC, XComp commented
@MartijnVisser keep in mind that I reverted all the commits related to FLINK-30166. PR #21371 changed 13 files. This PR only changes 3. I guess, you have to cherry-pick the other commits once more? :thinking:

2023-01-09 16:26 UTC, MartijnVisser commented
> @MartijnVisser keep in mind that I reverted all the commits related to [FLINK-30166](https://issues.apache.org/jira/browse/FLINK-30166). PR #21371 changed 13 files. This PR only changes 3. I guess, you have to cherry-pick the other commits once more? 🤔

Yeah I forgot to revert your reversion ;) I've done that now, while making the commit message a bit more clear 😅

2023-01-10 12:23 UTC, MartijnVisser commented
@flinkbot run azure

2023-01-10 13:23 UTC, XComp commented
What's the plan with the `StreamingFileSink`? Are there follow-up tickets which are not linked with FLINK-30166? I'm just wondering because we're removing tests here for a class that's still present in the codebase. Why don't we remove everything at once?

2023-01-10 21:29 UTC, MartijnVisser commented
> Why don't we remove everything at once?

That was the original idea, but I chatted offline with @JingsongLi and there is work to be done on `FileSystemTableSink` in order to be able to completely remove `StreamingFileSink`. I've created https://issues.apache.org/jira/browse/FLINK-30627 as a follow-up ticket.

2023-01-11 09:42 UTC, XComp requested changes
There are even more occurrences of `StreamingFileSink` in the test source (e.g. `TestStreamingFileSinkFactory`) which are used by some tests. Should we get rid of those as well?

2023-01-12 09:16 UTC, MartijnVisser commented
> Should we get rid of those as well?

We can't yet due to https://issues.apache.org/jira/browse/FLINK-30627

2023-01-12 12:30 UTC, XComp commented
Sorry for being picky on that one. But even with knowing these details, it becomes kind of hard for me to review this PR. There are still code location where I have questions but which are hard to mention in this PR if they are actually not touched as code change. Why do we need to do the cleanup before the refactoring? Can't we wait for the refactoring and clean up everything properly afterwards? Or do we gain anything from cleaning up code partially which I'm not aware of?

Alternatively, if you really want to push for it, it might be more reasonable to ask @JingsongLi for a review or someone more related to whether the partial cleanup is to his liking. WDYT?

2023-01-12 12:32 UTC, MartijnVisser commented
> Alternatively, if you really want to push for it, it might be more reasonable to ask @JingsongLi for a review or someone more related to whether the partial cleanup is to his liking. WDYT?

The original PR (https://github.com/apache/flink/pull/21371) was reviewed and approved by @gaoyunhaii so it might make more sense to ask him :)

2023-02-10 20:39 UTC, MartijnVisser commented
@gaoyunhaii Can you take one more look? You've already reviewed the original PR, which missed one thing that is now addressed in this PR.

2023-06-24 09:56 UTC, gaoyunhaii commented
Very sorry for missing the message, I’lol have a look soon.

2023-06-27 11:46 UTC, MartijnVisser commented
> Very sorry for missing the message, I’ll have a look soon.

Thank you!

2025-04-02 06:26 UTC, closed without merging