[FLINK-30619][tests] Add retry
apache/flink pull request #21751
Opened 2023-01-24 14:20 UTC by zentol

2023-01-24 15:10 UTC, XComp commented
What speaks against replacing the `Thread.sleep(10L)` with a waiting condition in the test?
```
CommonTestUtils.waitUtil(
                () -> upTimeGauge.getValue() > 0L,
                TestingUtils.infiniteDuration(),
                "No non-zero uptime was measured.");
```

2023-01-25 11:01 UTC, zentol commented
We don't know the root cause, but know that the test is quick and the failure rate is low.
A retry should guarantee that this test will no longer fail; not sure if the same can be said about the loop? LMKWYT.

2023-01-25 11:21 UTC, XComp commented
Waiting for the `upTimeGauge` value feels to me like the better approach because we might get the chance of analyzing the thread dump if it really times out forever. :thinking: 
On another note: Did you consider that `taskManagerGateway.waitForSubmissions` is just exceeding its timeout of 5 seconds? `waitForSubmissions` uses `poll` internally which just returns `null` rather than failing in case of reaching the timeout.

2023-01-26 12:34 UTC, zentol commented
I doubt that a thread dump is gonna help us much since we know that the job state was changed from the existing logs.
But in the end waiting for it is a de-facto retry so why not.

2023-01-26 12:39 UTC, XComp requested changes

2023-01-26 12:39 UTC, XComp commented on flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
> +        CommonTestUtils.waitUntilCondition(() -> upTimeGauge.getValue() > 0L);
The `Thread.sleep(10L)` can be removed if we add the waitUntil condition. Additionally, the same pattern with `Thread.sleep` and `isGreatherThan` is applied a few lines further down in the test code. We might want to update that as well.

2023-01-26 12:56 UTC, XComp approved these changes
LGTM :+1:

2023-01-26 15:42 UTC, merged