[FLINK-30974] Add commons-io to flink-sql-connector-hbase
apache/flink pull request #21902
Opened 2023-02-09 06:51 UTC by xicm

## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluster with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

2023-02-09 07:42 UTC, MartijnVisser requested changes
@xicm Please also make sure that you updated the NOTICE file (that's currently failing the CI)

2023-02-09 08:43 UTC, xicm commented
@flinkbot run azure

2023-02-09 09:00 UTC, MartijnVisser commented
@xicm You'll need to rebase your PR to get the latest fixes for the CI

2023-02-09 09:19 UTC, xicm commented
> @xicm You'll need to rebase your PR to get the latest fixes for the CI

Oh, thanks, I rebased the master.

2023-02-09 12:03 UTC, chucheng92 commented
@xicm i think u need to update the NOTICE file like [Martijn](https://github.com/MartijnVisser) suggested.

2023-02-10 01:51 UTC, xicm commented
@MartijnVisser @chucheng92 Thank you for your suggestions. I am new to flink, is it to update this file https://github.com/apache/flink/blob/master/flink-connectors/flink-sql-connector-hbase-2.2/src/main/resources/META-INF/NOTICE

2023-02-10 02:35 UTC, chucheng92 commented
@xicm  good job ! btw, i think u need to modify your commit and PR name like:  

[FLINK-30974][connectors/hbase] Add commons-io to flink-sql-connector-hbase or 
[FLINK-30974][build] Add commons-io to flink-sql-connector-hbase

to add module name.

2025-04-02 06:27 UTC, closed without merging