[FLINK-31161][build] bump versions-maven-plugin to 2.14.2.
apache/flink pull request #21978
Opened 2023-02-21 05:10 UTC by liuyongvs

## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluster with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

2023-02-21 11:52 UTC, zentol requested changes
I don't understand what problem we are solving. Nothing in the ticket indicates an issue with out release scripts.
You are free to use whatever version you'd like in your own setup; what has that got to do with our release scripts?

2023-02-21 13:02 UTC, liuyongvs commented
> I don't understand what problem we are solving. Nothing in the ticket indicates an issue with out release scripts. You are free to use whatever version you'd like in your own setup; what has that got to do with our release scripts?

if user has one project , which is child of flink. we need change parrent version of it. but the version plugin 2.8.1 doesn't support it. so i suggest to upgrade version.

2023-02-21 13:11 UTC, zentol commented
> if user has one project , which is child of flink. we need change parrent version of it. but the version plugin 2.8.1 doesn't support it. so i suggest to upgrade version.

But you use a separate command anyway. What is stopping you from using a different version of the plugin?

2023-02-22 02:02 UTC, liuyongvs commented
> > if user has one project , which is child of flink. we need change parrent version of it. but the version plugin 2.8.1 doesn't support it. so i suggest to upgrade version.
> 
> But you use a separate command anyway. What is stopping you from using a different version of the plugin?

But I think the version should be consistent, and flink as a top-level project show give users a standard example, such as which version of the plugin to use, which has less problems. so i suggest upgrade it.

2023-02-22 12:48 UTC, liuyongvs commented
hi @zentol do you have time to look it again

2023-02-28 09:15 UTC, wangyang0918 commented
Given that `org.codehaus.mojo:versions-maven-plugin:2.8.1` works well for the current Flink release process, I also could not fully understand why we need to bump the version.

2023-03-02 12:27 UTC, liuyongvs commented
after offline discussion with @wangyang0918 , we both think it is in need. @zentol

2023-03-08 11:04 UTC, liuyongvs commented
hi @zentol @wangyang0918 how about it?

2025-04-02 06:27 UTC, closed without merging