[FLINK-31377][table] Fix array_contains ArrayData.ElementGetter shoul…
apache/flink pull request #22143
Opened 2023-03-10 03:08 UTC by liuyongvs

## What is the purpose of the change

*Fix array_contains ArrayData.ElementGetter should use element type instead of needle type.*

- needle and element type are identical. because " a NOT NULL type can be stored in NULL type but not vice versa." and after dig the code TypeInferenceOperandChecker.insertImplicitCasts, you can see here supportsAvoidingCast.

`
// code placeholder
Stream<TestSetSpec> getTestSetSpecs() {
    return Stream.of(
            TestSetSpec.forFunction(BuiltInFunctionDefinitions.ARRAY_CONTAINS)
                    .onFieldsWithData(
                            new Map[] {
                                null,
                                CollectionUtil.map(entry(1, "a"), entry(2, "b")),
                                CollectionUtil.map(entry(3, "c"), entry(4, "d")),
                            },
                            null)
                    .andDataTypes(
                            DataTypes.ARRAY(DataTypes.MAP(DataTypes.INT(), DataTypes.STRING())),
                            DataTypes.STRING())
                    .testResult(
                            $("f0").arrayContains(
                                            CollectionUtil.map(entry(3, "c"), entry(4, "d"))),
                            "ARRAY_CONTAINS(f0, MAP[3, 'c', 4, 'd'])",
                            true,
                            DataTypes.BOOLEAN()));
}
`

## Verifying this change
- add unit test

## Does this pull request potentially affect one of the following parts
- Dependencies (does it add or upgrade a dependency): no
- The public API, i.e., is any changed class annotated with @Public(Evolving): yes
- The serializers: no
- The runtime per-record code paths (performance sensitive): no
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing
- Kubernetes/Yarn/Mesos, ZooKeeper: no
- The S3 file system connector: no

## Documentation
- Does this pull request introduce a new feature? yes
- If yes, how is the feature documented? docs / JavaDocs

2023-06-09 04:19 UTC, liuyongvs commented
hi @luoyuxia will you have time to review it?

2023-06-09 05:50 UTC, snuyanzin requested changes
@liuyongvs can you please provide a SQL test for this issue since it is not clear what SQL does not work here?

2023-06-09 07:41 UTC, liuyongvs commented
and that is why i add this test, it should contains the null elements, when it throw exception
```
new Map[] {
                                    null,
                                    CollectionUtil.map(entry(1, "a"), entry(2, "b")),
                                    CollectionUtil.map(entry(3, "c"), entry(4, "d")),
                                }
```

2023-06-09 08:03 UTC, snuyanzin commented
@liuyongvs thanks for your response

I tried to do it with datagen (since recently it supports `null-rate`), so I tried this
```sql
CREATE TABLE t (
     a BIGINT,
     b ARRAY<MAP<INT, STRING>>
 ) WITH (  
   'connector' = 'datagen',
   'fields.a.null-rate' = '0.5',
   'fields.b.null-rate' = '0.5',
   'fields.b.element.null-rate' = '0.5'
 );

```
and then this query (you've mentioned)
```sql
 SELECT a, b, ARRAY_CONTAINS(b, MAP[1, 'a']) FROM t;
```
for about 5 min I was not able to get any exception...


About test in the PR:
I'm a bit skeptic about it because it explicitly sets entry of map to `NULL`. What functionality allows to that?
I do not remember any SQL function allowing to do that. Key and value yes however not the whole entry

2023-06-09 08:16 UTC, snuyanzin commented
That's why is table definition there are both
```
...
'fields.b.null-rate' = '0.5',
'fields.b.element.null-rate' = '0.5'
...
```

2023-06-09 09:39 UTC, liuyongvs commented
@snuyanzin i debug it, the sql way you offers, it is GenericRowData,
 
![image](https://github.com/apache/flink/assets/6316753/834634ee-2a98-4d4e-9940-4a3151d78416)

while unit test  in local debug  it is BinaryRowData,that is why your example  not throw exception

![image](https://github.com/apache/flink/assets/6316753/887111f6-4576-4c89-93d0-d22b268be45e)

2023-06-09 10:33 UTC, snuyanzin reviewed
Thanks for your response

the only way I was able to get some failure is
```sql
SELECT array_contains(array[null, map[1, 'a']], map[1, 'a']);
```
which is https://issues.apache.org/jira/browse/FLINK-27438

May be current PR for https://issues.apache.org/jira/browse/FLINK-27438 does not cover your case I would suggest to add this test case to https://issues.apache.org/jira/browse/FLINK-27438.

Since it's better to fix all the related issues especially when test cases are very similar

2023-06-09 10:56 UTC, liuyongvs commented
@snuyanzin but it is a different problem. that is to say, there are 2 problem.  this https://issues.apache.org/jira/browse/FLINK-27438 i reported before in the issue. so i think we should fix the first one . then fix https://issues.apache.org/jira/browse/FLINK-27438
what do you think?

2023-06-09 11:04 UTC, snuyanzin commented
Well i don't see a good reason to fix something that could be checked only via artifitial test-case and at the same time keep not working on SQL level...
In my opinion it's better to have both working or both not-working

2023-06-09 11:10 UTC, liuyongvs commented
@snuyanzin Ha ha, may we fix one thing in one pr in the software development principal. just my personal think.

2023-06-09 11:18 UTC, snuyanzin commented
i try to have a look from user point of view:
now it does not work both via api and SQL
imagine after fixing this it will work via API however not via SQL and that introducies  inconcistency in behavior

2023-06-09 11:40 UTC, liuyongvs commented
@snuyanzin 
1) first, this https://issues.apache.org/jira/browse/FLINK-27438  is long time, and don't have any progress. 
2) from my side. this is 2 different problem indeed. we need to fix bugs try out bese.

2023-06-09 12:50 UTC, liuyongvs commented
@snuyanzin one more thing
1.  It is bug array_contains
2. the issues https://issues.apache.org/jira/browse/FLINK-27438 is about array[map].  Totally different problem, why we also put them together to taklk

2023-06-12 06:50 UTC, liuyongvs commented
@snuyanzin another example:
if user use it like this, the b column is a udx or a builtin function, which using BinayArrayData. it will also throw exception
```
SELECT array_contains(b, map[1, 'a']);
```

2023-06-15 11:23 UTC, liuyongvs commented
hi @snuyanzin do you have time to have a look again?

2025-04-02 06:28 UTC, closed without merging