[FLINK-31444][runtime]FineGrainedSlotManager reclaims slots when job is finished
apache/flink pull request #22183
Opened 2023-03-15 07:22 UTC by huwh

## What is the purpose of the change
When a job shuts down there is a race condition between slots being freed and requirements being set to 0. If the slot release arrives first at the RM then it will immediately try to re-allocate slots, since the requirements are not 0 yet.

This change try to free all inactive slots in task executor when job finished(clear requirements). 

## Verifying this change
  - *Added unit test testReclaimInactiveSlotsOnClearRequirements to verify reclaim only invoked on clear requirements*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation
  - Does this pull request introduce a new feature?(no)

2023-03-20 09:12 UTC, reswqa reviewed
Thanks @huwh for porting this feature to `FineGrainedSlotManager`, this change looks good to me overall, I only left a minor comments, PTAL.

2023-03-23 07:14 UTC, xintongsong requested changes

2023-03-23 07:14 UTC, xintongsong commented on flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/DefaultSlotStatusSyncer.java
> +    }
Shall we eagerly notify the task manager tracker and resource tracker about the freeing of the slots? Or we rely on task managers to report the slots becoming available later to keep the states consistent? I personally lean towards eagerly sync the status. Either way, it should be documented.

2023-03-23 09:35 UTC, huwh commented
@xintongsong thanks, comments addressed. PTAL

2023-03-24 07:25 UTC, xintongsong commented
@flinkbot run azure

2023-03-24 08:26 UTC, xintongsong approved these changes
LGTM. Merging this.

2023-03-24 08:29 UTC, closed without merging