[FLINK-31617] Upgrade the SnakeYaml Maven dependency
apache/flink pull request #22274
Opened 2023-03-26 12:40 UTC by yangjf2019

## What is the purpose of the change

*Upgrade the SnakeYaml Maven dependency from 1.33 to 2.0 to fix the container vulnerability [CVE-2022-1471](https://github.com/advisories/GHSA-mjmj-j48q-9wg2)*

## Brief change log
I modified some files in the project.
  - *Upgrade SnakeYaml version from 1.33 to 2.0.*
  - *Updated the SnakeYaml Maven dependency in the pom.xml.*
  - *Updated the "flink-kubernetes/src/main/resources/META-INF/NOTICE" file in the project.*

## Verifying this change
This change is a just maven dependency update doesn't make impact.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
Hi,  @wuchong please take a look in your free time,thank you very much!

2023-03-30 09:07 UTC, MartijnVisser requested changes
@yangjf2019 Please fix the CI, Snakeyaml 2.0 has backward incompatible changes so you'll need to fix the Flink code too

2023-04-03 06:08 UTC, yangjf2019 commented
@MartijnVisser Thanks for your review,  and i will update as soon as possible.

2023-04-04 08:20 UTC, yangjf2019 commented
@MartijnVisser I think we should upgrade `snakeyaml` and `kubernetes.client` at the same time, don't you think?The new version solves the compatibility problem.

2023-04-05 12:07 UTC, yangjf2019 commented
I will fix it.

2023-04-07 01:18 UTC, yangjf2019 commented
@flinkbot run azure

2023-04-14 12:34 UTC, MartijnVisser requested changes
@yangjf2019 Do these changes need to happen at the same time? I would prefer separate Jira tickets for them, since they don't seem related. Also, please have a look at the naming conventions for commits at https://flink.apache.org/how-to-contribute/code-style-and-quality-pull-requests/#4-commit-naming-conventions

2023-04-16 13:04 UTC, yangjf2019 commented
Okay, I'll take care of it as soon as possible.

2023-04-18 02:16 UTC, closed without merging