[FLINK-32225][Runtime] Executions in same Job use a shared TaskDeploymentDescriptorFactory.
apache/flink pull request #22686
Opened 2023-05-31 14:11 UTC by huwh

## What is the purpose of the change

TaskDeploymentDescriptorFactory#fromExecution needs to retrieve several fields from the ExecutionGraphAccessor. We could introduce a new TaskDeploymentDescriptorHelper to merge all these fields to make the ExecutionGraph/TaskDeploymentDescriptor more readable.

## Brief change log
  - *Merge all task deployment related fields to TaskDeploymentDescriptorHelper*

## Verifying this change

This change is code refactoring without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)

2023-06-02 06:09 UTC, huwh commented
@Thesharing @reswqa, could you please take a look at this PR?

2023-06-02 06:49 UTC, reswqa commented
Thanks for inviting me, also cc @wanglijie95.

2023-06-08 07:52 UTC, wanglijie95 commented
Thanks @huwh for creating this PR. I have a different idea:

We can create the `TaskDeploymentDescriptorFactory` outside ExecutionGraph and pass it in through the ctor. The`TaskDeploymentDescriptorFactory` provides a `createDeploymentDescriptor(Execution execution, ...)` method to create the deployment descriptor for an execution. 

In this way, the job/graph level configurations such as `partitionLocationConstraint` and `nonFinishedHybridPartitionShouldBeUnknown` should be passed into the `TaskDeploymentDescriptorFactory` instead of `ExecutionGraph`.

WDYT ? @Thesharing @reswqa

2023-06-08 08:20 UTC, Thesharing commented
> Thanks @huwh for creating this PR. I have a different idea:
> 
> We can create the `TaskDeploymentDescriptorFactory` outside ExecutionGraph and pass it in through the ctor of ExecutionGraph. The`TaskDeploymentDescriptorFactory` provides a `createDeploymentDescriptor(Execution execution, ...)` method to create the deployment descriptor for an execution.
> 
> In this way, the job/graph level configurations such as `partitionLocationConstraint` and `nonFinishedHybridPartitionShouldBeUnknown` should be passed into the `TaskDeploymentDescriptorFactory` instead of `ExecutionGraph`.
> 
> WDYT ? @Thesharing @reswqa

It's a great idea. Currently `TaskDeploymentDescriptorFactory` is created for each execution. But it involves several job-level configurations. This is a bit confusing.

However, this change would introduce a lot of code changes. Maybe we'll need a small design doc to show the scope affected by this refactoring job.

2023-06-08 09:29 UTC, wanglijie95 commented
@Thesharing I had a quick look, and found that the ctor and `createDeploymentDescriptor` are only used in 2 places: `Execution` and `TaskDeploymentDescriptorFactoryTest`, it seems the code changes are not quite complicated. Can you help to confirm it @huwh , thanks.

2023-06-08 10:09 UTC, Thesharing commented
> @Thesharing I had a quick look, and found that the ctor and `createDeploymentDescriptor` are only used in 2 places: `Execution` and `TaskDeploymentDescriptorFactoryTest`, it seems the code changes are not quite complicated. Can you help to confirm it @huwh , thanks.

Yes, I overcomplicate this. Thank you for pointing this out. Aside from the initialization of `TaskDeploymentDescriptorFactory`, the remaining code changes are acceptable.

2023-06-08 12:42 UTC, huwh commented
Thanks @wanglijie95 and @Thesharing  for the analysis. 

After making a quick code changes, I think it makes sense to change TaskDeploymentDescriptorFactory to Job Level, so it only contains job level immutable configurations. We create the TaskDeploymentDescriptorFactory in the DefaultExecutionGraphBuilder and pass it to the ExecutionGraph. Executions can use TaskDeploymentDescriptorFactory#createDeploymentDescriptor(Execution execution, ...) to create the DeploymentDescriptor, and in this method, we can put all execution-level configurations, such as InputGateDeploymentDescriptors, into the DeploymentDescriptor.

I will take more tests to confirm this.

2023-06-12 09:42 UTC, wanglijie95 requested changes
Thanks for update @huwh. I left some comments, PTAL. And the CI failed due to FLINK-32294, please rebase your code.

2023-06-12 09:42 UTC, wanglijie95 commented on flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraph.java
> +
Add `@Override`

2023-06-12 09:42 UTC, wanglijie95 commented on flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraphBuilder.java
> +            TaskDeploymentDescriptorFactory taskDeploymentDescriptorFactory =
I think it would be better to add a separate try catch block, because the exception message of current block is "Could not create the ExecutionGraph"

2023-06-12 09:42 UTC, wanglijie95 commented on flink-runtime/src/main/java/org/apache/flink/runtime/deployment/TaskDeploymentDescriptorFactory.java
> +            for (Map.Entry<IntermediateDataSetID, ShuffleDescriptorAndIndex[]> entry :
I prefer to keep the same logic as before, only put `getClusterPartitionShuffleDescriptors` in try catch block.

2023-06-14 02:55 UTC, huwh commented
Thanks for your review, @wanglijie95 . comments addressed. Please take a look.

Since only "BlobWriter.serializeAndTryOffload" will throw an IOException, I'd like to remove the try catch of creating the DefaultExecutionGraph after adding a separate try catch block to create TaskDeploymentDescriptorFactory.

2023-06-14 03:31 UTC, wanglijie95 approved these changes
LGTM. I have last 2 minor comments. @reswqa @Thesharing Would you like to have a look?

2023-06-14 03:31 UTC, wanglijie95 commented on flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraph.java
> +        this.taskDeploymentDescriptorFactory = taskDeploymentDescriptorFactory;
maybe add `checkNotNull`

2023-06-14 03:31 UTC, wanglijie95 commented on flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraphBuilder.java
> +        executionGraph =
This 2 lines can be merged into 1.

2023-06-14 04:19 UTC, huwh commented
Thanks a lot, comments addressed and fixup commit squashed.

2023-06-15 05:58 UTC, huwh commented
@Thesharing, do you have any recommendations or concerns?  I'd like to merge this so I can continue working on https://github.com/apache/flink/pull/22674.

2023-06-15 06:10 UTC, reswqa approved these changes
Thanks for doing this refactoring, good job! +1 for merging.

2023-06-15 06:52 UTC, closed without merging