[FLINK-30217] Replace ListState#clear along with following #add with a ListState#update
apache/flink pull request #23344
Opened 2023-08-31 17:19 UTC by Zakelly

## What is the purpose of the change

This PR replace ListState#clear along with following ListState#add with a ListState#update, which reduces the state access overhead for KeyedState and normalize the function calls for updating a ListState.

## Brief change log

Found the ListState#clear along with following ListState#add everywhere and did an equivalent replacement for these function calls. I tried my best to do the replacement and there may be omissions.

## Verifying this change

This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / don't know)
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

2023-09-01 02:17 UTC, Zakelly commented
@masteryhx Would you please take a look? Thanks a lot!

2023-09-01 04:30 UTC, masteryhx requested changes
Thanks for the pr.
Existing changes LGTM, besides these, I think we could also update:
1. Doc about operator state example: https://nightlies.apache.org/flink/flink-docs-release-1.17/docs/dev/datastream/fault-tolerance/state/#using-operator-state， see BufferingSink#snapshotState and CounterSource#snapshotState, that many users may learn from.
2. the case of "clear() + addAll()" which could also be replaced.  I saw many examples, e.g. CollectSinkFunction#snapshotState. Of Course, I think we could modify them in a seprate commit.

2023-09-01 09:08 UTC, Zakelly commented
@flinkbot run azure

2023-09-07 08:29 UTC, masteryhx requested changes
Thanks for the update, PTAL my comments.
BTW, `SavepointWriterITCase#StatefulOperator `could also be updated.

2023-09-07 08:29 UTC, masteryhx commented on flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/SavepointReaderITTestBase.java
>              unionState.addAll(elements);
```suggestion
            unionState.update(elements);
```

2023-09-07 08:29 UTC, masteryhx commented on flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/sort/StreamSortOperator.java
>          // batch put
```suggestion
        // batch update
```

2023-09-08 02:49 UTC, Zakelly commented
@masteryhx Good catch! Many thanks!

2023-09-08 04:13 UTC, masteryhx approved these changes
Thanks for the update, LGTM.

2023-09-08 04:18 UTC, closed without merging