[FLINK-33121] Failed precondition in JobExceptionsHandler due to concurrent global failures
apache/flink pull request #23440
Opened 2023-09-20 05:56 UTC by pgaref

## What is the purpose of the change

https://issues.apache.org/jira/browse/FLINK-33121

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluster with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

2023-10-24 00:54 UTC, pgaref commented
> I'm against making this change without a clear explanation as to when this case occurs. AFAICT we don't intend for it to occur, so let's find that bug rather than allowing it and potentially causing other downstream side-effects.

Found the root cause of this, @zentol / @dmvk  can you please take another look?

2023-10-24 11:54 UTC, dmvk requested changes
The reasoning reads sane 👍 I have few questions
1. Would it be possible to introduce a test that simulates the original issue?
2. What about `testExceptionHistoryWithTaskConcurrentGlobalFailure`, which is failing? 
  a. It suggests multiple global failures can occur. Is that even correct?
  b. If correct, wouldn't that manifest into the same problem? (we can only have one root I assume)
3. Is the wrong ordering a regression caused by failure enrichment?

2023-10-24 21:09 UTC, pgaref commented
Hey @dmvk  -- thanks for the comments!

1. Was debating about that, however testing e2e would require to add the mocked AdaptiveScheduler dependency (like `ExceptionHistoryTester`) to JobExceptionsHandlerTest -- that even though is possible, would add more complexity than value IMO as we just need to ensure the order of entries for the conversion is correct (similar to what we do in the AdaptiveSchedulerTest in the PR)
2. Regarding `testExceptionHistoryWithTaskConcurrentGlobalFailure`, two concurrent Global failures could never occur with the current logic in the AdaptiveScheduler -- so I modified the test to represent reality and include our case too
3. This issue is not related to failure enrichment at all -- it is just not too common as there should be one or more concurrent Task/Local failures followed by a Global one

2023-10-26 16:09 UTC, dmvk commented on flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
>      void testExceptionHistoryWithTaskConcurrentGlobalFailure() throws Exception {
is the test name still matching what's happening in the test?

2024-03-22 08:17 UTC, zentol requested changes
I suppose this can work but it seems rather brittle and may obfuscate the underlying failure cause.
If the reality is that multiple global failures can occur then the exception history should simply support that. The old stack got around this by just throwing away older global failures if a new one occurred, which isn't great either.

This might be the opportunity to properly fix this. In the old days (pre source coordinators) this wasn't as pressing because global failures were rare and only triggered by the JM (which typically ensured it only happened once), but since this has changed now we should adjust accordingly.

2024-03-22 08:17 UTC, zentol commented on flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StateWithExecutionGraph.java
> +        if (this.getJob().getState() != JobStatus.RESTARTING) {
Override `handleGlobalFailure` in `Restarting` instead.

2024-03-22 08:17 UTC, zentol commented on flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/exceptionhistory/RootExceptionHistoryEntry.java
> +                entry.getFailingTaskName(),
seems unrelated?

2024-03-22 08:17 UTC, zentol commented on flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StateWithExecutionGraph.java
> +        if (this.getJob().getState() != JobStatus.RESTARTING) {
While less common this problem can also occur for `Canceling` and `Failing`.

2024-03-25 05:30 UTC, pgaref commented
> I suppose this can work but it seems rather brittle and may obfuscate the underlying failure cause. If the reality is that multiple global failures can occur or that global failures can occur after task failures then the exception history should simply support that. The old stack got around this by just throwing away older global failures if a new one occurred, which isn't great either.
> 
> This might be the opportunity to properly fix this. In the old days (pre source coordinators) this wasn't as pressing because global failures were rare and only triggered by the JM (which typically ensured it only happened once), but since this has changed now we should adjust accordingly.

Thanks @zentol  ! Opened https://issues.apache.org/jira/browse/FLINK-34922 to address properly supporting multiple Global failures in the Exception History.

Also changed this PR to ignore Global failures while being in a Restarting/Canceling or Failing phase on the Adaptive scheduler -- let me know what you think

2024-03-28 15:11 UTC, closed without merging