[FLINK-33235][doc] Update OLAP QuickStart doc and translate to Chinese
apache/flink pull request #23523
Opened 2023-10-14 13:36 UTC by xiangyuf

## What is the purpose of the change

Update Flink OLAP quickstart and translate to Chinese

## Brief change log

- Follow the [documentation style guide](https://flink.apache.org/how-to-contribute/documentation-style-guide/) use 'active voice' and 'you' instead of 'passive voice' and 'we' in the doc
- Add architecture diagram in the doc
- Fix typos and misconfigured options in the doc
- Translate to Chinese

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no

2023-10-14 17:38 UTC, xiangyuf commented
@flinkbot run azure

2023-10-14 17:48 UTC, xiangyuf commented
@flinkbot run azure

2023-10-14 18:07 UTC, xiangyuf commented
@flinkbot run azure

2023-10-14 18:09 UTC, xiangyuf commented
@flinkbot run azure

2023-10-14 22:47 UTC, xiangyuf commented
@KarmaGYZ @FangYongs Hi, can you help review this when you have time?

2023-10-31 13:03 UTC, xiangyuf commented
@flinkbot run azure

2023-11-01 06:55 UTC, KarmaGYZ requested changes

2023-11-01 06:55 UTC, KarmaGYZ commented on docs/content.zh/docs/dev/table/olap_quickstart.md
> +Flink JDBC Driver 提供了底层的连接管理能力，方便用户使用并向 SQL Gateway 提交查询请求。在实际的生产使用中，用户需要注意如何复用 JDBC 连接，来避免 Gateway 频繁的执行 Session 相关的创建及关闭操作，从而减少端到端的作业耗时。详细信息可以参考文档 [Flink JDBC Driver]({{{<ref "docs/dev/table/jdbcDr
broken link.

2023-11-01 06:55 UTC, KarmaGYZ commented on docs/content.zh/docs/dev/table/olap_quickstart.md
> +Flink JDBC Driver 提供了底层的连接管理能力，方便用户使用并向 SQL Gateway 提交查询请求。在实际的生产使用中，用户需要注意如何复用 JDBC 连接，来避免 Gateway 频繁的执行 Session 相关的创建及关闭操作，从而减少端到端的作业耗时。详细信息可以参考文档 [Flink JDBC Driver]({{{<ref "docs/dev/table/jdbcDr
broken in english version.

2023-11-01 06:55 UTC, KarmaGYZ commented on docs/content.zh/docs/dev/table/olap_quickstart.md
> +* **客户端**: 可以是任何可以和 Flink SQL Gateway 交互的客户端，包括：SQL Client，Flink JDBC Driver 等等；
Add links for them.

2023-11-01 06:55 UTC, KarmaGYZ commented on docs/content.zh/docs/dev/table/olap_quickstart.md
> +* **Flink SQL Gateway**: Flink SQL Gateway 服务主要用作 SQL 解析、元数据获取、统计信息分析、Plan 优化和集群作业提交；
ditto.

2023-11-01 06:55 UTC, KarmaGYZ commented on docs/content.zh/docs/dev/table/olap_quickstart.md
> +* **Flink Session Cluster**: OLAP 查询建议运行在 Session 集群上，主要是可以减少集群启动时的额外开销；
ditto for session cluster.

2023-11-01 06:55 UTC, KarmaGYZ commented on docs/content/docs/dev/table/olap_quickstart.md
> +  * Flink OLAP runs naturally as an MPP(Massively Parallel Processing) system, which enables planners to easily adjust the job parallelism to fulfill queries' latency requirement under different data
Remove the MPP phrase.

2023-11-01 06:55 UTC, KarmaGYZ commented on docs/content.zh/docs/dev/table/olap_quickstart.md
> +这里的方法和[本地安装]({{< ref "docs/try-flink/local_installation" >}})中记录的步骤类似。Flink 可以运行在任何类 UNIX 的操作系统下面, 例如：Linux, Mac OS X 和 Cygwin (for Windows)。你需要在本地安装好 __Java 11__，可以通过下述命令行的方式检查安装好的 Java 版本：
We recommend user to use JDK 17 below.

2023-11-01 11:43 UTC, KarmaGYZ approved these changes

2023-11-02 02:14 UTC, merged