[FLINK-33434][runtime-web] Support invoke async-profiler on TaskManager via REST API
apache/flink pull request #24041
Opened 2024-01-08 05:26 UTC by yuchen-ecnu

## What is the purpose of the change

This is a subtask of [FLIP-375](https://cwiki.apache.org/confluence/x/64lEE), which introduces the async-profiler for profiling Jobmanager. 

## Brief change log
- Generalized file upload from TaskManager to support different `FileType` uploading (different `fileType` could have different `baseDir`)
- Introduce APIs for Creating Profiling Instances / Downloading Profiling Results / Retrieving Profiling List on TaskManager
- Provide a web page for profiling TaskManager on  Flink WEB

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): **no** 
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: **no**
  - The serializers: **no** 
  - The runtime per-record code paths (performance sensitive): **no** 
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: **no** 
  - The S3 file system connector: **no**

## Documentation

  - Does this pull request introduce a new feature? **yes**
  - If yes, how is the feature documented? not documented, it will be added in [FLINK-33436](https://issues.apache.org/jira/browse/FLINK-33436)

2024-01-08 05:28 UTC, yuchen-ecnu commented
Hi @Myasuka , do you have time to help review this PR?

2024-01-14 09:12 UTC, Myasuka reviewed
Thanks for creating this PR, I think this already looks in good shape. 

I think the first two commits could be combined as one. And we can also introduce another hotfix to add more logs for test case debug.

2024-01-14 09:12 UTC, Myasuka commented on flink-runtime-web/web-dashboard/src/app/pages/task-manager/profiler/task-manager-profiler.component.html
> +      nzMessage="You need to set the config `rest.profiler.enabled=true` to enable this experimental profiler feature."
The hint is correct with current implementation, and we shall use yaml-like hint `rest.profiling.enabled: true`.

The `job-manager-profiler.component.html` should also be changed.

2024-01-15 14:48 UTC, Myasuka requested changes
Thanks for the quick fix. We don't need to refactor the deprecated interfaces, and you might forget to change some classes. PTAL.

2024-01-15 14:48 UTC, Myasuka commented on flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManagerGateway.java
> +            ResourceID taskManagerId, String fileName, @RpcTimeout Duration timeout);
We do not need to change the class from `Time` to `Duration` for a deprecated interface.

2024-01-15 14:48 UTC, Myasuka commented on flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/taskmanager/TaskManagerProfilingFileHandler.java
> +public class TaskManagerProfilingFileHandler
It seems you forget to change this class.

2024-01-16 11:16 UTC, yuchen-ecnu commented
Hi @Myasuka , I have reverted the changes of the deprecated function `requestTaskManagerFileUploadByName`. But in the `TaskManagerProfilingFileHandler`, the `Time timeout` was used by the base class `LeaderRetrievalHandler`.  And it was used by almost all handlers, so I think maybe we can replace that in a separate PR in the future.

2024-01-17 14:11 UTC, yuchen-ecnu commented
Hi @Myasuka , I have added two more tests for `TaskManagerProfilingHandler` and `TaskManagerProfilingListHandler`.

2024-01-18 04:48 UTC, yuchen-ecnu commented
@flinkbot run azure

2024-01-18 12:25 UTC, merged