[FLINK-34522][core] Changing the Time to Duration for StateTtlConfig.Builder.cleanupInRocksdbCompactFilter
apache/flink pull request #24417
Opened 2024-03-01 02:00 UTC by RocMarshal

- What is the purpose of the change
[FLINK-32570](https://issues.apache.org/jira/browse/FLINK-32570) deprecated the Time class and refactor all Public or PublicEvolving apis to use the Java's Duration.

StateTtlConfig.Builder#cleanupInRocksdbCompactFilter is still using the Time class. In general, we expect:

Mark cleanupInRocksdbCompactFilter(long, Time) as @Deprecated
Provide a new cleanupInRocksdbCompactFilter(long, Duration)
But I found this method is introduced in 1.19 ([FLINK-30854](https://issues.apache.org/jira/browse/FLINK-30854)), so a better solution may be: only provide cleanupInRocksdbCompactFilter(long, Duration) and don't use Time.

The deprecated Api should be keep for 2 minor version. IIUC, we cannot remove Time related class in Flink 2.0 if we don't deprecate it in 1.19. If so, I think it's better to merge this JIRA in 1.19.0 as well.

- Brief change log
[[FLINK-34522](https://issues.apache.org/jira/browse/FLINK-34522)][core] Changing the Time to Duration for StateTtlConfig.Builder.cleanupInRocksdbCompactFilter

Fix based on https://github.com/apache/flink/pull/24388   & https://github.com/apache/flink/pull/24387#issuecomment-1971427877

2024-03-01 04:06 UTC, HuangXingBo commented on flink-python/pyflink/datastream/state.py
> +                periodic_compaction_time=Duration.of_days(30)) -> \
`Duration.of_days(30)` -> None

2024-03-01 04:06 UTC, HuangXingBo commented on flink-python/pyflink/datastream/state.py
> +                         periodic_compaction_time=Duration.of_days(30)):
`Duration.of_days(30)-> None` and do the similar thing to `cleanup_in_rocksdb_compact_filter`

2024-03-01 07:42 UTC, 1996fanrui approved these changes
I saw the python ci has passed, thanks a lot @HuangXingBo for the debug and suggestion, and thanks @RocMarshal for the fix!

LGTM

cc @XComp

2024-03-01 09:10 UTC, Myasuka requested changes
Thanks for creating this PR, please correct the `import` examples in the docs.

2024-03-01 09:10 UTC, Myasuka commented on docs/content/docs/dev/datastream/fault-tolerance/state.md
>  from pyflink.common.time import Time
As we use new interface of `Duration`, we don't need this `import` anymore.

2024-03-01 09:10 UTC, Myasuka commented on docs/content/docs/dev/datastream/fault-tolerance/state.md
>  import org.apache.flink.api.common.time.Time;
We don't need this import anymore.

2024-03-01 09:40 UTC, 1996fanrui commented
> Thanks for creating this PR, please correct the `import` examples in the docs.

Thanks @Myasuka for the review!

The Time is still used for ttl config and Time is not deprecated in python api in 1.19, that's why I didn't remove this import in this PR. 

https://github.com/apache/flink/pull/24387#issuecomment-1966071598 also mentions this issue, FLINK-34527 will deprecate it.

2024-03-02 04:38 UTC, Myasuka approved these changes
Thanks for @1996fanrui 's correction, LGTM.

2024-03-02 04:41 UTC, merged