[FLINK-25544][streaming][JUnit5 Migration] The runtime package of module flink-stream-java
apache/flink pull request #24483
Opened 2024-03-11 14:42 UTC by Jiabao-Sun

## What is the purpose of the change

[FLINK-25544][streaming][JUnit5 Migration] The runtime package of module flink-stream-java

## Brief change log

[JUnit5 Migration] The runtime package of module flink-stream-java

## Verifying this change

This change is already covered by existing tests.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not documented)

2024-03-12 02:07 UTC, Jiabao-Sun commented
Hi @ferenc-csaky, @GOODBOY008.
Could you help review this when you have time?
This is the last PR of flink-stream-java module.

2024-03-12 03:45 UTC, Jiabao-Sun commented
Tests count verified.

master
Tests      run: 2353, Failures: 0, Errors: 0, Skipped: 132
IT Tests   run: 64, Failures: 0, Errors: 0, Skipped: 0

PR
Tests      run: 2353, Failures: 0, Errors: 0, Skipped: 132
IT   Tests run: 64, Failures: 0, Errors: 0, Skipped: 0

2024-03-13 10:56 UTC, Jiabao-Sun commented
Thanks @JingGe for the suggestions.
Brief change log Updated.

2024-03-13 11:13 UTC, ferenc-csaky commented
@Jiabao-Sun  FYI: I think I'll be finished with the review today or tomorrow.

2024-03-13 22:21 UTC, JingGe approved these changes
LGTM

2024-03-13 22:28 UTC, JingGe commented
> Brief change log

@Jiabao-Sun Thanks for the excellent summary! I have added it as the reference example in the description of [FLINK-25325](https://issues.apache.org/jira/browse/FLINK-25325)

2024-03-14 04:40 UTC, ferenc-csaky requested changes
Thanks for pushing this forward! Added some comments/suggestions.

2024-03-14 05:24 UTC, Jiabao-Sun commented on flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/partitioner/StreamPartitionerTest.java
> +    protected abstract StreamPartitioner<Tuple> createPartitioner();
Good point!

2024-03-14 05:29 UTC, Jiabao-Sun commented on flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/windowing/TumblingProcessingTimeWindowsTest.java
> +                .hasMessageContaining("TumblingProcessingTimeWindows");
Thanks.
I'll change the usage of deprecated `Time` to `Duration` as well.

2024-03-14 05:33 UTC, Jiabao-Sun commented on flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/windowing/TumblingProcessingTimeWindowsTest.java
> +                .hasMessageContaining("TumblingProcessingTimeWindows");
I found that in many test classes contain Time, I think it should be uniformly removed in Flink 2.0.

2024-03-14 05:41 UTC, Jiabao-Sun commented on flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/OneInputStreamTaskTest.java
> +        assertThat(
> the only reason for collecting the retrieved Gauge instances to a Set is to validate that none of them are null

Here, we are not checking for null; rather, we are examining whether there are duplicates among the five `Gauge`s to ensure that no metric has been registered multiple times.

2024-03-14 06:01 UTC, Jiabao-Sun commented on flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/windowing/MergingWindowSetTest.java
> +        assertThat(windowSet.addWindow(new TimeWindow(0, 13), mergeFunction))
Good catch!

2024-03-14 06:17 UTC, Jiabao-Sun commented
Thanks @ferenc-csaky for the hard review.
PTAL again when you have time.

2024-03-14 10:21 UTC, ferenc-csaky commented on flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/OneInputStreamTaskTest.java
> +        assertThat(
Right, I misinterpreted this part, but even the equals message clearly tells what happens here. :)

2024-03-14 10:23 UTC, ferenc-csaky commented on flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/windowing/TumblingProcessingTimeWindowsTest.java
> +                .hasMessageContaining("TumblingProcessingTimeWindows");
Fair point, makes sense. 👍

2024-03-14 10:27 UTC, ferenc-csaky approved these changes
Thanks for the quick updates @Jiabao-Sun, LGTM!

2024-03-15 10:07 UTC, merged