[FLINK-25537] [JUnit5 Migration] Module: flink-core with,Package: api
apache/flink pull request #24603
Opened 2024-04-02 06:48 UTC by GOODBOY008

Because flink-core is huge ， so split into multi pr to review.

Changes:

- Migrate mudule `flink-core`'s `api` package to junit5.

2024-04-02 08:25 UTC, GOODBOY008 commented
@Jiabao-Sun PTAL

2024-04-02 09:12 UTC, GOODBOY008 commented
I have compared https://github.com/apache/flink/actions/runs/8395180921/job/22994258945 (flink master) and https://github.com/GOODBOY008/flink/actions/runs/8517183618/job/23327527159 (my repo). The unit test count is same.

2024-04-02 10:14 UTC, Jiabao-Sun requested changes
Thanks @GOODBOY008 for this contribution.
I left some comments, and I will need another round to complete the review.

2024-04-04 16:20 UTC, Jiabao-Sun commented on flink-core/src/test/java/org/apache/flink/api/java/typeutils/runtime/AbstractGenericTypeComparatorTest.java
> +import org.junit.jupiter.api.Test;
The `@Test` methods visibility can be adjusted to package default.

2024-04-04 16:21 UTC, Jiabao-Sun commented on flink-core/src/test/java/org/apache/flink/api/java/typeutils/runtime/AbstractGenericTypeSerializerTest.java
> +import org.junit.jupiter.api.Test;
The `@Test` methods visibility can be adjusted to package default.

2024-04-04 16:23 UTC, Jiabao-Sun commented on flink-core/src/test/java/org/apache/flink/api/java/typeutils/runtime/PojoSerializerSnapshotTest.java
> +        assertThat(restoredSerializer.getClass() == PojoSerializer.class).isTrue();
instanceOf is better.

2024-04-04 16:24 UTC, Jiabao-Sun commented on flink-core/src/test/java/org/apache/flink/api/java/typeutils/runtime/PojoSerializerSnapshotTest.java
> +        assertThat(restoredSerializer.getClass() == PojoSerializer.class).isTrue();
instanceOf is better.

2024-04-04 16:27 UTC, Jiabao-Sun commented on flink-core/src/test/java/org/apache/flink/api/java/typeutils/runtime/PojoSerializerTest.java
> +                    && (nestedClass == null || nestedClass.equals(otherTUC.nestedClass));
IMO, these changes are not necessary and unrelated to the JUnit migration.

2024-04-04 16:28 UTC, Jiabao-Sun commented on flink-core/src/test/java/org/apache/flink/api/java/typeutils/runtime/PojoSerializerUpgradeTestSpecifications.java
> +                    "");
Can we provide a meaningful description?
There are many similar cases in this class.

2024-04-04 16:31 UTC, Jiabao-Sun commented on flink-core/src/test/java/org/apache/flink/api/java/typeutils/runtime/PojoSubclassSerializerTest.java
> +            return dumm2.equals(otherTUC.dumm2);
We don't need these changes in this PR.

2024-04-04 16:32 UTC, Jiabao-Sun commented on flink-core/src/test/java/org/apache/flink/api/java/typeutils/runtime/RowComparatorTest.java
> +            return Objects.equals(name, myPojo.name);
We don't need these changes int this PR.

2024-04-04 16:33 UTC, Jiabao-Sun commented on flink-core/src/test/java/org/apache/flink/api/java/typeutils/runtime/SubclassFromInterfaceSerializerTest.java
> +            return dumm2.equals(otherTUC.dumm2);
We don't need these changes in this PR.

2024-04-04 16:36 UTC, Jiabao-Sun commented on flink-core/src/test/java/org/apache/flink/api/java/typeutils/runtime/kryo/KryoSerializerSnapshotTest.java
>      public void sanityTest() {
```suggestion
   void sanityTest() {
```

2024-04-04 16:37 UTC, Jiabao-Sun commented on flink-core/src/test/java/org/apache/flink/api/java/typeutils/runtime/tuple/base/TuplePairComparatorTestBase.java
>      public void testEqualityWithReference() {
```suggestion
   void testEqualityWithReference() {
```

2024-05-06 11:22 UTC, Jiabao-Sun approved these changes
Thanks @GOODBOY008 for the quick fix. 
LGTM now.

2024-05-07 01:11 UTC, Jiabao-Sun commented
@flinkbot run azure

2024-05-07 09:33 UTC, merged