[FLINK-25537] [JUnit5 Migration] Module: flink-core with,Package: util
apache/flink pull request #24670
Opened 2024-04-16 08:52 UTC by GOODBOY008

2024-05-07 10:01 UTC, Jiabao-Sun requested changes
Thanks @GOODBOY008 for this contribution.
I left some comments.

2024-05-08 01:21 UTC, Jiabao-Sun reviewed
Thanks @GOODBOY008 for the quick fix.
Minor comments.

2024-05-08 01:21 UTC, Jiabao-Sun commented on flink-core/src/test/java/org/apache/flink/util/LinkedOptionalMapTest.java
> +        assertThat(m).containsKey(String.class);
```suggestion
        assertThat(m).containsKeys(String.class, Boolean.class);
```

2024-05-08 01:21 UTC, Jiabao-Sun commented on flink-core/src/test/java/org/apache/flink/util/SerializedValueTest.java
> +        assertThat(v.getByteArray().length).isNotEqualTo(0);
```suggestion
        assertThat(v.getByteArray()).isNotEmpty();
```

2024-05-08 01:21 UTC, Jiabao-Sun commented on flink-core/src/test/java/org/apache/flink/util/concurrent/ConjunctFutureTest.java
>      public static Collection<FutureFactory> parameters() {
```suggestion
    private static Collection<FutureFactory> parameters() {
```

2024-05-08 03:07 UTC, Jiabao-Sun commented on flink-core/src/test/java/org/apache/flink/util/SerializedValueTest.java
> +        assertThat(copy).hasSameHashCodeAs(v.hashCode());
```suggestion
        assertThat(copy).hasSameHashCodeAs(v);
```

2024-05-10 01:58 UTC, 1996fanrui reviewed
Thanks @GOODBOY008 for the contribution, and @Jiabao-Sun for the review!

I left some comments, also MdcUtilsTest is not changed, so I comment them here:

- All test method of MdcUtilsTest class have `public`, they can be removed.

Please take a look in your free time, thanks~

2024-05-10 01:58 UTC, 1996fanrui commented on flink-core/src/test/java/org/apache/flink/util/AbstractIDTest.java
> +        assertThat(id1.compareTo(CommonTestUtils.createCopySerializable(id1))).isZero();
```suggestion
        assertThat(id1).isEqualByComparingTo(CommonTestUtils.createCopySerializable(id1));
```

The rest can be updated as well

2024-05-10 01:58 UTC, 1996fanrui commented on flink-core/src/test/java/org/apache/flink/util/ReferenceTest.java
>  @ExtendWith({TestLoggerExtension.class})
TestLoggerExtension has been enabled at module level, so it can be removed here.

2024-05-10 01:58 UTC, 1996fanrui commented on flink-core/src/test/java/org/apache/flink/util/MathUtilTest.java
> +        assertThat(MathUtils.flipSignBit(Long.MIN_VALUE)).isEqualTo(0L);
```suggestion
        assertThat(MathUtils.flipSignBit(Long.MIN_VALUE)).isZero();
```

2024-05-10 01:58 UTC, 1996fanrui commented on flink-core/src/test/java/org/apache/flink/util/TimeUtilsTest.java
> +        assertThat(TimeUtils.parseDuration("1 D").toDays()).isEqualTo(1L);
Most of them can be updated to isOne().

2024-05-11 02:37 UTC, 1996fanrui approved these changes
Thanks for the update!

LGTM

2024-05-11 02:38 UTC, Jiabao-Sun approved these changes
Thanks @GOODBOY008 for this contribution and @1996fanrui for the review.
+1

2024-05-11 08:58 UTC, merged

2024-05-11 09:22 UTC, 1996fanrui commented
> @Jiabao-Sun @1996fanrui I will open hotfix to mater.

Sorry, I didn't notice it. I start fix it after I received the CI alert. 😂