[FLINK-35353][docs-zh]Translate "Profiler" page into Chinese
apache/flink pull request #24822
Opened 2024-05-22 04:47 UTC by drymatini

## What is the purpose of the change

"Profiler "page was released in English and it should be translated into Chineses

## Brief change log

translate 'docs/content/docs/ops/debugging/profiler.md'

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no)
  - The serializers: (no )
  - The runtime per-record code paths (performance sensitive): ( no )
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no )
  - The S3 file system connector: ( no )

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (no)

2024-05-22 04:48 UTC, drymatini commented
Hi @wuchong , I have finished the translation of the page.Could you please verify my pull request?

2024-05-28 06:50 UTC, drymatini commented
HI,@reswqa , I have finished the translation of the page.Could you please verify my pull request?

2024-05-31 12:30 UTC, JingGe commented on docs/content.zh/docs/ops/debugging/profiler.md
> +- 首先，您应找出性能瓶颈的 TaskManager/JobManager，然后切换到相应的 TaskManager/JobManager 页面（分析器选项卡）。
```suggestion
- 首先，你应找出性能瓶颈的 TaskManager/JobManager，然后切换到相应的 TaskManager/JobManager 页面（分析器选项卡）。
```
and replace all others. 
Reference：https://cwiki.apache.org/confluence/display/FLINK/Flink+Translation+Specifications

2024-06-04 13:12 UTC, drymatini commented
Hi @JingGe , thank you for the review, I have already made adjustment based on your opinion, please check my commit again.

2024-06-05 13:26 UTC, Myasuka requested changes
Thanks for creating this PR, please take a look at my comments.

2024-06-05 13:26 UTC, Myasuka commented on docs/content.zh/docs/ops/debugging/profiler.md
> +自 Flink 1.19 起，我们基于 Flink Web UI ，用 [异步分析器](https://github.com/async-profiler/async-profiler) 交互式地分析JobManager/TaskManager 进程， 让用户可以创建具有任意间隔和事件模式的分析实例，比如 ITIMER、CPU、Lock、Wall-Clock 和 Allocation。
`async-profiler` is the project name, and I don't think we need to translate this just like we don't translate `Flink` to chinese.

2024-06-05 13:26 UTC, Myasuka commented on docs/content.zh/docs/ops/debugging/profiler.md
> +- **ALLOCATION**: 在allocation 分析模式下， 每个调用跟踪的顶部框架是被分配对象的类，计数器是堆压力 （分配的TLAB或TLAB之外的对象的总大小）。
`计数器是堆压力` 这个描述太奇怪了，不如直接说成`对分配的TLAB或TLAB之外的对象的总大小的计数`

2024-06-05 13:26 UTC, Myasuka commented on docs/content.zh/docs/ops/debugging/profiler.md
> +由于分析器由异步分析器驱动，因此必须在异步分析器支持的平台上运行。
同理，这里不应该翻译`async-profiler`

2024-06-05 13:26 UTC, Myasuka commented on docs/content.zh/docs/ops/debugging/profiler.md
> +1. **CPU模式下无法进行分析：没有访问perf事件的权限。请试着使用-fdtransfer或--all-user选项或'sysctl kernel.perf_event_paranoid=1'** \
这里不应该翻译，毕竟原来的异常信息就是英文的

2024-06-05 13:26 UTC, Myasuka commented on docs/content.zh/docs/ops/debugging/profiler.md
> +2. **Allocation模型下无法进行分析: 未找到AllocTracer符号。是否安装了JDK调试符号？** \
同理，这里不应该翻译

2024-06-06 08:39 UTC, drymatini commented
Hi @Myasuka ,thank you for the comments, I have made changes to solve the problems, please check again.

2024-06-28 09:22 UTC, Myasuka approved these changes
LGTM, I'll then squash all the commits.

2024-06-28 09:31 UTC, closed without merging