[FLINK-35512[flink-clinets] Don't depend on the flink-clients jar actually existing.
apache/flink pull request #24931
Opened 2024-06-13 05:18 UTC by SamBarker

## What is the purpose of the change

Ensure that running `mvn clean verify` works for flink-clients (as is the recommended step from [contributing to flink](https://flink.apache.org/how-to-contribute/contribute-code/#3-open-a-pull-request)).

## Brief change log

  - *Unit test fix: not to depend on the artefact currently being built*
 

## Verifying this change

Please make sure both new and modified tests in this PR follow [the conventions for tests defined in our code quality guide](https://flink.apache.org/how-to-contribute/code-style-and-quality-common/#7-testing).

*(Please pick either of the following options)*

This change added tests and can be verified as follows:

  - *running `mvn clean package -pl :flink-clients`*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): **no**
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: **no**
  - The serializers: **no**
  - The runtime per-record code paths (performance sensitive): **no**
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: **no**
  - The S3 file system connector: **no**

## Documentation

  - Does this pull request introduce a new feature? **no**
  - If yes, how is the feature documented? **not applicable**|

2024-06-13 22:25 UTC, SamBarker commented
@flinkbot run azure

2025-01-07 10:09 UTC, ferenc-csaky commented
@flinkbot run azure

2025-01-10 16:53 UTC, afedulov requested changes
`getFlinkClientsJar()` is now unused, please remove it.

2025-01-13 13:26 UTC, ferenc-csaky commented
Added the following PRs, which all contain the requested changes by @afedulov:
- https://github.com/apache/flink/pull/25969
- https://github.com/apache/flink/pull/25970
- https://github.com/apache/flink/pull/25971

Kept @SamBarker as author. I plan to merge those 3 when all CI passed and approved and close this one.

2025-01-13 20:08 UTC, afedulov commented
Merged int the PRs listed [here](https://github.com/apache/flink/pull/24931#issuecomment-2587101672).

2025-01-13 20:08 UTC, closed without merging

2025-01-26 21:09 UTC, SamBarker commented
Thanks @ferenc-csaky I didn't manage to find the time while travelling with the family to make the changes