[FLINK-33875][runtime] Support slots wait mechanism at DeclarativeSlotPoolBridge side for Default Scheduler
apache/flink pull request #25134
Opened 2024-07-30 11:24 UTC by RocMarshal

## What is the purpose of the change

- Refactor FreeSlotInfoTracker to FreeSlotTracker for the better semantic
- Support slots wait mechanism at DeclarativeSlotPoolBridge side for Default Scheduler

## Brief change log

- Refactor FreeSlotInfoTracker to FreeSlotTracker for the better semantic
- Support slots wait mechanism at DeclarativeSlotPoolBridge side for Default Scheduler

## Verifying this change

This change added tests and can be verified as the corresponding core test classes.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no**)
  - The serializers: (yes / **no** / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / **no** / don't know)
  - Anything that affects deployment or recovery:  DefaultScheduler
  - The S3 file system connector: (yes / **no** / don't know)

## Documentation

  - Does this pull request introduce a new feature? (**yes** / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

2024-08-02 04:48 UTC, 1996fanrui commented on flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/slotpool/DeclarativeSlotPoolBridge.java
> +    private void fulfillMatchedSlots(
nit: all callers call `reserveMatchedFreeSlots` and `fulfillMatchedSlots` together, why do we need 2 methods?

As I understand, merge them into one method is enough: `reserveAndFulfillMatchedFreeSlots`.

2024-08-02 04:48 UTC, 1996fanrui commented on flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/slotpool/DeclarativeSlotPoolBridge.java
> +    private void newSlotsAvailableForNonSlotBatchAllocatable(
```suggestion
    private void newSlotsAvailableForDirectlyAllocatable(
```

how about updating the name to `newSlotsAvailableForDirectlyAllocatable`?

2024-08-03 03:31 UTC, RocMarshal commented
@flinkbot run azure

2024-08-05 09:46 UTC, 1996fanrui reviewed
Thanks @RocMarshal for the update!

Overall the PR LGTM, I only left some comments for test code. Please take a look in your free time, thanks~

2024-08-05 09:46 UTC, 1996fanrui commented on flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/slotpool/AbstractDeclarativeSlotPoolBridgeTest.java
> +            DeclarativeSlotPoolBridgeResourceDeclarationTest.RequirementListener
Is it possible that we don't pass `RequirementListener` here?

Alternative solution is : All tests of DeclarativeSlotPoolBridgeResourceDeclarationTest could call `requirementListener#tryWaitSlotRequestIsDone` directly.

In general, the parent class doesn't depends on the class inside of children class.

2024-08-05 09:46 UTC, 1996fanrui commented on flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/slotpool/DeclarativeSlotPoolBridge.java
> +    }
If last comment makes sense, could we move ` void tryWaitSlotRequestIsDone()` method to `DeclarativeSlotPoolBridgeTest`?

Only `DeclarativeSlotPoolBridgeTest` calls `tryWaitSlotRequestIsDone()`.

2024-08-06 08:00 UTC, 1996fanrui requested changes

2024-08-06 08:00 UTC, 1996fanrui commented on flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/slotpool/DeclarativeSlotPoolBridgeResourceDeclarationTest.java
> +    static final class RequirementListener {
After refactor, the original private may be enough, right?

2024-08-06 08:00 UTC, 1996fanrui commented on flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/slotpool/DeclarativeSlotPoolBridgeTest.java
> +    void tryWaitSlotRequestIsDone(DeclarativeSlotPoolBridge declarativeSlotPoolBridge) {
Could it be private?

2024-08-06 11:11 UTC, RocMarshal commented
HI, @1996fanrui Thank you very much for the quick review. I made some change based on your comments. PTAL if you had the free time~ :)

2024-08-07 06:26 UTC, 1996fanrui approved these changes
Thanks @RocMarshal for the update!

LGTM assuming the CI is green.

2024-08-08 01:39 UTC, merged