[FLINK-36510][rpc] bump pekko to 1.1.2, remove netty 3
apache/flink pull request #25494
Opened 2024-10-11 08:31 UTC by gracegrimwood

## What is the purpose of the change

Updates Pekko dependency to 1.1.2 which in turn upgrades Netty 3 to 4 (addressing [FLINK-29065](https://issues.apache.org/jira/browse/FLINK-29065) and removing several CVEs from Flink). Pekko 1.1 also upgrades other dependencies such as slf4j and Jackson. For more details see the [Pekko 1.1 release notes](https://pekko.apache.org/docs/pekko/current/release-notes/releases-1.1.html).

## Brief change log

  - Update Pekko version from 1.0.1 to 1.1.2
  - Replace Pekko Netty 3 dependency with flink-shaded Netty 4
  - Update Netty imports in `ActorSystemBootstrapTools` and `PekkoUtils`
  - Update NOTICE file

## Verifying this change

This change is covered by existing tests in flink-rpc.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): yes
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no
## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

2024-10-11 13:57 UTC, gracegrimwood commented
@flinkbot run azure

2024-10-14 13:47 UTC, tomncooper approved these changes

2024-10-16 05:31 UTC, ferenc-csaky requested changes
Probably the CI failure is independent from your change, I suggest to rebase against latest master as well.

2024-10-17 03:13 UTC, gracegrimwood commented on flink-rpc/flink-rpc-akka/pom.xml
> +			<artifactId>netty-all</artifactId>
Unfortunately we do still need to have Netty directly declared in the dependencies. If the `io.netty:netty-all` dependency is missing from the POM, Pekko throws at runtime with
`java.lang.IllegalStateException: Classic remoting is enabled but Netty is not on the classpath, it must be added explicitly. See https://pekko.apache.org/docs/pekko/current/remoting.html`. Those [Pekko docs](https://pekko.apache.org/docs/pekko/current/remoting.html) linked in the error message insist that it must be declared explicitly:
> Classic remoting depends on Netty. This needs to be explicitly added as a dependency so that users not using classic remoting do not have to have Netty on the classpath

The relocation is there so that we can use the `flink-shaded-netty` version for Pekko rather than having two seperate copies of Netty 4, it is not strictly necessary and there might be a better or nicer way to do it. But as far as I can tell there is no way to get around needing a direct Netty dependency here.

2024-10-17 05:39 UTC, gracegrimwood commented on flink-rpc/flink-rpc-akka/pom.xml
> +			<artifactId>netty-all</artifactId>
@SamBarker is right, after some testing it looks like the minimum we need here is `io.netty:netty-all` in `test` scope and the shade plugin relocation of `io.netty` to `org.apache.flink.shaded.netty4.io.netty`.

2024-10-17 15:05 UTC, ferenc-csaky commented on flink-rpc/flink-rpc-akka/pom.xml
> +			<artifactId>netty-all</artifactId>
Ah yeah, thanks for the detailed answer, quite some time ago I started to create a POC to migrate to Artery but forgot the whole context since then. :)

2024-10-17 15:05 UTC, ferenc-csaky commented
@flinkbot run azure

2024-10-17 22:28 UTC, SamBarker approved these changes
LGTM 

Thanks for picking this up @gracegrimwood

2024-10-20 16:41 UTC, ferenc-csaky approved these changes
LGTM! Thank you @gracegrimwood for picking up and concluding this long lasting improvement! :) Will merge this by Tuesday EOD CEST if no objections until then.

2024-10-22 16:58 UTC, merged