FLINK-36487 remove deprecated method createTemporaryView StreamTableE…
apache/flink pull request #25524
Opened 2024-10-15 12:16 UTC by jbalchan

…nvironment

## What is the purpose of the change

https://issues.apache.org/jira/browse/FLINK-36487 Remove deprecated method StreamTableEnvironment createTemporaryView

## Brief change log

Removed deprecated method

## Verifying this change

This change is already covered by existing tests

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: no
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no

## Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable

2024-10-16 10:53 UTC, davidradl requested changes
I notice that this method is referred to in the docs. [Here is an example
createTemporaryView ](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/sql/queries/overview/#specifying-a-query). I suggest replacing this example in the docs with one using the non-deprecated API. 
Also the [Python code](https://github.com/apache/flink/blob/38e749efd8c0d7d1332a1849872cc9b26cb84ce8/flink-python/pyflink/table/table_environment.py#L992) calls this deprecated method - so we should remove that also. 

I have updated the umbrella issue, : https://issues.apache.org/jira/projects/FLINK/issues/FLINK-36476 with the question if the Python API is not marked deprecated but the java API is deprecated - can we remove both - or isn't this against the deprecation rules.

2024-10-16 13:36 UTC, jbalchan commented
@flinkbot run azure

2025-01-02 05:45 UTC, xuyangzhong commented
Hi, @jbalchan the ci seems failed, can you take a look?

2025-01-08 10:53 UTC, xuyangzhong commented
@jbalchan any update? The code freeze date for flink 2.0.0 is approaching...

2025-01-09 13:45 UTC, jbalchan commented
@flinkbot run azure

2025-05-11 06:25 UTC, closed without merging