[hotfix] [docs]Fix miss semicolon on SELECT & WHERE clause example sql
apache/flink pull request #25673
Opened 2024-11-22 03:04 UTC by camilesing

## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*
Fix miss semicolon on SELECT & WHERE clause example sql.

## Brief change log
Add semicolon for miss semicolon example sql.

## Verifying this change

Since the changes affect the doc examples and there are no tests. I copied the snippets and verified (compiled) them locally.

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
  - The serializers: (no)
  - The runtime per-record code paths (performance sensitive): (no)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
  - The S3 file system connector: (no)

## Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

2024-11-22 11:10 UTC, davidradl approved these changes

2024-11-24 18:19 UTC, snuyanzin requested changes
Thanks for the contribution

IIRC semicolon is just a statement terminator and it always should be used to inform parser that the statement is finished, so it is ok to not specify it in such doc having this in mind.
Even more there is no concrete example with concrete environment.
For instance if we try to use these examples with Flink SQL Client then yes we need to use semicolon, however if we try to use this with Table SQL then there is no need for that

2024-11-25 02:35 UTC, camilesing commented
> Thanks for the contribution
> 
> IIRC semicolon is just a statement terminator and it always should be used to inform parser that the statement is finished, so it is ok to not specify it in such doc having this in mind. Even more there is no concrete example with concrete environment. For instance if we try to use these examples with Flink SQL Client then yes we need to use semicolon, however if we try to use this with Table SQL then there is no need for that

I know what you mean. But I suggest it's better to unify it in the docs, rather than having some IIRC and others not @snuyanzin

2024-11-25 20:51 UTC, snuyanzin commented
then I don't think the unification is limited only to `select.md`

you can have a look at 
https://nightlies.apache.org/flink/flink-docs-release-1.20/docs/dev/table/sql/queries/limit/
https://nightlies.apache.org/flink/flink-docs-release-1.20/docs/dev/table/sql/queries/orderby/
https://nightlies.apache.org/flink/flink-docs-release-1.20/docs/dev/table/sql/queries/joins/
https://nightlies.apache.org/flink/flink-docs-release-1.20/docs/dev/table/sql/queries/group-agg/
and many more including chinese version
and you'll see that lots of queries are without semicolon
and also I think it would make sense to ask for instance in ML whether the community is ok with such unification (not sure about this yet..)

2024-11-26 02:04 UTC, camilesing commented
> then I don't think the unification is limited only to `select.md`
> 
> you can have a look at https://nightlies.apache.org/flink/flink-docs-release-1.20/docs/dev/table/sql/queries/limit/ https://nightlies.apache.org/flink/flink-docs-release-1.20/docs/dev/table/sql/queries/orderby/ https://nightlies.apache.org/flink/flink-docs-release-1.20/docs/dev/table/sql/queries/joins/ https://nightlies.apache.org/flink/flink-docs-release-1.20/docs/dev/table/sql/queries/group-agg/ and many more including chinese version and you'll see that lots of queries are without semicolon and also I think it would make sense to ask for instance in ML whether the community is ok with such unification (not sure about this yet..)

You might be right in a way. So, who will ask for the mailing list?  @snuyanzin

2025-05-09 06:26 UTC, closed without merging